### ISSUE TITLE
Missing select family of functions

### ISSUE THREAD

**Issue by flaub** [rust-lang/libc#10]
Looks like this belongs either in `bsd42` or `posix01`.

From `select(2)` of Linux man pages:

```
/* According to POSIX.1-2001 */
#include <sys/select.h>

/* According to earlier standards */
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>

int select(int nfds, fd_set *readfds, fd_set *writefds,
           fd_set *exceptfds, struct timeval *timeout);

void FD_CLR(int fd, fd_set *set);
int  FD_ISSET(int fd, fd_set *set);
void FD_SET(int fd, fd_set *set);
void FD_ZERO(fd_set *set);
```

From `select(2)` of BSD System Calls Manual:

```
     #include <sys/select.h>

     void
     FD_CLR(fd, fd_set *fdset);

     void
     FD_COPY(fd_set *fdset_orig, fd_set *fdset_copy);

     int
     FD_ISSET(fd, fd_set *fdset);

     void
     FD_SET(fd, fd_set *fdset);

     void
     FD_ZERO(fd_set *fdset);

     int
     select(int nfds, fd_set *restrict readfds, fd_set *restrict writefds, fd_set *restrict errorfds, struct timeval *restrict timeout);
```

And then on Windows, which only works for sockets:

```
int select(
  _In_    int                  nfds,
  _Inout_ fd_set               *readfds,
  _Inout_ fd_set               *writefds,
  _Inout_ fd_set               *exceptfds,
  _In_    const struct timeval *timeout
);
```

With `FD_CLR`, `FD_ISSET`, `FD_SET`, and `FD_ZERO` defined as macros on most (all?) platforms.

**Comment by flaub** [comment]
With this layer in place, it would be possible to extend the `std::net::*Socket` API to allow for cancelation of pending I/O operations (`recv`, `recv_from`, `send`, `accept`, etc). This would fix rust-lang/rust#23272 and mentioned in rust-lang/rfcs#957. The goal here would *not* be to allow non-blocking I/O in general per-se, but to simply provide a way for users to cleanly cancel blocking calls.

**Comment by alexcrichton** [comment]
Thanks for the report! Currently we're not trying to track all the missing APIs in liblibc, though, (there are quite a few!). You're more than welcome to add the bindings, however! If you make a PR against the main Rust repo then we can update the submodule here once that's landed.

**Comment by flaub** [comment]
Ok, I'll take a stab, thanks for the reply :)

**Comment by flaub** [comment]
I see now that many of the low level functions are actually implemented directly in libstd/sys.

**Comment by keepsimple1** [comment]
Is `select` available now in Rust std? I couldn't find it in the current Rust 1.59.
