### ISSUE TITLE
termios2 shouldn't exist on musl targets

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/libc#1006]
`musl` doesn't include the termios2 API, but those structs are declared by libc. They should be removed.

**Comment by gnzlbg** [comment]
I think we can go ahead and do this breaking change, care to submit a PR ?

**Comment by Susurrus** [comment]
I already have a PR in #629, however it contains other breaking changes to datatypes around termios. Do you want me to break it out as a separate PR or is that whole PR on the table for merging?

**Comment by gnzlbg** [comment]
Separate PR would be better

**Comment by Susurrus** [comment]
I think this can be closed now that #629 was merged.
