### ISSUE TITLE
fdopendir on macOS

### ISSUE THREAD

**Issue by scottlamb** [rust-lang/libc#1017]
I'd like to use `fdopendir`, but it's missing on macOS.

Looks like 99a524d added `fdopendir` to...

   * `src/unix/bsd/freebsdlike/mod.rs`
   * `src/unix/bsd/netbsdlike/mod.rs`
   * `src/unix/haiku/mod.rs b/src/unix/haiku/mod.rs`
   * `src/unix/notbsd/mod.rs`
   * `src/unix/solaris/mod.rs`

and it was copied into `src/unix/uclibc/mod.rs` when that was created in 6e4beb6.

so it's there for everything but macOS and "newlib" (which I guess is [this](https://sourceware.org/newlib/)?). As far as I can tell, both those platforms do have it. macOS apparently added it in 10.10 (see chneukirchen/nq#6).

Could this just be in `src/unix/bsd/mod.rs` rather than the freebsdlike/netbsdlike subdirs? or even in `src/unix/mod.rs` (like `fdopen`) since all existing platforms support it?

**Comment by alexcrichton** [comment]
Thanks for the report! It's ok for APIs to only be in one module and not others, that's what libc is all about!
