### ISSUE TITLE
getresgid values different from C

### ISSUE THREAD

**Issue by sevagh** [rust-lang/libc#1046]
Hello. `libc::getresgid` is giving me seemingly incorrect values. I am on Linux x86_64: Fedora 28, kernel 4.17, X86_64 (Thinkpad T450 with Intel i5 processor).

Rust code:
```
let mut rgid = 0u32;
let mut egid = 0u32;
let mut sgid = 0u32;

unsafe { libc::getresgid(&mut rgid, &mut egid, &mut sgid) };

println!("{} {} {}", rgid, egid, sgid);
```
Rust output:
```
65534 65534 65534
```
C code:
```
static gid_t egid, rgid, sgid;
getresgid(&rgid, &egid, &sgid);
printf("Result of getresgid():\n\t%u %u %u\n", egid, rgid, sgid);
```
C output:
```
Result of getresgid():
        1000 1000 1000
```
Bash output:
```
$ id -g
1000
```
Could this be a bug?

**Comment by alexcrichton** [comment]
Can you poke around the executables to see if there's a difference? Does `strace` report different syscalls? Does your system have a different symbol for `getresgid`?

**Comment by sevagh** [comment]
Thanks for the help Alex. Embarrassingly :cry: , I forgot that my call to `getresgid` was in a namespace:

```
unshare(...)
getresgid(...)
```
So the values were correct, for the namespace I created with `unshare`.
