### ISSUE TITLE
Route netlink C header #define's PR?

### ISSUE THREAD

**Issue by jbaublitz** [rust-lang/libc#1059]
This is a follow up to #921 which tracks the PR that implemented genetlink constants. I maintain a [netlink library](https://github.com/jbaublitz/neli) but am now implementing the next subsystem in netlink (rtnetlink). I would like to add the constants in the rtnetlink subsystem now that I have a request to provide support for this. If I provide the PR, would you be willing to review and merge it?

**Comment by alexcrichton** [comment]
Definitely! Always willing to have more constants and defines here :)

**Comment by jbaublitz** [comment]
Great! I'll gather all of the rtnetlink constants into a PR when I get a moment.

**Comment by jbaublitz** [comment]
I'm mostly done with this and will be ready to try CI soon. Mainly just making sure this doesn't get closed as I'm actively working on it again. I got pulled away from my side projects for a long while.

**Comment by gnzlbg** [comment]
Glad to hear that!
