### ISSUE TITLE
MAP_ANONYMOUS is missing on Mac

### ISSUE THREAD

**Issue by mikebenfield** [rust-lang/libc#1060]
On my Mac, I get this:

```
error[E0425]: cannot find value `MAP_ANONYMOUS` in module `libc`
  --> src/us/mod.rs:34:38
   |
34 |             libc::MAP_SHARED | libc::MAP_ANONYMOUS,
   |                                      ^^^^^^^^^^^^^ not found in `libc`

```

Now here's what's a little odd... a Google search reveals lots of people (using C) talking about MAP_ANONYMOUS being absent on Macs, which I guess is why it's not in `libc`. But it's definitely present on my system. This C program compiles:

```
#include<stdio.h>
#include<sys/mman.h>
int main() {
  printf("%d", MAP_ANONYMOUS);
}
```

**Comment by alexcrichton** [comment]
Interesting! If it compiles maybe it was added recently? In any case if it exists then it should be good to add! Our CI will catch it if it's not defined

**Comment by jack-pappas** [comment]
It looks as though the constant is called ``MAP_ANON`` on OSX, although the mmap.h header also defines ``MAP_ANONYMOUS`` as an alias:
https://github.com/apple/darwin-xnu/blob/0a798f6738bc1db01281fc08ae024145e84df927/bsd/sys/mman.h#L127
