### ISSUE TITLE
support for RS485

### ISSUE THREAD

**Issue by xoac** [rust-lang/libc#1094]
Hi,
There exist crate [rs485](https://github.com/mbr/rs485-rs/blob/master/src/lib.rs#L49) that define const from libc. The problem is that `ioctls` change signature depending on system platform (for example it accept `c_int` when using musl on x86 and `c_ulong` when use glibc on x86_64). So compilation fill when musl is involved:

```
rust-musl-builder-armv7 cargo build --examples                                                                                                              18:21:01 
   Compiling rs485 v0.1.0
error[E0308]: mismatched types
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rs485-0.1.0/src/lib.rs:92:45
   |
92 |         let rval = unsafe { libc::ioctl(fd, TIOCGRS485, &mut conf as *mut SerialRs485) };
   |                                             ^^^^^^^^^^ expected i32, found u32

error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rs485-0.1.0/src/lib.rs:186:45
    |
186 |         let rval = unsafe { libc::ioctl(fd, TIOCSRS485, self as *const SerialRs485) };
    |                                             ^^^^^^^^^^ expected i32, found u32

```  

It would be nice to add  this constants (`TIOCGRS485`, `TIOCSRS485`) to libc. I am not sure how to do it properly. For musl target constant can be found here:
http://git.musl-libc.org/cgit/musl/tree/arch

in most cases looks like this:
```
#define TIOCGRS485	0x542E
#define TIOCSRS485	0x542F
```
but there are different here:
http://git.musl-libc.org/cgit/musl/tree/arch/mips64/bits/ioctl.h#n61

**Comment by alexcrichton** [comment]
Looks like you've got a [PR for this](https://github.com/rust-lang/libc/pull/1095), which sounds great to me!

**Comment by xoac** [comment]
@gnzlbg I think no -- I just added implementation to musl target and it's still missing for others. I don't need more since I use just musl -- but I think rs485 crate will still fail to compile on others platform.

**Comment by gnzlbg** [comment]
The RS485 crate define the constants itself, so it cannot fail to compile AFAICT.

**Comment by xoac** [comment]
It can fail `c_int` and `c_ulong` are different types. Since libc (this crate) didn't define it. So rs485 failed to compile on musl buf successful for example on glibc.
`libc::ioctl` on musl required `c_int` (i32) but got `c_long`(u32) [as defined in RS485 crate]. Now when libc define `TIOCGRS485` and `TIOCSRS485` it can be used in rs485 crate - and it will successfully compile on all defined platforms <3

**Comment by gnzlbg** [comment]
> Now when libc define TIOCGRS485 and TIOCSRS485 it can be used in rs485 crate - and it will successfully compile on all defined platforms <3

AFAICT this is only true if these constants have the appropriate types.
