### ISSUE TITLE
Missing declaration of SCM_TIMESTAMPING in x86-32?

### ISSUE THREAD

**Issue by gz** [rust-lang/libc#1103]
The SCM_TIMESTAMPING declaration is available in 64bit
https://github.com/rust-lang/libc/blob/4bd52f5e3ef5d6c8abdd1fbaf7c9975800a0dc93/src/unix/notbsd/linux/other/b64/x86_64.rs#L375

but missing in the 32bit version:
https://github.com/rust-lang/libc/blob/8565755356f23baf6b2df933ff734ce2f00c8d9b/src/unix/notbsd/linux/other/b32/mod.rs#L207

Is it possible to add this? Also since it is a linux kernel extension rather than a libc issue, it would also be feasible to add it to musl?

https://github.com/rust-lang/libc/tree/4bd52f5e3ef5d6c8abdd1fbaf7c9975800a0dc93/src/unix/notbsd/linux/musl

I'm happy to submit the necessary pull requests if you think this is ok. It's currently blocking https://github.com/nix-rust/nix/pull/902

**Comment by alexcrichton** [comment]
Thanks for the report! So long as our CI passes it should be good to add this!
