### ISSUE TITLE
Missing definitions for SOF_TIMESTAMPING_*

### ISSUE THREAD

**Issue by gz** [rust-lang/libc#1104]
The SOF_TIMESTAMPING_* definitions from https://github.com/torvalds/linux/blob/master/include/uapi/linux/net_tstamp.h are currently missing. Would it be acceptable to add these? I'm happy to submit a pull request if someone can advise me where the best place to put them is.

This issue is currently blocking https://github.com/nix-rust/nix/pull/902

**Comment by alexcrichton** [comment]
Similar to https://github.com/rust-lang/libc/issues/1103, a PR would be most welcome! So long as CI passes we should be good to go
