### ISSUE TITLE
CStr should be in libc and libstd should re-export that

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/libc#1120]
Currently `CStr` lives in `std::ffi` which means that it cannot be used in `core`+`libc` projects without requiring `libstd` as well. 

This type cannot go into `core` because it is platform-dependent (e.g. on `libc::c_char`), but it could be moved down to libc (without the `use_std` feature), when `use_std` is enabled, `libc` could just re-export the type from `std`.

**Comment by jplatte** [comment]
Why has this issue been closed immediately? I'd be interested in using `CStr` without `std`.

**Comment by gnzlbg** [comment]
Since `ffi::CStr` is not FFI-safe it cannot be used in FFI so adding it to `libc` makes no sense.
