### ISSUE TITLE
MS_RMT_MASK changed in Linux 4.0

### ISSUE THREAD

**Issue by diwic** [rust-lang/libc#113]
Hi,
In Linux < 4.0, the MS_RMT_MASK is correct,
in Linux >= 4.0, the [MS_RMT_MASK was changed to 0x2800051](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=0ae45f63d4ef8d8eeec49c7d8b44a1775fff13e8) to support the lazytime option.

I needed to change that in order to make the test run here. Probably this is the more compatible way as well, but I'm not sure if I can just change it without breaking tests running on older kernels...?

**Comment by jimblandy** [comment]
Support for MS_LAZYTIME was added to libc [last June][1], along with the change to MS_RMT_MASK, but it seems like the glibc on the CI systems is older than that.

The flag is available from <linux/fs.h>, but I think we shouldn't be using that, for reasons I describe in pull request #127.

[1]: https://sourceware.org/git/?p=glibc.git;a=commit;h=31545c23277cd54a1edd41c85d8255fb589158e3

**Comment by alexcrichton** [comment]
Ah yeah this should be fine to change, if the CI doesn't like it then it's fine to add an exception to handle special cases like this.

**Comment by nodakai** [comment]
Memo: glibc 2.22 and musl 1.1.13 or later includes `MS_LAZYTIME` as `MS_RMT_MASK`

**Comment by jimblandy** [comment]
> Memo: glibc 2.22 and musl 1.1.13 or later includes MS_LAZYTIME as MS_RMT_MASK

I think you mean "includes `MS_LAZYTIME` *in* `MS_RMT_MASK`"?

Right; glibc 2.22 was the first release to include those definitions.

**Comment by posborne** [comment]
Hah, missed that a fix for this was already upstream.  This can probably be closed.

**Comment by alexcrichton** [comment]
Ok!
