### ISSUE TITLE
nl_pad is private and is required to be initialized for sockaddr_nl

### ISSUE THREAD

**Issue by WillYee** [rust-lang/libc#1135]
https://github.com/rust-lang/libc/blob/5b403753da9ec8ff501adf34cb6d63b319b4a3ae/src/unix/uclibc/mod.rs#L82

I was able to fix this buy marking nl_pad as pub

**Comment by gnzlbg** [comment]
PR welcome :)

**Comment by gnzlbg** [comment]
FWIW you don't need to access `nl_pad` to initialize the struct, e.g., you can use `MaybeUninit<sockaddr_nl>::zeroed()` to zero the struct, and then only initialize the relevant fields.

**Comment by gnzlbg** [comment]
Alternatively, you can use `let x: sockaddr_nl = unsafe { mem::zeroed() };` on stable Rust, although if you can use nightly `MaybeUninit` is preferable.
