### ISSUE TITLE
Policy of supported platform version for constant values

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/libc#1142]
We have many bugs where the value of a constant does not match the value of the constant in the users system. 

I think that, at least for constants, we should support the latest released version of the platform, and that we do not consider upgrading a constant value a breaking change. 

If the `libc` crate ever gets support for multiple versions of the same platform, we should revisit this policy.

**Comment by alexcrichton** [comment]
I agree! For now upating constants as they're updated on the system hasn't caused problems and seems like we should continue to do so
