### ISSUE TITLE
Fuchsia is part of the main cfg_if switch but also part of unix

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/libc#1143]
See: https://github.com/rust-lang/libc/search?q=fuchsia&unscoped_q=fuchsia

Fuchsia has a top-level module fuchsia, but it also has stuff in src/unix/notbsd/mod.rs and src/unix/notbsd/linux/mod.rs . 

Does `target_os` linux return `true` for `fuchsia` ?

**Comment by alexcrichton** [comment]
These are likely copy/paste errors perhaps?

**Comment by cramertj** [comment]
It used to live in `unix/` but then got moved to a separate `fuchsia/`. I'm guessing I missed removing these when I made that change.

**Comment by gnzlbg** [comment]
This should all be clean on master. We are now minimally testing some fuchsia targets on CI (x86_64 and aarch64 IIRC).
