### ISSUE TITLE
Support SOCK_NONBLOCK and SOCK_CLOEXEC

### ISSUE THREAD

**Issue by jamperry** [rust-lang/libc#115]
These values provide convenience when created sockets via `socket` to add non blocking and closing--on-exec flags as it saves calling `fcntl(2)`. 

I am happy to write a patch for this if you accept this issue. There are some gotchas because

`SOCK_NONBLOCK` != `O_NONBLOCK`
`SOCK_CLOEXEC` != `FD_CLOEXEC`

for certain architectures. 

This is due to socket flag state would be be overridden so it uses a different enumerate value.

**Comment by jamperry** [comment]
Here's the MAN page for socket to give some background information: http://man7.org/linux/man-pages/man2/socket.2.html

**Comment by alexcrichton** [comment]
Ah yeah I've definitely wanted these in the past, they're more than welcome here! May just take some hunting to find the BSD definitions, but those aren't critical to land.

**Comment by polachok** [comment]
http://bxr.su/search?q=&defs=SOCK_CLOEXEC&refs=&path=&project=DragonFly&project=FreeBSD&project=NetBSD&project=OpenBSD

**Comment by alexcrichton** [comment]
Oh wow, that's quite a useful link, thanks @polachok!

**Comment by alexcrichton** [comment]
Closing as these were added in https://github.com/rust-lang/libc/pull/150, yay!
