### ISSUE TITLE
Consider moving FreeBSD tests to Cirrus-CI

### ISSUE THREAD

**Issue by asomers** [rust-lang/libc#1163]
libc's FreeBSD tests are currently using QEMU on Travis-CI.  This is bad for three reasons:
1) It's slow
2) It's complicated
3) Somebody (@wezm I believe) has to build a new image for every release.

Cirrus-ci.com just launched their new FreeBSD service.  It works much like Travis, but it has the option of using full VMs instead of just containers.  They currently provide images for four different versions of FreeBSD, and building new images is probably easier than with QEMU.  https://cirrus-ci.org/guide/FreeBSD/ .  Here's an example of a Rust project using Cirrus: https://github.com/asomers/tokio-file/pull/6 .

**Comment by wezm** [comment]
> Somebody (@wezm I believe) has to build a new image for every release.

I updated them last time out of need (to get the build to pass with a change I had made) and documented the process. Having Cirrus manage this sounds like it's work trying.

**Comment by gnzlbg** [comment]
@alexcrichton thoughts ? This requires enabling Cirrus-CI for `rust-lang/libc`, I don't know exactly which permissions Cirrus-CI would like to have, but as long as they are reasonable it might be worth it to enable it and let those interested send PRs to support it.

The same applies to https://builds.sr.ht/ which offers native FreeBSD and OpenBSD VMs. It's in beta, but they said that if we are interested, we should drop them an email: sir@cmpwn.com . Their "pricing" is extremely reasonable ("as much as we want to pay" with a minimum of 2$ / month...) and they are nice (this is how wlroots is tested on those platforms). I'm sure they would help us set things up.

**Comment by gnzlbg** [comment]
@alexcrichton it seems that Cirrus-CI requires:

> * Read access to code
> * Read access to members, metadata, pull requests, and single file
> * Read and write access to checks and commit statuses

**Comment by alexcrichton** [comment]
Seems plausible to me to set up!

**Comment by asomers** [comment]
@alexcrichton if you're willing, please follow the instructions at https://cirrus-ci.org/guide/quick-start/ to configure the Cirrus CI application on libc's github repo.  Stop when you get to the "Post Installation" step.  I can submit a PR to do the rest.

**Comment by alexcrichton** [comment]
Ok that's been done! Or at least I'm pretty sure it's done

**Comment by inferiorhumanorgans** [comment]
This would be good to mention in the top-level README.  Currently the tests badge links to appveyor (windows tests only), there's a link further down in the README to the travis-ci bits (Linux, Apple), but none for Cirrus (and I'm not sure what the URL is for the libc tests on the Cirrus site :/).

FWIW the tests are not completing successfully for me on FreeBSD 12 so I'm trying to figure out if they're passing or not on the CI system.

**Comment by inferiorhumanorgans** [comment]
Oh! I missed the travis badge.  At the risk of bikeshedding, would it be worth using a table for the build status?
