### ISSUE TITLE
Fix flakiness of Android builds

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/libc#1170]
In https://github.com/rust-lang/libc/pull/1159 I'm configuring some android builds under "allowed failures". They've been insanely flaky recently and are basically just serving as preventing things from landing currently. This issue is intended to track re-enabling these as gating by default on CI

**Comment by gnzlbg** [comment]
I don't know exactly why these stall. Sometimes things fail to download, so maybe retying multiple times would help, but some times the installer just hangs waiting for a `Y/n` input =/
