### ISSUE TITLE
Add statx linux system call so we can implement fs::Metadata::created on Linux

### ISSUE THREAD

**Issue by ariasuni** [rust-lang/libc#1178]
Right now, `std::fs::Metadata::created` returns an `Err` on Linux. But the creation time is available with the `statx` system call.

https://unix.stackexchange.com/a/407305/289105

**Comment by alexcrichton** [comment]
Should be fine to send a PR to add this API!

**Comment by gnzlbg** [comment]
We haven't added other syscalls in the past (e.g. `memfd_create`: https://github.com/rust-lang/libc/pull/902#issuecomment-361280295). There is nothing blocking using this syscall in `std::fs` btw, you can just use `syscall` to call it yourselfe, like, e.g., I did with `memfd_create` here: https://github.com/gnzlbg/slice_deque/blob/master/src/mirrored/linux.rs#L18

**Comment by ariasuni** [comment]
@gnzlbg There is a `statx()` wrapper in glibc but the man page is not up-to-date (fixed upstream but not yet released).

I’m not sure what’s the best way to access the creation information under Linux (if I want to implement a workaround in the meantime), since you mentioned using the syscall directly (note btw that there’s no `SYS_statx` in the `libc` crate).

**Comment by gnzlbg** [comment]
There does not seem to be any open rust-lang/rust issues about this.
