### ISSUE TITLE
SYS_calls should be bound

### ISSUE THREAD

**Issue by nagisa** [rust-lang/libc#121]
Since there’s a binding to `syscall` function, `SYS_*` constants should also be bound. Perhaps in their own module, since there’s so many of them.
- [ ] Linux (???)
- [ ] [Android](https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.7-4.6/+/master/sysroot/usr/include/bits/syscall.h) where __NR are defined in unistd_{[32](https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.7-4.6/+/master/sysroot/usr/include/asm/unistd_32.h),[64](https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.7-4.6/+/master/sysroot/usr/include/asm/unistd_64.h)};
- [ ] [FreeBSD](http://fxr.watson.org/fxr/source/sys/syscall.h?v=FREEBSD10);
- [ ] [NetBSD](http://fxr.watson.org/fxr/source/sys/syscall.h?v=NETBSD);
- [ ] [OpenBSD](http://fxr.watson.org/fxr/source/sys/syscall.h?v=OPENBSD);
- [ ] [Apple](http://www.opensource.apple.com/source/xnu/xnu-1228.5.20/bsd/sys/syscall.h)

**Comment by alexcrichton** [comment]
Sounds good to me, should be relatively easy enough to add at any time!

**Comment by kamalmarhubi** [comment]
I am willing to take this on. I've been wanting to script getting constants anyway—at least on Linux— and this is a great excuse.

**Comment by kamalmarhubi** [comment]
Also re Linux, I found the easiest place to get the sycall numbers is actually in from musl source, eg:
- http://git.musl-libc.org/cgit/musl/tree/arch/aarch64/bits/syscall.h
- http://git.musl-libc.org/cgit/musl/tree/arch/powerpc/bits/syscall.h

It'll be worth putting these in a joint musl / other location though. Probably `unix::notbsd::linux::syscalls`, which will be included by others.

**Comment by alexcrichton** [comment]
For now I'd prefer to just stick with duplication, it's not that hard to have and it presents a much more understandable organization hierarchy

**Comment by kamalmarhubi** [comment]
Sounds good.

**Comment by posborne** [comment]
:+1: for scripting this and getting consistent, complete coverage.

**Comment by Susurrus** [comment]
@alexcrichton I think this is addressed as there are tons of `SYS_*` constants now in `libc`.

**Comment by alexcrichton** [comment]
Indeed!
