### ISSUE TITLE
Cirrus-CI is failing

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/libc#1225]
@asomers https://cirrus-ci.com/task/5732382389829632

**Comment by asomers** [comment]
Looks intermittent.  Have you retried?

**Comment by asomers** [comment]
Cirrus has fixed the particular issue that caused that job to abort.  In general, Cirrus is usually pretty quick about fixing these things, if you report the failure to their github repo.  You can close this issue now.
https://github.com/cirruslabs/cirrus-ci-docs/issues/137

**Comment by gnzlbg** [comment]
Thanks!
