### ISSUE TITLE
Libc on osx now requires rust 1.24.0+

### ISSUE THREAD

**Issue by erickt** [rust-lang/libc#1232]
The rand crate tries to maintain compatibility with rust 1.22.0, but a recent release of libc now implicitly requires [1.24.0 on osx](https://github.com/rust-random/rand/issues/719) due to this patch: rust-lang/libc#1212, which uses a constant function that was stablized in 1.24. It appears that the Travis config is trying to maintain compatibility with 1.13, but this test only runs on Linux.

Now I personally don't care what is the minimum version you want to support, but given how libc is now the most actively used dependency, you drive the minimum version of a lot of the ecosystem, so would it be possible to at least document this requirement, or setup some more test targets to make sure this doesn't [happen again accidentally](https://github.com/rust-lang/libc/issues/1229)?

**Comment by gnzlbg** [comment]
@erickt thank you for the report and sorry for the inconvenience. 

We should:

* detect whether the Rust version is >= 1.24 in our build.rs file, and define a `cfg` flag that is used to white-list const fns in those cases. The functions can be exposed as non-const fn in older Rust versions. 

* run cargo build for nightly, beta, and stable, on all build bots using Rust 1.13 as the stable Rust version

I can look into implementing both of these things.

**Comment by gnzlbg** [comment]
cc @Stebalien @erickt libc mater builds again down to Rust 1.13. There are a couple of PRs with fixes in the queue. Once those are merged I'll do a new release.

**Comment by gnzlbg** [comment]
I forgot to mention what I wanted to mention. Would you be able to test if the master branch solves your issues ? (e.g. by creating a PR to your projects that use the libc master branch and letting your CI run?).

**Comment by dhardy** [comment]
We still appear to have a problem using Rustc 1.22 on OSX: https://travis-ci.org/rust-random/rand/jobs/493719761 (use of `mem::size_of` as a const fn). Is this because the relevant changes are not in a release yet?

I don't have a Mac platform to test with myself.
See also: https://github.com/rust-random/rand/issues/719

**Comment by gnzlbg** [comment]
> Is this because the relevant changes are not in a release yet?

Yes. The changes are on master, and a release is blocked on the affected parties testing that master does not have these issues.

**Comment by dhardy** [comment]
Okay, I forced Travis to use libc master via a patch section. [The test now succeeds](https://travis-ci.org/rust-random/rand/builds/493850447?utm_source=github_status&utm_medium=notification) on OSX with Rustc 1.22.0 where it didn't before. So seems to have fixed it.
