### ISSUE TITLE
Remove align cargo feature

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/libc#1242]
I'd like to remove the align cargo feature (or make it a dummy), and automatically use `repr(align)` if the Rust version is new enough (newer than Rust 1.25.0). 

In particular, I'd like for libc to not expose the C APIs that use `repr(align)` if `repr(align)` is not available anymore. This would be a breaking change, but using these APIs without the proper alignment is undefined behavior anyways (unless one is super super super careful). 

Users that want to use these APIs and are currently on Rust versions older than Rust 1.25.0 can either stick to an older `libc` version or upgrade to at least Rust 1.25.0.

**Comment by gnzlbg** [comment]
Well, this is worse than I thought. Using `repr(align(N))` anywhere (even behind a `#[cfg_attr]`) requires at least Rust 1.25.0 . That is, any target that wants to optionally use `repr(align)` needs to bump the minimum required Rust version to 1.25.0. 

cc @alexcrichton - a couple of targets already do this, maybe we should bump the minimum supported libc version to Rust 1.25.0 and call it a day. It might well be that `libc` works with older Rust versions in some targets, but I don't think we should guarantee that. In any case, gating `align` behind a cargo feature doesn't do anything, since Rust 1.25 is required for the cargo feature to actually work.

**Comment by gnzlbg** [comment]
Alternatively, we could move all code that uses `repr(align(N))` into separate modules, and put the module declaration behind the feature gate. For example,

```rust
#[cfg(libc_align)]
mod align;
```

**Comment by Mark-Simulacrum** [comment]
The modules would/could be completely transparent to downstream users, right? Via re-exports?

**Comment by gnzlbg** [comment]
Yes, I am already working on that, but it is a pain due to how many targets are already depending on it.

**Comment by josephlr** [comment]
@gnzlbg I think bumping libc's supported version to 1.25 is not unreasonable. Of the most popular crates, `lazy_static` has 1.24 as the min version, `bitflags` has 1.20, `rand` has 1.22. However, `serde`, `syn`, and `log` all have much lower required versions (~1.15)

**Comment by alexcrichton** [comment]
1.25.0 is a bit too recent I think for libc, but we could detect this in the build script and auto-enable the feature I believe?

**Comment by gnzlbg** [comment]
FWIW libc now auto-detect whether `repr(align)` is available. The `align` feature still works as it worked before. I don't think we can ever remove it without breaking projects that want to be able to work properly on a very wide range of libc versions.
