### ISSUE TITLE
mq_attr checks __reserved and pad fields in PartialEq comparison

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/libc#1302]
We run tests on mq_attr, and moving from our `PartialEq` implementation to `libc`'s broke those tests because these fields are compared. They are only used for alignment on some platforms and can contain junk data on some platforms. These fields should be skipped when doing a comparison of these structs.

**Comment by gnzlbg** [comment]
FWIW these fields should be private, so that one day we can remove them and switch to just properly using `repr(align)`.

**Comment by gnzlbg** [comment]
> Do you know if there's anything stopping us from making them that way, as I know we already do that for some other types?

If you mean about making them `repr(align)`, the main issue, I think, is bumping the minimum supported Rust version to Rust 1.25.0 (which is ~1 year old). Maybe when Rust 1.25 is 1.5-2 years old we can just do that.

**Comment by Susurrus** [comment]
There's the `repr(align)` feature we can use and only implement it like that for that feature.

Note that this problem also exists for the `sockaddr_nl` type which has the `nl_pad` field, which should be ignored for equality but currently isn't (I don't know if we can just remove that field and specify `repr(align)`).

**Comment by gnzlbg** [comment]
@Susurrus it seems this should be possible, we manually write these implementations for some types.

**Comment by Susurrus** [comment]
So my question is what are the right next steps here. Removing the `pad` and `__reserved` fields in favor of `repr(align)` or manually implementing `PartialEq` for these types?

**Comment by gnzlbg** [comment]
Making those fields private if they aren't yet, and manually implementing PartialEq would be a good start. If you want to use `repr(align)`, I strongly recommend doing that _afterwards_ in a subsequent PR because `repr(align)` is not available on all toolchains that we currently have to support.
