### ISSUE TITLE
Linux 3.10.0-693.2.2.el7.x86_64 seems to somehow expose inconsistent sysctl API 

### ISSUE THREAD

**Issue by przygienda** [rust-lang/libc#1311]
ewnough said, API changed in mutability on first parameter and ptr/size? and that breaks crates like e.g. sysctl ...

**Comment by gnzlbg** [comment]
> ewnough said,

libc has a million APIs, so it would at least be nice to know which API, which target triple, minimum working example (no dependencies) with instructions to reproduce, etc.

**Comment by przygienda** [comment]
nightly-x86_64-unknown-linux-gnu

sysctl(...)  call changed mutability of parameters ... 

reproduce: try to compile sysctl crate which takes libc and uses sysctl(..) calls

**Comment by gnzlbg** [comment]
Read https://github.com/rust-lang/libc/pull/1312/files .

**Comment by gnzlbg** [comment]
The last commit that changed `sysctl` on x86_64-unknown-linux-gnu is from 2 years ago (https://github.com/rust-lang/libc/commit/343b7c15bea8777399ab5e667239e6bbe8239542) and landed on libc 0.2.33. There aren't any commits between 0.2.50 and 0.2.51 touching that API.

**Comment by gnzlbg** [comment]
rust-semverver also reports no breaking changes between 0.2.50 and 0.2.51 on `x86_64-unknown-linux-gnu` (https://travis-ci.com/rust-lang/libc/jobs/188694789#L819) and it checks for changes in function signature types.

**Comment by przygienda** [comment]
thanks, yet somehow it looks like updating to .51 broke sysctl here. I will try to get you an example today to verify it's not something else

**Comment by przygienda** [comment]
Looked @ it further, it looks like an issues taht has nothing to do with newest libc release but been there since a bit. confusing, it compiles on other plaforms (BSD & MacOS)

Affects stable and nightly ... 

--- here's the info, code taken out directly from sysctl-rs crate 

extern crate libc;
use libc::{sysctl, c_int, c_void};

fn main() {
    let oid: [c_int; 2] = [0, 3];

    let mut len: usize = 32;

    // We get results in this vector
    let mut res: Vec<c_int> = vec![0; 32 as usize];

    let name = "abc";

    let ret = unsafe {
        sysctl(
            oid.as_ptr(),
            2,
            res.as_mut_ptr() as *mut c_void,
            &mut len,
            name.as_ptr() as *const c_void,
            name.len(),
        )
    };
}
[prz@rahi-01 ~/gitlab/sysctl-break]$cargo +stable build
   Compiling sysctl-break v0.1.0 (/home/prz/gitlab/sysctl-break)
error[E0308]: mismatched types
  --> src/main.rs:16:13
   |
16 |             oid.as_ptr(),
   |             ^^^^^^^^^^^^ types differ in mutability
   |
   = note: expected type `*mut i32`
              found type `*const i32`

error[E0308]: mismatched types
  --> src/main.rs:20:13
   |
20 |             name.as_ptr() as *const c_void,
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ types differ in mutability
   |
   = note: expected type `*mut libc::c_void`
              found type `*const libc::c_void`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `sysctl-break`.

To learn more, run the command again with --verbose.
$cargo +stable --version
cargo 1.33.0 (f099fe94b 2019-02-12)
$uname -a
Linux 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gnzlbg** [comment]
Is there a version of libc that compiled that example for that target correctly?

**Comment by przygienda** [comment]
https://github.com/johalun/sysctl-rs/issues/22  seems like crate was never tested on linux albeit I remember ages ago to have it working
