### ISSUE TITLE
MAP_SHARED_VALIDATE is missing on Linux

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/libc#1315]
`MAP_SHARED_VALIDATE` (defined in mmap(2)) is missing in libc, for linux >= 4.15.

For instance the following code should, I think, compile:
```rust
let p = libc::mmap(
    std::ptr::null_mut(),
    4096,
    libc::PROT_READ | libc::PROT_WRITE,
    libc::MAP_SHARED_VALIDATE | libc::MAP_ANONYMOUS,
    -1,
    0,
);
```

Thank you for your time! :)

**Comment by gnzlbg** [comment]
This is fixed on master.
