### ISSUE TITLE
Solarish __posix_readdir_r symbol is only for 32-bit libc

### ISSUE THREAD

**Issue by jasonbking** [rust-lang/libc#1318]
As discovered building the latest 'fd', the `__posix_readdir_r` symbol is only available in the Solaris & illumos 32-bit libc.  For 32-bit libraries, there is some confusing symbol shuffling that occurs to provide compatibility between traditional Solaris, draft POSIX, and official POSIX behavior for `readdir_r` (which is where `__posix_readdir_r` originates).

By the time 64-bit was introduced in Solaris, that was resolved and there is only `readdir_r` for 64-bit binaries.  Since rust (currently) only supports 64-bit targets on Solarish (Solaris & illumos) targets, the symbol renaming in mod.rs is unnecessary.

**Comment by gnzlbg** [comment]
How do we fix this ?

**Comment by jasonbking** [comment]
The PR to fix the issue was merged a month ago.  Is there some other problem that's come up?

**Comment by gnzlbg** [comment]
No, just checking. Thanks!
