### ISSUE TITLE
Ubuntu 17.10 repository is no longer available

### ISSUE THREAD

**Issue by mati865** [rust-lang/libc#1333]
It will result in following jobs failure: https://github.com/rust-lang/libc/search?l=Dockerfile&q=17.10

cc https://github.com/rust-lang/libc/pull/1297

**Comment by gnzlbg** [comment]
We should probably update directly to the latest Ubuntu version.  Will do that after #1337 is merged.

**Comment by jackpot51** [comment]
@gnzlbg I recommend to update to 18.04, not the latest. It is a long term support version and will be supported for at least another 4 years, whereas 19.04 will only be supported until January of next year.

**Comment by gnzlbg** [comment]
The main issue with the upgrades is that, instead of doing small incremental upgrades every year, we do a huge one every 4 years. Also, we technically only support the latest release of `libc` on most platforms, and we have to add many workarounds to do that while using a 4 year old version in CI.

**Comment by jackpot51** [comment]
That is a good point. If it is possible to keep it up to date every 6 months, then that would be best. However, with many things still running 17.10... you will already have to jump three fourths the length of an LTS cycle to get to 19.04

**Comment by gnzlbg** [comment]
Yeah, I'll focus first on getting CI back running again, so that we can merge the open PRs and unblock work in rust-lang/rust. Once that happens, we can start slowly migrating to newer Ubuntu versions in CI.
