### ISSUE TITLE
gettimeofday has incorrect signature 

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/libc#1338]
The signature of `gettimeofday` incorrect on ~~most~~ all targets:

```
error: incompatible pointer types returning 'int (struct timeval *, struct timezone *)' from a function with result type 'int (*)(struct timeval *, void *)' [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return gettimeofday;
```

we should see if we can fix it. Will depend on how many crates are using it.

**Comment by oherrala** [comment]
Found this warning from [parking_lot_core 0.4.0](https://crates.io/crates/parking_lot_core). Seems to still be in use in master branch also.

Code: https://github.com/Amanieu/parking_lot/blob/3259fd72e0d76e9c9a6f31ff41a996648fe9ccfa/core/src/thread_parker/unix.rs#L210

```
warning: use of deprecated item 'libc::gettimeofday': The signature of this function is incorrect. If you are using it, please report that in the following issue so that we can e
valuate the impact of fixing it: https://github.com/rust-lang/libc/issues/1338
   --> /Users/oherrala/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.4.0/src/thread_parker/unix.rs:200:13
    |
200 |     let r = libc::gettimeofday(&mut now, ptr::null_mut());
    |             ^^^^^^^^^^^^^^^^^^
```

**Comment by oherrala** [comment]
Found this warning from time 0.1.42. Still in use in master also.

Code: https://github.com/rust-lang-deprecated/time/blob/324d2eb89354c412f520dbb29ef2c812085010a9/src/sys.rs#L497

```
warning: use of deprecated item 'libc::gettimeofday': The signature of this function is incorrect. If you are using it, please report that in the following issue so that we can evaluate the impact of fixing it: https://github.com/rust-lang/libc/issues/1338
   --> /Users/oherrala/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.1.42/src/sys.rs:497:22
    |
497 |             unsafe { libc::gettimeofday(&mut tv, ptr::null_mut()); }
    |                      ^^^^^^^^^^^^^^^^^^
```

**Comment by faern** [comment]
I can probably update `parking_lot` quickly if you change the signature. I'm working on pretty large changes there as we speak anyway. So don't let that library hold you back IMO.

**Comment by gnzlbg** [comment]
Thank you both, it seems that we can't easily fix the signature of `gettimeofday` without breaking a lot of code.
