### ISSUE TITLE
Test failures: bad ucontext_t size, bad function pointers for scanf family of functions

### ISSUE THREAD

**Issue by ibabushkin** [rust-lang/libc#1341]
On target `x86_64-unknown-linux-gnu` (Void Linux w/ glibc 2.29),
in `libc-test`, `cargo test --test main` fails as follows (paths redacted):
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running /path/to/libc/target/debug/deps/main-f3d552575350a420
RUNNING ALL TESTS
bad ucontext_t size: rust: 936 (0x3a8) != c 968 (0x3c8)
bad fscanf function pointer: rust: 140532381063520 (0x7fd03ea71960) != c 140532381067792 (0x7fd03ea72a10)
bad scanf function pointer: rust: 140532381063712 (0x7fd03ea71a20) != c 140532381067552 (0x7fd03ea72920)
bad sscanf function pointer: rust: 140532381063920 (0x7fd03ea71af0) != c 140532381068000 (0x7fd03ea72ae0)
bad NFT_MSG_MAX value at byte 0: rust: 22 (0x16) != c 25 (0x19)
thread 'main' panicked at 'some tests failed', /path/to/libc/target/debug/build/libc-test-0947c93ea2bf2100/out/main.rs:13:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::begin_panic
             at /rustc/3f5152e200c0c02dfe0f79367948c98053d35855/src/libstd/panicking.rs:408
   6: main::main
             at /path/to/libc/target/debug/build/libc-test-0947c93ea2bf2100/out/main.rs:13
   7: std::rt::lang_start::{{closure}}
             at /rustc/3f5152e200c0c02dfe0f79367948c98053d35855/src/libstd/rt.rs:64
   8: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
   9: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  10: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  11: std::rt::lang_start
             at /rustc/3f5152e200c0c02dfe0f79367948c98053d35855/src/libstd/rt.rs:64
  12: main
  13: __libc_start_main
             at ../csu/libc-start.c:308
  14: _start
             at ../sysdeps/x86_64/start.S:120
error: test failed, to rerun pass '--test main'
```

I haven't had time yet to check on a fresh install or different hardware, but I think this is worth our attention.

**Comment by gnzlbg** [comment]
@ibabushkin the tests are only intended to run inside the docker containers, so don't worry about that.

---

@mati865 ^^^ looks like there are some people using glibc 2.29 already, for which those functions will point to the incorrect addresses.

**Comment by ibabushkin** [comment]
Alright, good to know. I think one should adjust the directions in `CONTRIBUTING.md` then, since that mentions running the tests but does not point out that detail :)

**Comment by mati865** [comment]
I'm also using glibc 2.29 based distro but haven't noticed issues yet (apart from not working libc tests :smile:).

**Comment by gnzlbg** [comment]
I think you'd have to build a program that directly calls `fscanf`/`scanf`/`sscanf`. The error message basically says, that the call will jump to a function at some address, which is different from the address of those functions. 

Whether that's problematic or not, it depends. It might well be that `glibc` 2.29 modified any of this functions in some backward incompatible way (IIRC from the changelog, this happened), but to avoid breaking old binaries, they keep a copy of the old function at the same address, and add a new function symbol at a different address. 

It can also mean that we have a bug somewhere, and when you call that function, execution jumps somewhere it shouldn't and the program crashes.

**Comment by gnzlbg** [comment]
So here it is: https://github.com/bminor/glibc/blob/ce7eb0e90315eb1939ac29f656d39b3db858c092/libio/bits/stdio-ldbl.h#L29

We might want to define `DEPRECATED_SCANF` macro before including the glibc headers, so that the C code that we use to test links to the deprecated function symbols. This would allow Rust code to continue to link against older glibc's. 

The alternative would be to change the `#[link_name]` of these functions to point to the correct symbols, but this means that linking will fail when an older glibc is dynamically linked, which might not have them.

**Comment by ibabushkin** [comment]
I agree that that spot is the place to add the disclaimer about Docker (as that is where I looked initially for pre-PR testing directions). I'll whip something up once I verify a working setup.

Regarding the function symbol issue -- https://github.com/bminor/glibc/commit/03992356e6fedc5a5e9d32df96c1a2c79ea28a8f this commit suggests one gets the modern scanf (which is not all that different) in most reasonable configurations already, so I presume that is what one might want to go with. I have no idea what the model to support older libc versions is though, and what ramifications this has in general.

**Comment by mati865** [comment]
@ibabushkin see https://github.com/rust-lang/libc/pull/1337
