### ISSUE TITLE
semver build jobs broken

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/libc#1343]
The semver build jobs are failing to build: https://travis-ci.com/rust-lang/libc/jobs/200647230#L409

cc @ibabushkin

**Comment by ibabushkin** [comment]
I am aware of the problem. I also have a partial fix laying around, but it is still failing some of semverver's own tests, mostly regarding trait impls. I'll push that to git and you can check whether the test failures affect the use of semverver for libc.

**Comment by gnzlbg** [comment]
Thank you for looking into this @ibabushkin , I just wanted to notify you. We allow the build jobs to fail, so they should become "green" automatically once the next semverver version is released if all test pass, or "red" if semver changes are detected.

**Comment by JohnTitor** [comment]
It's now worked with the pinned nightly version.
