### ISSUE TITLE
syscalls missing for musl aarch64

### ISSUE THREAD

**Issue by dianpopa** [rust-lang/libc#1348]
Hi,

Should not the list of syscalls from [rust-lang-aarch64-musl-syscalls](../blob/master/src/unix/notbsd/linux/musl/b64/aarch64.rs) be the same as [musl-libc-aarch64-syscalls](https://git.musl-libc.org/cgit/musl/tree/arch/aarch64/bits/syscall.h.in)?

In my [project](https://github.com/firecracker-microvm/firecracker) that I compile against musl libc and which I run on aarch I am trying to whitelist the `fstat` syscall but I cannot pass compilation since [rust-lang's file](../blob/master/src/unix/notbsd/linux/musl/b64/aarch64.rs) does not contain it.

Can you please advise?

**Comment by gnzlbg** [comment]
If there is a syscall missing for the `musl` target, PRs welcome.

**Comment by gnzlbg** [comment]
So I'm closing this. If there is a particular syscall that you need, either fill a more explicit issue, or send a PR adding the syscall.

**Comment by dianpopa** [comment]
Fixed by #1435.
