### ISSUE TITLE
How to use my local libc when building rust from souce code?

### ISSUE THREAD

**Issue by BaoshanPang** [rust-lang/libc#1369]
Hi Exports,

I am seeing this issue:

$ git clone https://github.com/rust-lang/rust.git

$ git clone https://github.com/rust-lang/libc.git

$ cd rust

$ # edit Cargo.toml in rust to contain this line in field [patch.crates-io]:

libc = {path = “../libc” }

$ ./x.py build

Then the erros appear:

error: the feature cfg_target_vendor has been stable since 1.33.0 and no longer requires an attribute to enable –> /home/bpang/rust_ref/libc/src/lib.rs:22:13 | 22 | feature(cfg_target_vendor, link_cfg, no_core) | ^^^^^^^^^^^^^^^^^ | = note: -D stable-features implied by -D warnings

error: unused attribute –> /home/bpang/rust_ref/libc/src/lib.rs:27:1 | 27 | #![no_std] | ^^^^^^^^^^ | = note: -D unused-attributes implied by -D warnings

error: crate-level attribute should be in the root module –> /home/bpang/rust_ref/libc/src/lib.rs:27:1 | 27 | #![no_std] | ^^^^^^^^^^

error: aborting due to 3 previous errors

Is this a known problem? or there is something wrong in my steps?

Thanks,
Baoshan

**Comment by gnzlbg** [comment]
You should probably ask in rust-lang/rust, you might need to tweak other things in your config or in x.py to do that.

**Comment by BaoshanPang** [comment]
Hi gnzlbg,

Thanks for your response.

If we need to change some thing in libc and want to see if it works in rust, what's the normal process we usually do?

I asked the question in rust, but so far nobody answer me.

Thanks,
Baoshan

**Comment by semarie** [comment]
@BaoshanPang libc crate is used at several levels in rustc.

if you want to test things inside rustc, you want to change files in `rust/src/libclibc` directory. It is an embedded version of `libc` crate used by the compiler.

else, your changes in the crate `libc` will be only used by  rustbuild (the rust program that will build `rustc`) and not in `rustc` itself.

**Comment by BaoshanPang** [comment]
@semarie 

The directory rust/src/liblibc disappears since rust version 1.33, the rustc crate has been used since then.

**Comment by JohnTitor** [comment]
I'm going to close this as it's stale and don't have to be tracked here but on rust-lang/rust or other places like the internal forum.
