### ISSUE TITLE
Potential breakage in pthread_kill/pthread_t

### ISSUE THREAD

**Issue by neoeinstein** [rust-lang/libc#1383]
Building `cargo-outdated` for `x86_64-unknown-linux-musl` and ran into this error while compiling a dependency:

```
   Compiling jobserver v0.1.13
error[E0308]: mismatched types
   --> /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/jobserver-0.1.13/src/lib.rs:665:40
    |
665 |                     libc::pthread_kill(self.thread.as_pthread_t(), libc::SIGUSR1);
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected *-ptr, found u64
    |
    = note: expected type `*mut imp::libc::c_void`
               found type `u64`
```

**Comment by gnzlbg** [comment]
@neoeinstein that's correct, `pthread_t` is a pointer in musl, not an `u64`. What's the return type of `as_pthread_t()` ? If it isn't `pthread_t`, there is the bug.

**Comment by gnzlbg** [comment]
So `as_pthread_t` does return `pthread_t`, but it returns that from a different `libc` version.

**Comment by gnzlbg** [comment]
That is, `libstd` includes some older `libc`-version, where `pthread_t` has a different type, and it includes that one, which is incompatible with the new type. That is, IIUC, there are two versions of `libc` in the dependency graph.

**Comment by gnzlbg** [comment]
I have a libstd PR open that should fix this on nightly, but I wonder whether we should just revert this change.

**Comment by gnzlbg** [comment]
@neoeinstein So AFAICT, this was never intended to work. `libstd`'s `pthread_t` type has been deprecated since Rust 1.8.0 and the warning says that the type alias is incorrect and should not be used. 

I'm closing this issue but feel free to re-open if you disagree.

**Comment by gnzlbg** [comment]
Wait. So... the alias is deprecated, but it is used by APIs like JoinHandleExt that, for some reason, are not deprecated...

**Comment by neoeinstein** [comment]
I am not knowledgeable in this area, so I have no objections. I will file a similar report over at `jobserver` so that they can make the appropriate correction on their end.

**Comment by gnzlbg** [comment]
@neoeinstein i've got a PR open upstream that might fix it, so that jobserver and similar don't have to: https://github.com/rust-lang/rust/pull/61428
