### ISSUE TITLE
Pthread_t change broke musl

### ISSUE THREAD

**Issue by mati865** [rust-lang/libc#1396]
Using latest `libc` causes issues on musl because of this:
```
error[E0308]: mismatched types
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/jobserver-0.1.13/src/lib.rs:665:40
    |
665 |                     libc::pthread_kill(self.thread.as_pthread_t(), libc::SIGUSR1);
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected *-ptr, found u64
    |
    = note: expected type `*mut imp::libc::c_void`
               found type `u64`
```
It's because `pthread_t` type in `libc` changed to correct one but `libstd` still use wrong one.

**Comment by mati865** [comment]
Even with https://github.com/rust-lang/rust/pull/61428 merged stable and beta will remain broken.

To handle it gracefully `libc` would have to detect `pthread_t` type exported by `libstd` and use the same.

**Comment by gnzlbg** [comment]
I don't think this is a libc bug. Neither `libc` nor `libstd` promise that `libstd::RawPthread` and `libc::pthread_t` are type aliases to the exact same type. IIUC, this is actually intended to not be the case by design.

That is, the bug here is in the user code that assume that passing a `libstd::RawPthread` to a `libc` API taking a `libc::pthread_t` is portable code. It is not. The portable way of interfacing a `libstd::RawPthread` with a `libc::pthread_t` is, AFAICT, to use `mem::transmute`.

**Comment by gnzlbg** [comment]
Having said that, it is unclear to me how to fix this, or whether it is worth fixing. How much user code is impacted by this ?

**Comment by mati865** [comment]
At least everything that depends on `jobserver` won't build: https://crates.io/crates/jobserver/reverse_dependencies
Cargo is one of listed crates so this is very likely to break building of Cargo for musl toolchain unless there is workaround applied to `jobserver`.

**Comment by gnzlbg** [comment]
IIRC a workaround to jobserver was already applied ?

**Comment by gnzlbg** [comment]
I don't know if that was the "proper" workaround, AFAICT the proper workaround is just using a `mem::transmute` here, although for the time being at least using a `raw_pthread as _` should work as well since an `usize` can be cast into a `*mut c_void`.

**Comment by mati865** [comment]
> IIRC a workaround to jobserver was already applied ?

Not for this issue:
https://github.com/alexcrichton/jobserver-rs/blob/15b93a7caac18dd9aedd686e7c8381cef3fd450c/src/lib.rs#L667

**Comment by gnzlbg** [comment]
Indeed, I might have confused jobserver with some other project. See https://github.com/alexcrichton/jobserver-rs/pull/14

**Comment by gnzlbg** [comment]
@mati865 so a new version of jobserver has been released with a fix, could you let me know whether that solves this issue ?

**Comment by mati865** [comment]
It works, thanks.
