### ISSUE TITLE
What is the minimum iOS version we target?

### ISSUE THREAD

**Issue by josephlr** [rust-lang/libc#1406]
As part of https://github.com/rust-random/getrandom/issues/38 we are trying to figure out if we can reliably use the macOS/iOS [`getentropy(2)`](https://www.unix.com/man-page/mojave/2/getentropy/) function (added in macOS 10.12 and iOS 10).

The [Rust Platform Support](https://forge.rust-lang.org/platform-support.html) page has a minimum version for macOS (10.7) but not for iOS. Given that [distribution of iOS installs](url) is _much_ better than that of macOS or Android, I think setting iOS 10 to be the minimum supported version would be reasonable.

 If we do decide the that Rust's min iOS version is `>= 10`, we should at least add all the new libc functions added since then (including `getentropy`).

**Comment by gnzlbg** [comment]
AFAICT we can add the API here, but whether rust-random/getrandom should use it or not, depends on which iOS versions that crate wants to support. If it wants to support older versions, then it should probably query the iOS version and provide a workaround. 

Or in other words, libc does not guarantee that all provided APIs are available on all HOSTs of a particular platform. It is up to the users of libc to make sure that the APIs they are using are actually available on the HOSTs where their binaries run.

**Comment by josephlr** [comment]
>  If it wants to support older versions, then it should probably query the iOS version and provide a workaround.

The main reason I ask is that there is a proposal (rust-lang/rust#62082) to make `getrandom` a dependancy of Rust's `std`. So figuring out the min iOS version for that seems important. I agree that this is not a `libc` issue though.

**Comment by gnzlbg** [comment]
That feels like it would be a libstd issue. One can probably use a atomic function pointer that is set on initialization to use different implementations depending on the iOS version. Doing that only requires relaxed atomic loads and stores.

**Comment by gnzlbg** [comment]
I'm closing this, since adding an API here just exposes the FFI wrapper. It has nothing to do with the minimum iOS version that libstd supports - that's up to libstd to decide, and that will determine whether they can use a certain API or not.
