### ISSUE TITLE
Support future riscv64-unknown-linux-elf target

### ISSUE THREAD

**Issue by fintelia** [rust-lang/libc#1415]
Rust currently has support for bare metal RISC-V targets, but cannot compile for RISC-V Linux ones because it lacks standard library support. This is partially blocked because the libc crate does not recognize `target_arch = "riscv64"` and thus does not export symbols like `c_int`, `c_void`, and `uintptr_t` for it.

**Comment by gnzlbg** [comment]
A good place to start would be by adding a docker container for the target, e.g., that install gcc-riscv64-linux-gnu libc6-dev-riscv64-cross qemu-system-riscv64, and compiles libc for the target. That should not be blocked by anything. 

If compilation fails, that container can be added to `allow_failures:` in the .travis.yml.

**Comment by tgross35** [comment]
It seems like this may have been addressed by https://github.com/rust-lang/libc/pull/1684. Please feel free to reopen or refile if that isn't the case.
