### ISSUE TITLE
Building for x86_64-unknown-redox results in an empty crate

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/libc#1420]
See for example generated [docs](https://rust-lang.github.io/libc/x86_64-unknown-redox/libc/index.html). I think it was overlooked in  #1332 and until rust-lang/rust#60139 lands we should use `#[cfg(any(unix, target_os="redox"))]` [here](https://github.com/rust-lang/libc/blob/master/src/lib.rs#L116).

cc @jackpot51

**Comment by mati865** [comment]
No longer an issue with nightly toolchain.
