### ISSUE TITLE
Conflict between RLIMIT_NLIMITS and RLIMIT_RTTIME on linux-musl

### ISSUE THREAD

**Issue by Nugine** [rust-lang/libc#1446]
## Conflict

libc 0.2.60

[src/unix/linux_like/linux/musl/mod.rs#L255](https://github.com/rust-lang/libc/blob/2b01f7e67322175e05f25325e6e941aa9a3ddeae/src/unix/linux_like/linux/musl/mod.rs#L255) `RLIMIT_RTTIME` is 15

[GitHub Search](https://github.com/search?utf8=%E2%9C%93&q=RLIMIT_NLIMITS+repo%3Arust-lang%2Flibc+path%3Asrc%2Funix%2Flinux_like%2Flinux%2Fmusl&type=Code&ref=advsearch&l=&l=) However, `RLIMIT_NLIMITS` is also 15 inside the module.

## CI Test

Here is my test code.
```c
#include <stdio.h>
#include <sys/resource.h>
typedef int i32;
typedef unsigned long long u64;

int main() {
    printf("size of rlim_t: %d\n", (i32)sizeof(rlim_t));
    printf("RLIM_INFINTY: %llu\n", (u64)(RLIM_INFINITY));

#ifdef RLIMIT_NLIMITS
    printf("RLIMIT_NLIMITS: %d\n", (i32)(RLIMIT_NLIMITS));
#endif

#ifdef RLIMIT_RTTIME
    printf("RLIMIT_RTTIME: %d\n", (i32)(RLIMIT_RTTIME));
#endif

    return 0;
}
```

Some parts of ci log:
```
$ export TARGET=x86_64-unknown-linux-musl
...

size of rlim_t: 8
RLIM_INFINTY: 18446744073709551615
RLIMIT_NLIMITS: 16
RLIMIT_RTTIME: 15
...

Compiling rlimit v0.2.1 (/project)
error[E0081]: discriminant value `15` already exists
  --> src/lib.rs:79:14
   |
76 |     NLIMITS = libc::RLIMIT_NLIMITS as isize,
   |               ----------------------------- first use of `15`
...
79 |     RTTIME = libc::RLIMIT_RTTIME as isize,
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ enum already has `15`
error: aborting due to previous error
```

There is the same problem on target `i686-unknown-linux-musl`.

**Comment by Nugine** [comment]
Oops. I didn't use musl toolchain to compile my test code.

Here is the output.
```test
$ musl-gcc test_rlimit.c && ./a.out
size of rlim_t: 8
RLIM_INFINTY: 18446744073709551615
RLIMIT_NLIMITS: 15
```

**Comment by gnzlbg** [comment]
I think this probably means that RLIMIT_RTTIME was added to a musl version that we do not support yet.

**Comment by gnzlbg** [comment]
We currently support musl 1.1.22 with the sanitized kernel headers for the  "4.4.2" kernel. You are welcome to bump that up in CI (e.g. see https://github.com/rust-lang/libc/blob/master/ci/install-musl.sh) and upgrade the library.

**Comment by Nugine** [comment]
I solved the problem by specifying targets. Thanks for your answer!
