### ISSUE TITLE
Platform support section in Readme out of date

### ISSUE THREAD

**Issue by atouchet** [rust-lang/libc#1465]
> See ci/build.sh for the platforms on which libc is guaranteed to build for each Rust toolchain. The test-matrix at [Travis-CI], [Appveyor], and Cirrus-CI show the platforms in which libc tests are run.

The Travis and AppVeyor links were removed in #1376.

**Comment by atouchet** [comment]
Perhaps related but Cargo.toml also still lists:

`[badges]
travis-ci = { repository = "rust-lang/libc" }
appveyor = { repository = "rust-lang/libc", project_name = "rust-lang-libs/libc" }
`

Should those be removed as well?

**Comment by gnzlbg** [comment]
> Should those be removed as well?

Yes, we should add a badge for azure-pipelines.

**Comment by atouchet** [comment]
The Readme was fixed in 07d1f7a4957802e0c80be564fd4e4e470e4781e2 but Cargo.toml still needs to be updated.

**Comment by atouchet** [comment]
This was finished in #1687.
