### ISSUE TITLE
Weird cfgs in VxWorks module

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/libc#1469]
VxWorks module contains weird, always false `cfg`s, which look like a copypaste leftovers:
https://github.com/rust-lang/libc/blob/d7907c00e1a5061b4701e3d4aefca0ce4a181974/src/vxworks/mod.rs#L966-L970

**Comment by BaoshanPang** [comment]
@newpavlov 

Thanks for pointing it out, I will work on it.

**Comment by newpavlov** [comment]
Fixed in #1473
