### ISSUE TITLE
posix_fadvise() and POSIX_FADV_*

### ISSUE THREAD

**Issue by cybergeek94** [rust-lang/libc#148]
I'm working on an application which will be reading many small files, but only once each. I'd like to be able to use `posix_fadvise(fd, 0, 0, POSIX_FADV_WILLNEED)` to tell the kernel to asynchronously prefetch the file so when it comes time to access it, it will already have been pulled into the page cache in its entirety (less than 1MB on average) and can be read with minimal blocking.

I was going to implement this myself and issue a PR, but I noticed the semantically similar `posix_madvise()` has its constants (`POSIX_MADV_*`) duplicated across the Linux and various BSD/misc *nix modules and I'm not sure why because they have the same values AFAICT.

**Comment by alexcrichton** [comment]
Ah sometimes it's hard to keep track of the constants and where they go as they go through various revisions. The only really important part is that there is few `#[cfg]` annotations everywhere and the definitions themselves are correct (verified via the CI for this crate).

Feel free to collapse all equivalent constants higher up in the hierarchy, and also feel free to add more bindings!
