### ISSUE TITLE
Update rust to fix musl builds

### ISSUE THREAD

**Issue by aidanhs** [rust-lang/libc#15]
I'm in no particular hurry about this, I've just created the issue so I can be notified when it's closed.

https://github.com/rust-lang/rust/commit/52862e4cda1ff72e52dfaea21cf82ae93725b3be#diff-4c1827e2ef5156ad90c1cef13755f4c8

**Comment by alexcrichton** [comment]
Done!

**Comment by alexcrichton** [comment]
Ended up yanking 0.1.9 due to [compatibility concerns](https://github.com/rust-lang/libc/issues/16)

**Comment by dhuseby** [comment]
@alexcrichton this will also need to be updated to pick up the FreeBSD i686 changes when [Rust PR #27360 lands](https://github.com/rust-lang/rust/pull/27360).

**Comment by dhuseby** [comment]
I'll send you a PR.  The only question is if I need to bump the minor version or just the patch number.

**Comment by agrover** [comment]
This is a blocker for me. I need flock(2) for http://github.com/agrover/melvin. I added it to Rust repo on June 24, but until libc crate is updated I can't update nix-rust, and then start using it in my project. @alexcrichton I know you say in #17 you're busy but I just wanted to describe my situation to maybe increase this issue's relative status a little.

**Comment by aidanhs** [comment]
Why not just use a .cargo file? http://doc.crates.io/guide.html#overriding-dependencies

Clone the repo (with submodules), add .cargo and you're pretty much good to go.

**Comment by alexcrichton** [comment]
I've opened https://github.com/rust-lang/rust/pull/27762 and if that lands then we can upgrade libc without breaking anything.

**Comment by tailhook** [comment]
I can confirm that libc with rust submodule works nice for me (even with musl build). So looking forward for release soon.

**Comment by tailhook** [comment]
Thanks!
