### ISSUE TITLE
We could deprecate c_uchar and c_schar

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/libc#1505]
We guarantee that `c_uchar` and `c_schar` are always equal to `u8` and `i8` and we don't aim to support any platforms where this isn't the case, ever. So we could deprecate these and just recommend users to use `u8` and `i8` instead.

**Comment by maxbla** [comment]
As a small counterpoint, from a user's perspective, using `c_uchar` and `c_schar` can indicate that FFI is going on.

**Comment by kellda** [comment]
This would be consistent with the deprecation of `{u,}int{8,16,32,64}_t` in #1304

**Comment by tgross35** [comment]
These are defined in `core::ffi` now. Since they are defined there, I don't think there is any point in removing anything here.
