### ISSUE TITLE
Outstanding PowerPC64 testcase failures

### ISSUE THREAD

**Issue by antonblanchard** [rust-lang/libc#151]
With powerpc64 fully bootstrapped, I was able to go back and build the libc tests. It shows a number of things we need to move into the arch specific files. Note: I also had to make a couple of changes to struct ipc_perm to get the tests to build (some fields are different sizes), so it needs to be moved too.

bad MCL_CURRENT value at byte 0: rust: 1 (0x1) != c 0 (0x0)
bad MCL_CURRENT value at byte 1: rust: 0 (0x0) != c 32 (0x20)
bad MCL_FUTURE value at byte 0: rust: 2 (0x2) != c 0 (0x0)
bad MCL_FUTURE value at byte 1: rust: 0 (0x0) != c 64 (0x40)
bad SIGSTKSZ value at byte 1: rust: 32 (0x20) != c 64 (0x40)
bad CBAUD value at byte 0: rust: 15 (0xf) != c 255 (0xff)
bad CBAUD value at byte 1: rust: 16 (0x10) != c 0 (0x0)
bad TAB1 value at byte 1: rust: 8 (0x8) != c 4 (0x4)
bad TAB2 value at byte 1: rust: 16 (0x10) != c 8 (0x8)
bad TAB3 value at byte 1: rust: 24 (0x18) != c 12 (0xc)
bad CR1 value at byte 1: rust: 2 (0x2) != c 16 (0x10)
bad CR2 value at byte 1: rust: 4 (0x4) != c 32 (0x20)
bad CR3 value at byte 1: rust: 6 (0x6) != c 48 (0x30)
bad FF1 value at byte 1: rust: 128 (0x80) != c 64 (0x40)
bad BS1 value at byte 1: rust: 32 (0x20) != c 128 (0x80)
bad VT1 value at byte 1: rust: 64 (0x40) != c 0 (0x0)
bad VT1 value at byte 2: rust: 0 (0x0) != c 1 (0x1)
bad VWERASE value at byte 0: rust: 14 (0xe) != c 10 (0xa)
bad VREPRINT value at byte 0: rust: 12 (0xc) != c 11 (0xb)
bad VSUSP value at byte 0: rust: 10 (0xa) != c 12 (0xc)
bad VSTART value at byte 0: rust: 8 (0x8) != c 13 (0xd)
bad VSTOP value at byte 0: rust: 9 (0x9) != c 14 (0xe)
bad VDISCARD value at byte 0: rust: 13 (0xd) != c 16 (0x10)
bad VTIME value at byte 0: rust: 5 (0x5) != c 7 (0x7)
bad IXON value at byte 1: rust: 4 (0x4) != c 2 (0x2)
bad IXOFF value at byte 1: rust: 16 (0x10) != c 4 (0x4)
bad ONLCR value at byte 0: rust: 4 (0x4) != c 2 (0x2)
bad CSIZE value at byte 0: rust: 48 (0x30) != c 0 (0x0)
bad CSIZE value at byte 1: rust: 0 (0x0) != c 3 (0x3)
bad CS6 value at byte 0: rust: 16 (0x10) != c 0 (0x0)
bad CS6 value at byte 1: rust: 0 (0x0) != c 1 (0x1)
bad CS7 value at byte 0: rust: 32 (0x20) != c 0 (0x0)
bad CS7 value at byte 1: rust: 0 (0x0) != c 2 (0x2)
bad CS8 value at byte 0: rust: 48 (0x30) != c 0 (0x0)
bad CS8 value at byte 1: rust: 0 (0x0) != c 3 (0x3)
bad CSTOPB value at byte 0: rust: 64 (0x40) != c 0 (0x0)
bad CSTOPB value at byte 1: rust: 0 (0x0) != c 4 (0x4)
bad CREAD value at byte 0: rust: 128 (0x80) != c 0 (0x0)
bad CREAD value at byte 1: rust: 0 (0x0) != c 8 (0x8)
bad PARENB value at byte 1: rust: 1 (0x1) != c 16 (0x10)
bad PARODD value at byte 1: rust: 2 (0x2) != c 32 (0x20)
bad HUPCL value at byte 1: rust: 4 (0x4) != c 64 (0x40)
bad CLOCAL value at byte 1: rust: 8 (0x8) != c 128 (0x80)
bad ECHOKE value at byte 0: rust: 0 (0x0) != c 1 (0x1)
bad ECHOKE value at byte 1: rust: 8 (0x8) != c 0 (0x0)
bad ECHOE value at byte 0: rust: 16 (0x10) != c 2 (0x2)
bad ECHOK value at byte 0: rust: 32 (0x20) != c 4 (0x4)
bad ECHONL value at byte 0: rust: 64 (0x40) != c 16 (0x10)
bad ECHOPRT value at byte 0: rust: 0 (0x0) != c 32 (0x20)
bad ECHOPRT value at byte 1: rust: 4 (0x4) != c 0 (0x0)
bad ECHOCTL value at byte 0: rust: 0 (0x0) != c 64 (0x40)
bad ECHOCTL value at byte 1: rust: 2 (0x2) != c 0 (0x0)
bad ISIG value at byte 0: rust: 1 (0x1) != c 128 (0x80)
bad ICANON value at byte 0: rust: 2 (0x2) != c 0 (0x0)
bad ICANON value at byte 1: rust: 0 (0x0) != c 1 (0x1)
bad PENDIN value at byte 1: rust: 64 (0x40) != c 0 (0x0)
bad PENDIN value at byte 3: rust: 0 (0x0) != c 32 (0x20)
bad NOFLSH value at byte 0: rust: 128 (0x80) != c 0 (0x0)
bad NOFLSH value at byte 3: rust: 0 (0x0) != c 128 (0x80)
bad VEOL value at byte 0: rust: 11 (0xb) != c 6 (0x6)
bad VEOL2 value at byte 0: rust: 16 (0x10) != c 8 (0x8)
bad VMIN value at byte 0: rust: 6 (0x6) != c 5 (0x5)
bad IEXTEN value at byte 1: rust: 128 (0x80) != c 4 (0x4)
bad TOSTOP value at byte 1: rust: 1 (0x1) != c 0 (0x0)
bad TOSTOP value at byte 2: rust: 0 (0x0) != c 64 (0x40)
bad FLUSHO value at byte 1: rust: 16 (0x10) != c 0 (0x0)
bad FLUSHO value at byte 2: rust: 0 (0x0) != c 128 (0x80)
bad EXTPROC value at byte 2: rust: 1 (0x1) != c 0 (0x0)
bad EXTPROC value at byte 3: rust: 0 (0x0) != c 16 (0x10)
bad TCGETS value at byte 0: rust: 1 (0x1) != c 19 (0x13)
bad TCGETS value at byte 1: rust: 84 (0x54) != c 116 (0x74)
bad TCGETS value at byte 2: rust: 0 (0x0) != c 60 (0x3c)
bad TCGETS value at byte 3: rust: 0 (0x0) != c 64 (0x40)
bad TCSETS value at byte 0: rust: 2 (0x2) != c 20 (0x14)
bad TCSETS value at byte 1: rust: 84 (0x54) != c 116 (0x74)
bad TCSETS value at byte 2: rust: 0 (0x0) != c 60 (0x3c)
bad TCSETS value at byte 3: rust: 0 (0x0) != c 128 (0x80)
bad TCSETSW value at byte 0: rust: 3 (0x3) != c 21 (0x15)
bad TCSETSW value at byte 1: rust: 84 (0x54) != c 116 (0x74)
bad TCSETSW value at byte 2: rust: 0 (0x0) != c 60 (0x3c)
bad TCSETSW value at byte 3: rust: 0 (0x0) != c 128 (0x80)
bad TCSETSF value at byte 0: rust: 4 (0x4) != c 22 (0x16)
bad TCSETSF value at byte 1: rust: 84 (0x54) != c 116 (0x74)
bad TCSETSF value at byte 2: rust: 0 (0x0) != c 60 (0x3c)
bad TCSETSF value at byte 3: rust: 0 (0x0) != c 128 (0x80)
bad TCGETA value at byte 0: rust: 5 (0x5) != c 23 (0x17)
bad TCGETA value at byte 1: rust: 84 (0x54) != c 116 (0x74)
bad TCGETA value at byte 2: rust: 0 (0x0) != c 20 (0x14)
bad TCGETA value at byte 3: rust: 0 (0x0) != c 64 (0x40)
bad TCSETA value at byte 0: rust: 6 (0x6) != c 24 (0x18)
bad TCSETA value at byte 1: rust: 84 (0x54) != c 116 (0x74)
bad TCSETA value at byte 2: rust: 0 (0x0) != c 20 (0x14)
bad TCSETA value at byte 3: rust: 0 (0x0) != c 128 (0x80)
bad TCSETAW value at byte 0: rust: 7 (0x7) != c 25 (0x19)
bad TCSETAW value at byte 1: rust: 84 (0x54) != c 116 (0x74)
bad TCSETAW value at byte 2: rust: 0 (0x0) != c 20 (0x14)
bad TCSETAW value at byte 3: rust: 0 (0x0) != c 128 (0x80)
bad TCSETAF value at byte 0: rust: 8 (0x8) != c 28 (0x1c)
bad TCSETAF value at byte 1: rust: 84 (0x54) != c 116 (0x74)
bad TCSETAF value at byte 2: rust: 0 (0x0) != c 20 (0x14)
bad TCSETAF value at byte 3: rust: 0 (0x0) != c 128 (0x80)
bad TCSBRK value at byte 0: rust: 9 (0x9) != c 29 (0x1d)
bad TCSBRK value at byte 1: rust: 84 (0x54) != c 116 (0x74)
bad TCSBRK value at byte 3: rust: 0 (0x0) != c 32 (0x20)
bad TCXONC value at byte 0: rust: 10 (0xa) != c 30 (0x1e)
bad TCXONC value at byte 1: rust: 84 (0x54) != c 116 (0x74)
bad TCXONC value at byte 3: rust: 0 (0x0) != c 32 (0x20)
bad TCFLSH value at byte 0: rust: 11 (0xb) != c 31 (0x1f)
bad TCFLSH value at byte 1: rust: 84 (0x54) != c 116 (0x74)
bad TCFLSH value at byte 3: rust: 0 (0x0) != c 32 (0x20)
bad TIOCINQ value at byte 0: rust: 27 (0x1b) != c 127 (0x7f)
bad TIOCINQ value at byte 1: rust: 84 (0x54) != c 102 (0x66)
bad TIOCINQ value at byte 2: rust: 0 (0x0) != c 4 (0x4)
bad TIOCINQ value at byte 3: rust: 0 (0x0) != c 64 (0x40)
bad TIOCGPGRP value at byte 0: rust: 15 (0xf) != c 119 (0x77)
bad TIOCGPGRP value at byte 1: rust: 84 (0x54) != c 116 (0x74)
bad TIOCGPGRP value at byte 2: rust: 0 (0x0) != c 4 (0x4)
bad TIOCGPGRP value at byte 3: rust: 0 (0x0) != c 64 (0x40)
bad TIOCSPGRP value at byte 0: rust: 16 (0x10) != c 118 (0x76)
bad TIOCSPGRP value at byte 1: rust: 84 (0x54) != c 116 (0x74)
bad TIOCSPGRP value at byte 2: rust: 0 (0x0) != c 4 (0x4)
bad TIOCSPGRP value at byte 3: rust: 0 (0x0) != c 128 (0x80)
bad TIOCOUTQ value at byte 0: rust: 17 (0x11) != c 115 (0x73)
bad TIOCOUTQ value at byte 1: rust: 84 (0x54) != c 116 (0x74)
bad TIOCOUTQ value at byte 2: rust: 0 (0x0) != c 4 (0x4)
bad TIOCOUTQ value at byte 3: rust: 0 (0x0) != c 64 (0x40)
bad TIOCGWINSZ value at byte 0: rust: 19 (0x13) != c 104 (0x68)
bad TIOCGWINSZ value at byte 1: rust: 84 (0x54) != c 116 (0x74)
bad TIOCGWINSZ value at byte 2: rust: 0 (0x0) != c 8 (0x8)
bad TIOCGWINSZ value at byte 3: rust: 0 (0x0) != c 64 (0x40)
bad TIOCSWINSZ value at byte 0: rust: 20 (0x14) != c 103 (0x67)
bad TIOCSWINSZ value at byte 1: rust: 84 (0x54) != c 116 (0x74)
bad TIOCSWINSZ value at byte 2: rust: 0 (0x0) != c 8 (0x8)
bad TIOCSWINSZ value at byte 3: rust: 0 (0x0) != c 128 (0x80)
bad FIONREAD value at byte 0: rust: 27 (0x1b) != c 127 (0x7f)
bad FIONREAD value at byte 1: rust: 84 (0x54) != c 102 (0x66)
bad FIONREAD value at byte 2: rust: 0 (0x0) != c 4 (0x4)
bad FIONREAD value at byte 3: rust: 0 (0x0) != c 64 (0x40)
bad ipc_perm size: rust: 56 (0x38) != c 48 (0x30)
bad field offset __seq of ipc_perm: rust: 28 (0x1c) != c 24 (0x18)
bad field type __seq of ipc_perm: rust: 0x1c != c 0x18
bad shmid_ds size: rust: 120 (0x78) != c 112 (0x70)
bad field size shm_perm of shmid_ds: rust: 56 (0x38) != c 48 (0x30)
bad field offset shm_segsz of shmid_ds: rust: 56 (0x38) != c 72 (0x48)
bad field type shm_segsz of shmid_ds: rust: 0x38 != c 0x48
bad field offset shm_atime of shmid_ds: rust: 64 (0x40) != c 48 (0x30)
bad field type shm_atime of shmid_ds: rust: 0x40 != c 0x30
bad field offset shm_dtime of shmid_ds: rust: 72 (0x48) != c 56 (0x38)
bad field type shm_dtime of shmid_ds: rust: 0x48 != c 0x38
bad field offset shm_ctime of shmid_ds: rust: 80 (0x50) != c 64 (0x40)
bad field type shm_ctime of shmid_ds: rust: 0x50 != c 0x40
bad field offset shm_cpid of shmid_ds: rust: 88 (0x58) != c 80 (0x50)
bad field type shm_cpid of shmid_ds: rust: 0x58 != c 0x50
bad field offset shm_lpid of shmid_ds: rust: 92 (0x5c) != c 84 (0x54)
bad field type shm_lpid of shmid_ds: rust: 0x5c != c 0x54
bad field offset shm_nattch of shmid_ds: rust: 96 (0x60) != c 88 (0x58)
bad field type shm_nattch of shmid_ds: rust: 0x60 != c 0x58

**Comment by alexcrichton** [comment]
Nice work! If you want to set up a CI builder for powerpc64 you're more than welcome to, it should be relatively simple to the other triples like `aarch64-unknown-linux-gnu`.

You'll probably just need to give me a build of the standard library for powerpc64 linux as well as the nightly date it corresponds to, but other than that it should be easy to add! (and prevent regressions)

**Comment by antonblanchard** [comment]
Thanks Alex, it would be great to get powerpc64 into the CI builder. I'll work on it when we get the above issues fixed.

**Comment by darnuria** [comment]
[triage-attempt] Hello @antonblanchard, can you share your work about making a CI builder for PowerPC64 here? No problem if you didn't find a way or moved to an other project.

If you don't mind I would try to make it working like the way we test OpenBSD and consort.

Thank you very much. :)

**Comment by alexcrichton** [comment]
We're now currently [testing powerpc64](https://github.com/rust-lang/libc/blob/a3baaf6a9562ac9a37d03807cdbc15cba5fc34fb/.travis.yml#L79-L81), so I believe these have all been fixed.
