### ISSUE TITLE
Missing tag / crates.io update for version 0.2.64

### ISSUE THREAD

**Issue by loganwendholt** [rust-lang/libc#1515]
As of right now, the latest tag version is `0.2.63`, but the Cargo.toml version was bumped to `0.2.64` with commit 1dd09fb. In addition, crates.io has a `0.2.63`, but it has been yanked.

Could we get a `0.2.64` tag in place and update crates.io?

**Comment by loganwendholt** [comment]
Are there any specific issues / PRs related to the bugs that are blocking?

**Comment by Osspial** [comment]
The one problem I can find with `0.2.63` was an issue with musl, and [the code causing that breakage has been removed](https://github.com/rust-lang/libc/pull/1484). I can't find anything else that would be blocking, but I'm not all that familiar with this crate so I don't know if there's something else.

**Comment by Osspial** [comment]
Looking through the diff from `0.2.63` to now, the other issue that's mentioned is https://github.com/rust-lang/rust/pull/63649, but that has also been resolved.

**Comment by tlively** [comment]
https://github.com/rust-lang/rust/pull/63649 was rolled back in https://github.com/rust-lang/rust/pull/65151, but that should not block a new libc release. The Emscripten fixes in #1478 are independent of https://github.com/rust-lang/rust/pull/63649 and should be rolled into rust-lang/rust as soon as possible regardless of what happens with other PRs.

**Comment by newpavlov** [comment]
@gnzlbg 
Any news regarding ETA for `v0.2.64` release?

**Comment by gnzlbg** [comment]
As soon as bors reports all green, which is hopefully today. Last week some smaller components for the standard library were shipped, and those were missing some binary components that were required for some targets to work properly, but the fix landed on nightly today.

**Comment by gnzlbg** [comment]
0.2.64 has been released, please, do test and report any issues, I'll update rust-lang/rust to use this version after it has received some testing
