### ISSUE TITLE
Give tips on how to get all the platforms' constants

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang/libc#152]
I'm trying to add a constant (`IF_NAMESIZE`) and I can find out what it is on a couple of platforms, but certainly not all of them. Is there a recommended approach?

**Comment by kamalmarhubi** [comment]
It's also unclear what type to use for a buffer size constant... `size_t`? `c_uint`?

**Comment by alexcrichton** [comment]
Yeah unfortunately I don't really know if there's an easy way beyond "submit a PR and see what travis says".

The type of the constant basically just depends on what context it's used in, e.g. if it's an argument, an array length, etc.

**Comment by kamalmarhubi** [comment]
Quick clarification for types of constants: do we always prefer libc types over Rust types for constants in libc?

**Comment by alexcrichton** [comment]
Constants are a little tricky because they don't actually have a type in C, they're just `#defines`. The best suggestion I have for their type is to figure out what context they're used in and use that type (which is mostly a libc type rather than a Rust type)

**Comment by mrhota** [comment]
Initially, I had some trouble tracking down relevant headers for locale stuff. Except for apple and windows, I eventually found repos where I could look up the constants I needed. Maybe we can/should stick links to the repos in a wiki page.

**Comment by SShrike** [comment]
I used the following to get the control codes for ioctl calls (tested on Linux and FreeBSD):

```c
#include <sys/ioctl.h>
#include <stdio.h>
#include <unistd.h>

int main (int argc, char **argv) {
    // Replace <CONSTANT> with a ioctl control constant.
    printf ("Code: 0x%04lx\n", <CONSTANT>);
    return 0;
}
```

**Comment by tmiasko** [comment]
To find constants, defines, typedefs, functions available on different
platforms, I usually use some combination of following (in case someone else
would find them useful):

Various source code cross-reference sites:
- http://src.illumos.org/source/ - FreeBSD, Linux, illumos
- http://bxr.su/xref/ DragonFly BSD, FreeBSD, NetBSD, OpenBSD
- http://fxr.watson.org/ - FreeBSD, Linux, OpenBSD, DragonFly BSD, and others

Source code repositories:
- https://github.com/torvalds/linux/ - Linus Torvalds Linux repository
- https://github.com/bitrig/bitrig - Bitrig repository
- https://gitweb.dragonflybsd.org/dragonfly.git - DragonFly BSD repository

For OS X opensource.apple.com/source is quite useful, in particular: 
- https://opensource.apple.com/source/xnu/ (bsd/sys directory, ...)
- https://opensource.apple.com/source/libpthread/ (pthread/pthread.h, sys/_pthread/*.h)

**Comment by gnzlbg** [comment]
Is this issue resolved? If so, we can close it. 

@alexcrichton can `ctest` list missing constant / structs / functions ? That is, items implemented on the C side of things, that are not implemented in Rust ?

**Comment by alexcrichton** [comment]
Sure I'm fine closing it!

@gnzlbg not currently, no, but we could always add it!
