### ISSUE TITLE
error: cannot find derive macro `Copy` in this scope

### ISSUE THREAD

**Issue by BaoshanPang** [rust-lang/libc#1530]
I am building rust with the latest libc, it was working very well, but today I get this error:

error: cannot find derive macro `Copy` in this scope
 --> /folk/prj-rust-dev/bpang/V7LIBC-997/dev/.cargo/git/checkouts/libc-d1297d136f47e864/3a9e5d0/src/unix/linux_like/linux/gnu/b64/x8\
6_64/align.rs:1:10
  |
1 | #[derive(Copy, Clone, Debug, PartialEq)]
  |          ^^^^

**Comment by BaoshanPang** [comment]
The issue can be reproduced with follow steps in builing rust:
1. get rust
$ git clone https://github.com/rust-lang/rust.git
2.  add libc = { git = 'https://github.com/rust-lang/libc.git' } to Cargo.toml under section [patch.crates-io]:
 [patch.crates-io]
libc = { git = 'https://github.com/rust-lang/libc.git' }
3. update Cargo.lock
$ cargo update -p libc
4. build
$ ./x.py build -i --stage 0 src/libstd

Then the errors reported above show.

**Comment by gnzlbg** [comment]
cc @petrochenkov maybe ?

**Comment by gnzlbg** [comment]
Otherwise report the bug in rust-lang/rust, maybe something changed upstream.

**Comment by BaoshanPang** [comment]
> Otherwise report the bug in rust-lang/rust, maybe something changed upstream.

The align.rs is newly added in that directory. The issue would disappeare if I roll back to the point without this change.

**Comment by gnzlbg** [comment]
I think the issue is that during bootstrapping the derive macros are not available, https://github.com/rust-lang/libc/pull/1531 this _might_ fix that, but maybe you could try that branch and check that it works for you?

**Comment by BaoshanPang** [comment]
Thanks. The issue has been fixed by #1513.
