### ISSUE TITLE
Export mcontext fields on x86_64-unknown-linux-musl

### ISSUE THREAD

**Issue by nmattia** [rust-lang/libc#1553]
[lucet](https://github.com/fastly/lucet) uses some of the fields of `mcontext` that were added recently for `x86_64-unknown-linux-gnu`. It'd be great to port those to `x86_64-unknown-linux-musl`. In particular:

https://github.com/rust-lang/libc/blob/7b31ef34ede6860ce2a4cfeeef01b02f8120a607/src/unix/linux_like/linux/gnu/b64/x86_64/mod.rs#L221-L225

and 

https://github.com/rust-lang/libc/blob/7b31ef34ede6860ce2a4cfeeef01b02f8120a607/src/unix/linux_like/linux/gnu/b64/x86_64/mod.rs#L871

which were ported in https://github.com/rust-lang/libc/commit/ae06c2b2ae6938c9162b9deadae442194a816ad2 and https://github.com/rust-lang/libc/commit/ac7f0fac2f34d4eed1f05e9d20f236149711ff87. Lucet only need `mcontext.gregs` and `REG_RIP` to be defined (see [here](https://github.com/fastly/lucet/blob/6af51b4235b7c5e09ca30d9bea7b68f4f70483cb/lucet-runtime/lucet-runtime-internals/src/sysdeps/linux.rs#L16)).

These are defined in musl with `GNU_SOURCE`:
* https://github.com/ifduyue/musl/blob/b4b1e10364c8737a632be61582e05a8d3acf5690/arch/x86_64/bits/signal.h#L42
* https://github.com/ifduyue/musl/blob/b4b1e10364c8737a632be61582e05a8d3acf5690/arch/x86_64/bits/signal.h#L81

**Comment by gnzlbg** [comment]
PRs welcome :)

**Comment by nmattia** [comment]
@gnzlbg will do, just wanted to double-check first that the `GNU_SOURCE` requirement wasn't a dealbreaker.

**Comment by gnzlbg** [comment]
No it isn't, for linux targets (independently of whether they use gnu or musl), we always define it here: https://github.com/rust-lang/libc/blob/master/libc-test/build.rs#L2072
