### ISSUE TITLE
A feature for types only

### ISSUE THREAD

**Issue by elichai** [rust-lang/libc#1560]
Hi,

Would people be in favor of a feature for only types? i.e. no function definitions, just getting all the typedefs.

This can be useful for me here https://github.com/rust-lang/rfcs/issues/2610#issuecomment-543609263

Although I'm still debating if I should maintain my own list of typedefs for the kernel, flags etc.

How do people feel about this?

**Comment by gnzlbg** [comment]
I started working on this, but other things came in the way: https://github.com/rust-lang/libc/pull/1286

**Comment by elichai** [comment]
I was actually thinking to also includes the flags typedefs 
i.e. F_SETFL

**Comment by gnzlbg** [comment]
What problem are you trying to solve ? 

Adding the libc crate as a dependency from crates.io does not link any platform libc library into your binary.

**Comment by elichai** [comment]
I'm mostly worried i'll accidentally use an `extern "C"` static typess instead of a typedef.

**Comment by gnzlbg** [comment]
Why can't you write a wrapper crate over libc that only re-exports what you want ?

**Comment by elichai** [comment]
that might be an option. but even then i'll need to always check the types i'm re-exporting are still just typedefs(or structs?) but not a link.

**Comment by gnzlbg** [comment]
Sure, you'd have to do that.

I personally do not think it is worth it to introduce complexity for this in the `libc` crate when the motivation appears to be to implement a Rust target that does not use this crate, and once that is achieved, all this complexity wouldn't be required.

The libc crate does, however, have very strong backward compatibility guarantees, so we couldn't just remove this complexity later.

**Comment by elichai** [comment]
That's fair. 
I can try to help with https://github.com/rust-lang/libc/pull/1286 if you can point me to what missing. because I know of a bunch of crates that would like that use case.

**Comment by gnzlbg** [comment]
In the mean time you can just use the `cty` crate from crates.io. 

The issues related to that PR are more organizational than implementation-related.

(I'm closing this, but please feel free to re-open if you think there is something else we can do here)
