### ISSUE TITLE
nfnetlink constants

### ISSUE THREAD

**Issue by vorner** [rust-lang/libc#1562]
Hello

I'd like to ask, would it be OK to add netfilter netlink constants. They are in the linux headers (`/usr/include/linux/netfilter/nfnetlink*.h`). I'm trying to extend neli with nfnetlink support (currently NFLOG, https://github.com/jbaublitz/neli/pull/48).

I'll send a pull request, I just wanted to ask first if including these would be OK.

**Comment by gnzlbg** [comment]
Sure.

**Comment by JohnTitor** [comment]
I assume this is done by #1628 and am going to close but feel free to re-open if I'm missing something.

**Comment by vorner** [comment]
I think there are some few more constants in the header, but I guess a lazy approach (once they are actually needed) is good and there's not much use for keeping this issue open :-). Sorry for letting it rot in here.
