### ISSUE TITLE
error occurs by  /libcore/result.rs:997

### ISSUE THREAD

**Issue by yuer1727** [rust-lang/libc#1569]
**ERROR occurs by :** 

$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/icmp`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:312
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: rand::os::imp::OsRng::new
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/macros.rs:17
   9: libicmp::socket::RawSocket::set_nonblocking::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/result.rs:798
  10: core::cmp::impls::<impl core::cmp::PartialOrd for u64>::le
             at src/icmp.rs:29
  11: <alloc::collections::CollectionAllocErr as core::convert::From<core::alloc::LayoutErr>>::from
             at src/ping.rs:84
  12: icmp::main
             at src/main.rs:13
  13: std::rt::lang_start::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/rt.rs:64
  14: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  15: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:87
  16: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  17: std::rt::lang_start
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/rt.rs:64
  18: icmp::main

when i 'cargo run'  , error occurs: 'PermissionDenied' . I have no idea about it ,My machine is macbook pro. Thanks for reading the question.
here is a project base on libc : https://github.com/APTy/icmp

**Comment by semarie** [comment]
I bind guess: the `cargo run` run code that tries to create a raw socket to be able to make ping packet, but as you run the program with a "normal" account, the OS denied to you the permission to create such socket (and you get a PermissionDenied). Creating SOCK_RAW is a privilegied operation and usually require elevated privilegies (like behind superuser or having special capability under Linux).

**Comment by yuer1727** [comment]
> I blind guess: the `cargo run` run code that tries to create a raw socket to be able to make ping packet, but as you run the program with a "normal" account, the OS denied to you the permission to create such socket (and you get a PermissionDenied). Creating SOCK_RAW is a privilegied operation and usually require elevated privilegies (like behind superuser or having special capability under Linux).

nice!  Your guess is right!

**Comment by gnzlbg** [comment]
Feel free to re-open if that did not resolve your issue.
