### ISSUE TITLE
[Question] Is it normal for musl targets not to have utmpx?

### ISSUE THREAD

**Issue by GrayJack** [rust-lang/libc#1570]
I'm asking that cause I get problems compiling my project on musl targets, complaining that the struct doesnt exist on the crate. Looking at the musl code, I saw a utmpx on the legacy folder, with empty implementations, but also saw in the same codebase other utmpx file with everything defined

**Comment by rivy** [comment]
+1
[uucore](https://github.com/uutils/uucore), needed for [coreutils](https://github.com/uutils/coreutils), won't compile for musl targets because `utmpx` is missing.

**Comment by rivy** [comment]
Hmm, some further google research reveals that `musl` only stubs utmp and wtmp for security reasons.

* ref: <https://wiki.musl-libc.org/faq.html#Q:-Why-is-the-utmp/wtmp-functionality-only-implemented-as-stubs?>
* ref: <https://github.com/linux-pam/linux-pam/pull/52>
* ref: <http://skarnet.org/software/utmps>

**Comment by gnzlbg** [comment]
@grayjack does that answer your question?

**Comment by GrayJack** [comment]
Yes, it does
