### ISSUE TITLE
Policy on polyfilling new syscalls for older versions?

### ISSUE THREAD

**Issue by MarkMcCaskey** [rust-lang/libc#1580]
HI!  A user of our software ran into an issue on mac osx 10.11 due to missing `clock_gettime` and `clock_getres` (these were added in mac osx 10.12).

My question is: is this crate the place for a work-around?  The work-around being implementing these system calls in terms of other system calls when compiling for 10.11 and earlier?

One more relevant bit of information is that 10.11 is no longer officially supported by Apple, in case that changes anything.

Apologies if this has been answered before, I couldn't find the information.

**Comment by gnzlbg** [comment]
`libc` only provides raw FFI bindings - nothing more, nothing less. You might want to check out the `mach` crate, but it only provides raw FFI bindings as well, so you might need a higher level abstraction over that (e.g. `chrono` or the `time` crate).
