### ISSUE TITLE
Freebsd 12.0 missing in_pktinfo

### ISSUE THREAD

**Issue by wbl** [rust-lang/libc#1583]
On Freebsd 12.0 using Cargo nightly 1.39.0 a program of mine fails to build with the complaint that `libc::in_pktinfo does not exist`. This program builds quite well on Darwin and Linux, making me suspect something else is up. It also appears that the per-OS documentation shares this difference.

**Comment by gnzlbg** [comment]
The `libc` does not expose `in_pktinfo` on FreeBSD 12 maybe ? If that's the case, and that is actually available on FreeBSD, it might just be that nobody has implemented this yet.

**Comment by gnzlbg** [comment]
cc @asomers

**Comment by asomers** [comment]
libc doesn't define that struct on FreeBSD because it doesn't actually exist on FreeBSD.  Why don't you check whether the `IP_RECVIF`, `IP_RECVDSTADDR`, and/or `IP_ORIGDSTADDR` socket options will work for you?

**Comment by wbl** [comment]
Thank you! Looking at the manpages again you are exactly right.
