### ISSUE TITLE
SysV IPC APIs missing on OpenBSD

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/libc#1585]
See this issue: https://github.com/gnzlbg/slice_deque/issues/77#issue-518380526

**Comment by landryb** [comment]
cf landryb/libc@8c688c22bc25757f945f2acefc2d5038cb72229f for a quick wip. @semarie ?

**Comment by semarie** [comment]
@landryb thanks for the wip. I will use it as base for the PR.

I will have few fixes (but I will take care of that):
- `sys/shm.h` header is need in `libc-test/build.rs` for proper testsuite run
- `shm_segsz` is `int` and not a `size_t` on OpenBSD (hey, not posix compliant. I hope others crates doesn't rely on that)
- `struct shmid_ds` is incomplete
- few constants mismatches
