### ISSUE TITLE
Using sprintf on windows

### ISSUE THREAD

**Issue by ccartas** [rust-lang/libc#1595]
Is there any way to use sprintf on windows target? I was looking at Platform Specific Documentation and I don't see the sprintf function exported for windows.

**Comment by gnzlbg** [comment]
cc @retep998

**Comment by retep998** [comment]
The CRT used in recent versions of VC++ does not expose a `sprintf` symbol. Instead in the headers `sprintf` is an inline wrapper around a more generic function. There is however an `oldnames.lib` that can be linked to which exposes all those legacy symbols such as `sprintf`.

**Comment by ccartas** [comment]
I ended up using a little C function and use it with FFI to use sprintf.
This issue can be closed.
