### ISSUE TITLE
vfork can cause memory corruption due to the lack of #[ffi_returns_twice]

### ISSUE THREAD

**Issue by Amanieu** [rust-lang/libc#1596]
Due to the lack of a stable `#[ffi_returns_twice]` attribute, `vfork` cannot be safely used since it can cause memory corruption of unrelated local variables in the parent process.

Miscompilation example: https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=e192ab81e8d408fa9984f766e2356697

Fixed (but nightly-only) version with `#[ffi_returns_twice]`: https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=0de019e56b69aa048f3e0f5319cc187e

**Comment by tgross35** [comment]
`vfork` has been deprecated https://github.com/rust-lang/libc/pull/1574 then removed for 1.0 https://github.com/rust-lang/libc/pull/3624, so this should be good to close.
