### ISSUE TITLE
libc 0.1.9 includes an incompatible change

### ISSUE THREAD

**Issue by danburkert** [rust-lang/libc#16]
libc 0.1.9 includes at least one incompatible change over 0.1.8 (a change to the function signature of `libc::funcs::bsd44::ioctl`).  According to [Rust's version](http://doc.rust-lang.org/semver/semver/index.html) of semver, the 0.1.9 release should have incremented the minor version number.

**Comment by alexcrichton** [comment]
Small tweaks like this fall within the "semver compatible" vision of Rust because a small local annotation can be used to fix any compile errors. Additionally the changes provided are required for correctness, so it's possible to lead to memory unsafety if these aren't fixed.

**Comment by danburkert** [comment]
> Small tweaks like this fall within the "semver compatible" vision of Rust because a small local annotation can be used to fix any compile errors.

I'm not sure what annotation you are referring to here, but if it's setting the dependency "^0.1.8", that does not work because Cargo assumes 0.1.9 is compatible with 0.1.8.  If you mean setting the dependency "=0.1.8", that does not work because Cargo [appears to be broken](https://github.com/rust-lang/cargo/issues/1800).

> Additionally the changes provided are required for correctness, so it's possible to lead to memory unsafety if these aren't fixed.

Absolutely, and thank you for making the fix.  My only concern is that the minor version was not bumped.

**Comment by alexcrichton** [comment]
I've yanked 0.1.9 and this can be discussed later.

**Comment by perlun** [comment]
@danburkert - if there are really "breaking changes", it's not even enough to bump the minor version. The major version should also be adjusted, according to the link you posted.

*However*, it is also stated [here](http://semver.org/) (SemVer spec) that:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

So 0.1.9 being incompatible with 0.1.8 is perfectly fine in that sense. Still, all breaking changes should of course be thought through nonetheless (to avoid messing up for people), and even more and more as the usage of the library increases. My $0.02. :smile:

**Comment by agrover** [comment]
Is this discussion ongoing somewhere?
