### ISSUE TITLE
SIG_DFL and SIG_IGN on windows

### ISSUE THREAD

**Issue by vorner** [rust-lang/libc#1600]
Hello

The `SIG_DFL` and `SIG_IGN` constants seem to be missing on windows targets (`*-pc-windows-*` tripples). It seems that according to the documentation they should exist

https://docs.microsoft.com/en-us/previous-versions/xdkz3x12(v=vs.140)

I'd try adding them, but I don't have any Windows at hand so I can't find the value. Some tests on CI suggest that `SIG_DFL` might be 0, though, but I can't really be sure.

Is it possible to add them?

Thank you

**Comment by retep998** [comment]
From `ucrt\signal.h`
```C
#define SIG_DFL ((_crt_signal_t)0)     // default signal action
#define SIG_IGN ((_crt_signal_t)1)     // ignore signal
#define SIG_GET ((_crt_signal_t)2)     // return current value
#define SIG_SGE ((_crt_signal_t)3)     // signal gets error
#define SIG_ACK ((_crt_signal_t)4)     // acknowledge
#define SIG_ERR ((_crt_signal_t)-1)    // signal error value
```
There is also one more definition but it seems like it shouldn't be used?
```C
#ifdef _CORECRT_BUILD
    // Internal use only!  Not valid as an argument to signal().
    #define SIG_DIE ((_crt_signal_t)5) // terminate process
#endif
```
`_crt_signal_t` is defined like so and used in `signal` like so
```C
typedef void (__CRTDECL* _crt_signal_t)(int);
_ACRTIMP _crt_signal_t __cdecl signal(_In_ int _Signal, _In_opt_ _crt_signal_t _Function);
```

**Comment by vorner** [comment]
Thank you, I'll send a pull request adding them, then.

> Anyway, just remember that you should only ever use CRT signals for compatibility with existing C code that also uses CRT signals. You should never use them otherwise.

Actually, I don't even have a Windows machine around. I've hit this when trying to keep some minimal compatibility with Windows in signal-hook, which is primarily a unix crate.
