### ISSUE TITLE
Question: Why aren't some constans/structs in ucontext.h for x86_64-android?

### ISSUE THREAD

**Issue by igrep** [rust-lang/libc#1604]
* the target triple: x86_64-linux-android, aarch64-linux-android, etc.
* link to the documentation of the API showing the type signatures, how to use
  it, etc.:
    - https://pubs.opengroup.org/onlinepubs/7908799/xsh/ucontext.h.html
    - https://android.googlesource.com/platform/bionic/+/refs/tags/ndk-r20/libc/include/sys/ucontext.h

I confirmed some symbols (e.g. `_libc_xmmreg`, `ucontext_t`, `REG_R10` etc.) are available also in Android (see the source in googlesource.com above).
So I think symbols in ucontext.h should be added under linux_like/android/.
Am I missing something?

**Comment by gnzlbg** [comment]
99% of the time the answer is "because nobody has sent a PR to implement them", so if you want these, PRs welcome.
