### ISSUE TITLE
Add posix threads support for macOS

### ISSUE THREAD

**Issue by iddm** [rust-lang/libc#1618]
Can we add a possibility to use POSIX threads for the macOS? It seems to be not straightforward to do myself - all the code is mixed across many files. Thanks!

P.S. Maybe it is even better if we share all the POSIX-code among several targets which support it. Right now, for example, the `pthread_setschedprio` function is defined in the `/linux-like/linux` but it shouldn't be Linux-only available.

**Comment by gnzlbg** [comment]
PRs welcome.
