### ISSUE TITLE
Adding accept4(2) to NetBSD

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/libc#1636]
According to https://www.netbsd.org/changes/changes-8.0.html, NetBSD (x86_64-unknown-netbsd) has had the `accept4(2)` system call since February 2017. When the system call was added (https://github.com/rust-lang/libc/pull/394, https://github.com/rust-lang/libc/pull/546) it seems NetBSD 8.0 wasn't released yet (?).

I have two questions:

* Its it old/stable enough to add? Or is this crate targeting NetBSD 7.0?
* Can anyone with a NetBSD installation add the system call?

I would add it myself but I don't have a NetBSD installation so I would have no idea if I did it correctly, as NetBSD isn't run on the CI either (it seems).

Related: https://github.com/tokio-rs/mio/issues/1213.

**Comment by krytarowski** [comment]
accept4(2) is not a system call, but a libc wrapper to paccept(2). Supporting <8.0 has little point here and it will go EOL in few months.
