### ISSUE TITLE
The `libc` crate doesn't currently have active maintainers

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/libc#1657]
This crate does not currently have any active maintainers. There's a long backlog of PRs as well as CI maintenance that needs to happen. As such at this time we're temporarily not merging any PRs.

If you or someone else would like to help maintain this crate, please leave comments here! This is a pretty critical crate, and more maintainers for it would be most welcome!

**Comment by darcyliu** [comment]
Hi @alexcrichton, thanks for letting us know!
I would like to help maintain this crate. Could you provide more information about how to be a maintainer for it? Is there any guidance doc for us to catch up ? Thanks!

**Comment by vickenty** [comment]
I'd love to help out.

**Comment by stevendanna** [comment]
I'm happy to try to help in some capacity.

**Comment by xales** [comment]
Also would be interested to get involved and help go through PR backlog!

**Comment by LMJW** [comment]
Hi @alexcrichton. I would love to help with maintaining this crate.

**Comment by drhaynes** [comment]
Also happy to help out.

@darcyliu the RFC looks like a good place to start getting up to speed on the design of the library: https://github.com/rust-lang/rfcs/blob/master/text/1291-promote-libc.md

Platform specific docs appear to be in: https://rust-lang.github.io/libc/#platform-specific-documentation

**Comment by reitermarkus** [comment]
I'd also be happy to help.

**Comment by Ersikan** [comment]
I have a somewhat strong knowledge of the C library and I'd be glad to help out. However I currently don't know how the libc crate works.

**Comment by DerekStrickland** [comment]
I am willing

**Comment by alexcrichton** [comment]
Thanks for the support everyone! I've added @JohnTitor as a maintainer of this crate in the meantime and I hope to be pretty hands-off myself with this. I know @JohnTitor could use help with reviewing PRs and helping to fix CI, though, so any help that can be offered would be greatly appreciated!

**Comment by srikwit** [comment]
Hi @alexcrichton , I would be willing to contribute to this crate too!

**Comment by Lee-Ashmore** [comment]
Hello @JohnTitor, I would love to help you out on maintenance of this crate. I've notice the docs for this one could use some love and wouldn't mind lending a hand

**Comment by pwang7** [comment]
put my two cents in, is it possible to automatically generate libc code using similar tool like BindGen?

**Comment by GuillaumeDIDIER** [comment]
> put my two cents in, is it possible to automatically generate libc code using similar tool like BindGen?

I believe this a long running debate and the object of a very old closed issue. #423
