### ISSUE TITLE
Does the key_add system call belong in libc?

### ISSUE THREAD

**Issue by jbaublitz** [rust-lang/libc#1663]
I'm currently wondering if it's within scope to add the `add_key` system call for Linux for adding keys to the kernel keyring. I'm happy to put together a PR but per [the documentation](http://man7.org/linux/man-pages/man2/add_key.2.html), this has no libc wrapper. This is purely a system call and I'm not sure what the line is for acceptance in the libc crate. Are system calls without a libc wrapper fair game? If so, I'll start working on it. Thanks!

**Comment by vickenty** [comment]
> This is purely a system call

Not quite. The man page you linked is actually for a wrapper that is provided by the `libkeyutils` library. (see `NOTES` section). So the `add_key` function is not available to all programs automatically, they actually have to explicitly link to the library to get it. This library is distributed and packaged separately by the distributions (both Debian and Redhat all have a separate package for it). 

So I think it is safe to treat this as just another C library - not in scope for this crate, but something that can be easily wrapped by a independent crate. In fact, it seems someone is already working on one: https://github.com/mathstuf/rust-keyutils

**Comment by jbaublitz** [comment]
Excellent thanks!

**Comment by landhb** [comment]
In case anybody stumbles upon this I've also created `linux-keyutils` which creates a rust interface around the keyutils facility. It's only dependencies are `libc` and the `bitflags` crates.

[Repository](https://github.com/landhb/linux-keyutils)
[Docs](https://docs.rs/linux-keyutils/0.1.0/linux_keyutils/)
[Crates.io](https://crates.io/crates/linux-keyutils)

Basic usage:

```rust
use linux_keyutils::{Key, KeyRing, KeyError, KeyRingIdentifier};
use linux_keyutils::{KeyPermissionsBuilder, Permission};

fn main() -> Result<(), KeyError> {
    // Obtain the default session keyring for the current process
    // See [KeyRingIdentifier] and `man 7 keyrings` for more information on default
    // keyrings for processes.
    let ring = KeyRing::from_special_id(KeyRingIdentifier::Session, false)?;

    // Insert a new key
    let key = ring.add_key("my-new-key", b"secret")?;

    // Utiltiies to create proper permissions
    let perms = KeyPermissionsBuilder::builder()
        .posessor(Permission::ALL)
        .user(Permission::ALL)
        .group(Permission::VIEW | Permission::READ)
        .build();

    // Perform manipulations on the key such as setting permissions
    key.set_perms(perms)?;

    // Or setting a timeout for how long the key should exist
    key.set_timeout(300)?;

    // Or invalidating (removing) the key
    key.invalidate()?;
    Ok(())
}
```
