### ISSUE TITLE
RLIMIT_AS missing from android?

### ISSUE THREAD

**Issue by rbtcollins** [rust-lang/libc#1670]
This applies to all android variants as far as I can tell.

RLIMIT_AS is missing from the rust libc bindings such  as https://rust-lang.github.io/libc/aarch64-linux-android/libc/index.html

I'm reasonably sure that is is however defined on Android (in particular there are media framework commits that only recently stopped using RLIMIT_AS!): 

https://android.googlesource.com/kernel/common/+/refs/heads/android-mainline/include/uapi/asm-generic/resource.h

There are from visual inspection some other limits also missing; the full list is
```
RLIMIT_AS
RLIMIT_RSS
RLIMIT_NPROC
RLIMIT_NOFILE
RLIMIT_MEMLOCK
```

Is this as simple as adding them to https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/android/mod.rs#L1103 ?

**Comment by igrep** [comment]
Yes, it should be.

**Comment by JohnTitor** [comment]
Sounds good, feel free to send a PR or I'm available if you want me to do :)
