### ISSUE TITLE
Add `sigset_t` for NetBSD

### ISSUE THREAD

**Issue by nvzqz** [rust-lang/libc#1671]
According to https://www.unix.com/man-page/netbsd/9/sendsig/, `sigset_t` is in NetBSD but `libc` currently only has it for OpenBSD. I believe it should also be in FreeBSD and DragonFly BSD.

**Comment by JohnTitor** [comment]
Hm, have you encountered any failures due to missing `sigset_t` on NetBSD? It seems to be already defined:

https://github.com/rust-lang/libc/blob/64b919f1d4cf601cf016350673564e4b364b13e5/src/unix/bsd/netbsdlike/netbsd/mod.rs#L67-L69

**Comment by nvzqz** [comment]
How odd, I could've sworn I couldn't find it when scouring `libc`. Thanks for pointing it out!

I'm not testing directly on NetBSD. It was through manual searching.
