### ISSUE TITLE
mount flags for MacOS (BSD)

### ISSUE THREAD

**Issue by pwang7** [rust-lang/libc#1688]
Hi All,

I'm using `libc::mount` under MacOS, and it seems `libc` only defines limited number of MacOS (BSD) `MNT_*` flags. Whereas, `libc` defines much more `MS_*` flags for Linux.

However, the mount(2) flags w.r.t. Linux and MacOS (BSD) are different, not only flag names differ, but also flag values.
Linux mount(2) flags:
```
#define MS_RDONLY	 1	/* Mount read-only */
#define MS_NOSUID	 2	/* Ignore suid and sgid bits */
#define MS_NODEV	 4	/* Disallow access to device special files */
...
```
MacOS (BSD) mount(2) flags:
```
#define	MNT_RDONLY	0x00000001	/* read only filesystem */
#define	MNT_SYNCHRONOUS	0x00000002	/* file system written synchronously */
#define	MNT_NOEXEC	0x00000004	/* can't exec from filesystem */
...
```

I'd like to add more MacOS (BSD) mount flags to libc, is [src/unix/bsd/mod.rs](https://github.com/rust-lang/libc/blob/master/src/unix/bsd/mod.rs#L326) the right place to start with?

Thanks!

**Comment by JohnTitor** [comment]
> I'd like to add more MacOS (BSD) mount flags to libc, is src/unix/bsd/mod.rs the right place to start with?

It seems FreeBSD defines [`MNT_RDONLY` as `0x0000000000000001ULL`](https://github.com/freebsd/freebsd/blob/f98fa6370ab08ec51399d253d19771cd0c3d28f8/sys/sys/mount.h#L295) so it should be placed in src/unix/bsd/apple/mod.rs, I think.

Anyway CI checks their types and values, feel free to send a PR!

**Comment by pwang7** [comment]
My PR got an error:
```
error: constant item is never used: `MNT_FORCE`
    --> src/unix/bsd/apple/mod.rs:3076:1
     |
3076 | pub const MNT_FORCE: ::c_int = 0x00080000; // force unmount or readonly change
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
```

Since I just added bunch of flags, do these flags have to be used?
