### ISSUE TITLE
BSD routing sockets

### ISSUE THREAD

**Issue by Demi-Marie** [rust-lang/libc#1713]
<dl><dt>Target triple</dt><dd>Many ― virtually every *nix other than Linux ― but I believe the API is essentially the same on all of them</dd><dt>Documentation</dt><dd>Man pages for the respective operating systems</dt></dl>

**Comment by tgross35** [comment]
Some of these have been added recently. This issue is a bit open-ended so I am going to close it, but please feel free to open a new issue or PR if there are specific interfaces still missing!
