### ISSUE TITLE
Documentation in `ci` is outdated

### ISSUE THREAD

**Issue by ForNeVeR** [rust-lang/libc#1733]
[The documentation in `ci`](https://github.com/rust-lang/libc/blob/12c28abe7bb2a30792d28e819ca4bb4257ed8f0c/ci/README.md) states that Travis and Appveyor are used, but actually it seems you've migrated to Azure & Cirrus. Looks like it's time to update it a bit!

**Comment by JohnTitor** [comment]
Thanks! I think it's quite outdated entirely, not just about Travis and AppVeyor. I'm not sure how many people read that docs and don't have time to document current structure now so I'll add a note to tell it's outdated for now.
