### ISSUE TITLE
[CI] CI for i686-linux-android is broken

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/libc#1765]
Currently, aarch64-unknown-linux-android and i686-linux-android targets are broken.
The logs:
- [aarch64-unknown-linux-android](https://gist.github.com/JohnTitor/f38a8cf2a3ae7fd8159a59460866b7ef): it's now resolved but some it seems API version is old somehow.
- [i686-linux-android](https://gist.github.com/JohnTitor/f0b471790736babd0c6bb0b29c048348)

We should investigate the cause and land a fix.

**Comment by rupansh** [comment]
Consider using a newer toolchain for android.
Current CI uses API 21's toolchain. These functions were added in later versions of android to the TC.
According to headers in `sysroot/usr/include` of the latest ndk

API 23 Functions:
`openpty`, `forkpty`, `login_tty`, `sethostname`, `sigtimedwait`, `fmemopen`, `open_memstream`, `open_wmemstream`, `clock_getcpuclockid`

API 24 Functions:
`lockf`,`preadv64`,`pwritev64`, `getifaddrs`, `freeifaddrs`, `getgrgid_r`, `getgrnam_r`

**Comment by JohnTitor** [comment]
> Current CI uses API 21's toolchain. 

Hm, it's weird. IIUC we use API 24 for arm/aarch64 and API 28 for i686/x86_64, am I missing something?

**Comment by rupansh** [comment]
> > Current CI uses API 21's toolchain.
> 
> Hm, it's weird. IIUC we use API 24 for arm/aarch64 and API 28 for i686/x86_64, am I missing something?

Did you recently change the CI? It was using android21 with azure pipelines 12 days ago.

**Comment by JohnTitor** [comment]
No. Here's our config for Android NDK:
https://github.com/rust-lang/libc/blob/2d044d98ad1694ecdaa947974212b8f0202f570d/ci/android-install-ndk.sh#L5-L34

> It was using android21 with azure pipelines 12 days ago.

You mean `r21d` is API 21?

**Comment by rupansh** [comment]
> No. Here's our config for Android NDK:
> 
> https://github.com/rust-lang/libc/blob/2d044d98ad1694ecdaa947974212b8f0202f570d/ci/android-install-ndk.sh#L5-L34
> 
> > It was using android21 with azure pipelines 12 days ago.
> 
> You mean `r21d` is API 21?

The old build is no longer opening on azure pipelines but I remember it was using  aarch64-linux-android21-clang
Perhaps I am remembering wrong. My bad!

**Comment by qwandor-google** [comment]
I also noticed that it was using `aarch64-linux-android21-clang`, while the others use `x86_64-linux-android28-clang` and `armv7a-linux-androideabi24-clang`. I couldn't see where these version numbers come from though, as the `android-install-ndk.sh` script does indeed seem to be installing a newer version~

**Comment by qwandor-google** [comment]
Where can I find instructions on how to run the CI tests locally, so I can try to debug this?

**Comment by JohnTitor** [comment]
You can run the scripts like CI on your local but I wouldn't recommend it.
I think we have two simple ways to debug CI:

1. Run _GHA_ on your local with https://github.com/nektos/act
1. Run GHA on your fork repo with a tweak to run Android jobs only (I'm doing it on #1927 with try builder)

**Comment by JohnTitor** [comment]
So, after some debugging, I think https://github.com/alexcrichton/cc-rs/pull/495 is the cause. If we set `cc = "=1.0.52"`, the test passes: https://github.com/rust-lang/libc/runs/1266137760
I'm going to pin `cc` crate for now, but it'd be great if we could introduce an actual fix for it (I'll file an issue on that repository later).
