### ISSUE TITLE
Problem with function signatures of getpriority and setpriority for gnu linux

### ISSUE THREAD

**Issue by bvaisvil** [rust-lang/libc#1767]
This issue is for version `0.2.70` compiling for `x86_64-unknown-linux-gnu` on `5.1.18-200.fc29.x86_64`

The function signatures of `getpriority` and `setpriority` are defined as [such](https://github.com/rust-lang/libc/blob/f90bd7711ba7eddd9b61fd0558aafa7f03794027/src/unix/linux_like/linux/gnu/mod.rs#L1301):
```rust
    pub fn getpriority(which: ::__priority_which_t, who: ::id_t) -> ::c_int;
    pub fn setpriority(
        which: ::__priority_which_t,
        who: ::id_t,
        prio: ::c_int,
    ) -> ::c_int;
```

The issue is the first argument, `which` is defined as a `__priority_which_t` (a [c_uint](https://github.com/rust-lang/libc/blob/f90bd7711ba7eddd9b61fd0558aafa7f03794027/src/unix/linux_like/linux/gnu/mod.rs#L2)) however, the `which` constants (`PRIO_PROCESS`, etc) are [defined](https://github.com/rust-lang/libc/blob/29b27da956002079bba0f9c6eb2d3ed29b8e49ab/src/unix/mod.rs#L272) as c_int. 

So passing `PRIO_PROCESS` to either function results in a compiler error:

```
error[E0308]: mismatched types
 --> src/main.rs:6:34
  |
6 |         let result = getpriority(PRIO_PROCESS, pid);
  |                                  ^^^^^^^^^^^^ expected `u32`, found `i32`
  |
help: you can convert an `i32` to `u32` and panic if the converted value wouldn't fit
  |
6 |         let result = getpriority(PRIO_PROCESS.try_into().unwrap(), pid);
  |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Here's my code to reproduce the issue:

```rust
use libc::{getpriority, PRIO_PROCESS, id_t};

fn main() {
    let pid: id_t = 0;
    unsafe {
        let result = getpriority(PRIO_PROCESS, pid);
        println!("{}", result);
    }
}
````

Please let me know if there is anything else I can provide to help.

**Comment by JohnTitor** [comment]
We should define `PRIO_PROCESS` and other two constants as `__priority_which_t` since it's a c_enum in glibc like `__rlimit_resource_t` and related items.
