### ISSUE TITLE
_ALIGNBYTES wrong on freebsd x86

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/libc#1775]
https://github.com/rust-lang/libc/blob/master/src/unix/bsd/freebsdlike/freebsd/x86.rs#L34-L43

Should probably be `4 - 1`.

**Comment by asomers** [comment]
Yep, this looks like a mistake accidentally introduced by a17a91cdbf13a43af4e24c0f5498ff6a5e6271c5 .  I agree with your suggested change.
