### ISSUE TITLE
WIFSIGNALED wrong on freebsd

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/libc#1782]
Upstream definition is

```c
#define	WIFSIGNALED(x)	(_WSTATUS(x) != _WSTOPPED && _WSTATUS(x) != 0 && (x) != 0x13)
```

downstream is

```rust
    pub fn WIFSIGNALED(status: ::c_int) -> bool {
        (status & 0o177) != 0o177 && (status & 0o177) != 0
    }

```

The `(x) != 0x13)` part is missing causing `WIFSIGNALED` to return `true` incorrectly.

**Comment by JohnTitor** [comment]
It's only true on FreeBSD: https://github.com/freebsd/freebsd/commit/dfbec9669f26f5557aa8fb7f9d64c035141a3516

DragonFlyBSD doesn't make sure it: https://github.com/DragonFlyBSD/DragonFlyBSD/blob/3854335fb0124ada0eed45beaf8b7485f3f40305/sys/sys/wait.h
