### ISSUE TITLE
SYS_ftruncate is missing on Arm64

### ISSUE THREAD

**Issue by michael2012z** [rust-lang/libc#1803]
Hi, 

In Cloud-hypervisor we reference the const definition `SYS_ftruncate`: 
https://github.com/cloud-hypervisor/cloud-hypervisor/blob/v0.8.0/vmm/src/seccomp_filters.rs#L228

But problem is, `SYS_ftruncate `is only available on X86, it cannot be found on AArch64. 

Was it missed? The version we are using is 0.2.71.

**Comment by JohnTitor** [comment]
Thanks for the report! I've submitted #1805.

**Comment by michael2012z** [comment]
Thanks a lot for fixing this. 
By the way, when will the next release come around?

**Comment by JohnTitor** [comment]
@michael2012z We have a PR for making a release #1807 but I'm holding it off since #1630 wants to be included.

**Comment by michael2012z** [comment]
Thank you.
