### ISSUE TITLE
[CI] CI for the switch target is broken

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/libc#1813]
devkitpro made new release for their pacman and somehow our CI won't work well after that.
CI says:
```
:: Synchronizing package databases...
error: failed retrieving file 'dkp-libs.db' from downloads.devkitpro.org : The requested URL returned error: 403
error: failed to update dkp-libs (unexpected error)
error: failed retrieving file 'dkp-linux.db' from downloads.devkitpro.org : The requested URL returned error: 403
error: failed to update dkp-linux (unexpected error)
error: failed to synchronize all databases
dpkg: error processing package devkitpro-pacman (--install):
 installed devkitpro-pacman package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
```

The command we use on CI works well on my local, perhaps it's signing keys issue on CI?
I disabled the tests for that target as it isn't essential but it'd be great if we could revive it.

CC #1812

**Comment by WinterMute** [comment]
You shouldn't be using pacman on CI, we provide docker images for this purpose - https://hub.docker.com/u/devkitpro

**Comment by JohnTitor** [comment]
@WinterMute Oh, I'll use it instead, thanks!
