### ISSUE TITLE
Request: place type aliases in their own module.

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/libc#1820]
It would be handy if projects could import _just_ the c types.

I propose that the c types be placed in their own module and then (to avoid breaking anyone) they also be publicly re-exported at the crate root. That way people who need just the types can glob import `libc::ctypes::*` (or whatever module name).

**Comment by ryankurte** [comment]
i believe there is already work around moving these types into a module and including base definitions so they are available for _all_ targets, as currently `libc` has to be substituted for `cty` on most of `no_std` platforms.

see: https://github.com/japaric/cty/issues/14 and https://github.com/rust-lang/libc/pull/1286

**Comment by Lokathor** [comment]
(I actually also have a crate that just provides the C types, though I'm its only user :P )

**Comment by LunarLambda** [comment]
Has there been any progress on this? I'd be greatly in favour of having something like `libc::types` available.

I suppose there may be questions about what to include? Just C standard types, or would things like `struct stat` be included too?
As well as, should this be its own crate since there are undoubtedly people who want "just the types, please"

**Comment by Lokathor** [comment]
Yes, you can use the `cty` crate.

**Comment by joshtriplett** [comment]
rust has exported these from `std::os::raw::*` for a while now. I'd love to see that exported from `core` as well. The last time types needed to move from libc to the Rust standard library, it was incredibly disruptive. Let's not go through that again, if we can put them directly in core to begin with this time.

**Comment by Lokathor** [comment]
Actually, minor nit, std::os::raw has its own definitions, not re-exported libc or cty definitions, so there could be a divergence and I'm not sure what the stability rule there is if a divergence does happen.

**Comment by joshtriplett** [comment]
On Tue, Oct 06, 2020 at 06:00:21PM -0700, Lokathor wrote:
> Actually, minor nit, std::os::raw has its own definitions, not re-exported libc or cty definitions, so there could be a divergence and I'm not sure what the stability rule there is if a divergence does happen.

Huh. For some reason I had thought that libc re-exported the definitions
from `std::os::raw`, but it looks like libc only does so for `c_void`.

**Comment by tgross35** [comment]
With `core::ffi` we have the primitive types available in Rust, and Chris added a test recently that they are the same https://github.com/rust-lang/libc/pull/3616. I think we can close this.
