### ISSUE TITLE
libc is missing some program header type constants

### ISSUE THREAD

**Issue by vext01** [rust-lang/libc#1877]
The following program header type constants are missing from libc:
 - `PT_HIOS`
 - `PT_LOPROC`
 - `PT_HIPROC`

Thanks

**Comment by joshtriplett** [comment]
Given that these flags exist in glibc's elf.h, these seem completely reasonable to add to the libc crate. Could you send a pull request adding them? (Please add the whole contiguous block of related constants that contain these, not just those three constants.)
