### ISSUE TITLE
libc expose SIGRTMIN and SIGRTMAX

### ISSUE THREAD

**Issue by Gelox** [rust-lang/libc#1883]
Exposing SIGRTMIN and SIGRTMAX might be problematic as they dynamically change and will therefore be hard to encode as constants. Perhaps exposing them in the form of functions is the best solution? I have very little experience porting from C to Rust so I am not sure what the best way of doing that would be. If someone gave me a point in the right direction then I would be willing to try to tackle this.

Target triplet: x86_64-linux-gnu

Man page for signals:
https://www.man7.org/linux/man-pages/man7/signal.7.html

Other crates looking for feature:
https://github.com/nix-rust/nix/issues/1143

**Comment by joshtriplett** [comment]
I think it would be reasonable to expose a function `libc_sigrtmin()` that calls `__libc_current_sigrtmin()`.

**Comment by Gelox** [comment]
Hi @joshtriplett, I'll gladly make this change but I'm wondering how one exposes the function with the name `libc::sigrtmin()` as far as I can see in the linux module all of the functions are exposed by their C names and there doesn't seem to be a standard for creating an unsafe rust function named `sigrtmin` which then would call the non-public `__libc_current_sigrtmin()`.

So, my questions are these:
Do I create an unsafe rust function named `sigrtmin()` that calls `__libc_current_sigrtmin()` or do I in some other way change the name of `__libc_current_sigrtmin()`? In that case how do I do that?
If I should create an unsafe rust function, where do I do this? Anywhere in the module?

**Comment by clarfonthey** [comment]
I feel like exposing it as an `extern "C"` function is best -- on systems which don't have a direct function for it we can just add a shim for it.
