### ISSUE TITLE
Android needs LFS exports too

### ISSUE THREAD

**Issue by cuviper** [rust-lang/libc#189]
In some ways Android's `bionic` dodges LFS, like its structs `stat` and `dirent` that are always the 64-bit versions.  But as mentioned in its own [32-bit ABI bugs](https://android.googlesource.com/platform/bionic.git/#32_bit-ABI-bugs), `off_t` is still an issue in other places.

Of those that rust itself uses, which we're actively switching to LFS:
- Every `*stat` variant is already 64-bit safe, as noted.
- `readdir_r` is similarly fine since `dirent` is always 64-bit.
- `open` already forces `O_LARGEFILE` implicitly.
- `ftruncate` and `lseek` both take `off_t` parameters, so need explicit LFS support.

At least from gingerbread they do have `ftruncate64` and `lseek64`, and more LFS functions have been added since.  What is the baseline here for Android support?  With that info, I'm willing to work on this myself.

**Comment by alexcrichton** [comment]
Ah this is a case where the support of the standard library and this crate are different. The standard library right now supports API level 18 and above (no idea what release that corresponds to), but liblibc just has *everything* so downstream users can select which release they prefer to target. The image we run CI tests in should in theory be a very up-to-date release of Android.

Along those lines, feel free to add the functions!

**Comment by cuviper** [comment]
OK, 18 is Android 4.3, Jelly Bean MR2 -- quite recent considering I was
looking back at gingerbread. :) That's good to know regardless, as my
follow-up will be to use these in the standard library.

I take it any "extra" libc declarations won't cause link issues? Even in
debug mode?  (I'm not sure how/when these things are pruned in Rust.)

**Comment by alexcrichton** [comment]
Yeah all the definitions in liblibc should just add more metadata to the library, nothing to the actual object file itself
