### ISSUE TITLE
Address family (AF_INET, ...), IPPROTO and other constants missing from Windows implementation

### ISSUE THREAD

**Issue by xanathar** [rust-lang/libc#1890]
I noticed that several networking related constants are missing from the windows implementations (both msvc and gnu); for example all address family constants (`AF_INET`, `AF_INET6`, `AF_UNIX`, etc.), and all `IPPROTO`s.

I can easily contribute these to the project, but wanted to check first if such a contribution is welcome or if the constants are intentionally missing for some reason.

**Comment by sdroege** [comment]
Note that they're part of the [`winapi`](https://docs.rs/winapi/0.3.9/winapi/shared/ws2def/constant.AF_INET.html) crate as part of the `ws2` module, so maybe the reason why they're not in `libc` is that on Windows this is not part of the C library but as part of winsock2. For constants that's not really a problem, but having the functions here too would require the `libc` crate to not only link to the C library but also `ws2`.

**Comment by xanathar** [comment]
Yup, that's the sort of things I was asking about before spending time to contribute the constants.
It's a low-hanging fruit, but that also means there might be a rationale behind why they weren't picked yet (besides the simplest "nobody did it").

Admittedly those constants are not much useful without the winsock functions, and std::net already provides an abstraction over TCP and UDP sockets if one wants to write portable sockets code (with the Windows specific bits, afaict, [here](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/windows/net.rs) )).

The glib/gio use-case is probably a corner case in the big picture, as it's providing an alternative frontend to the socket APIs, so it's in the odd position of needing the constants but not the functions. 

Let's hear the libc people's 2 cents on this anyway to decide the best solution to this (admittedly trivial) problem.

**Comment by retep998** [comment]
I believe the intention is that `libc` on Windows stick strictly to what the CRT provides and does not touch Windows API which is `winapi`'s domain (there are a few exceptions to this but they seem to all be accidental and only still exist due to backwards compatibility). Networking related constants all fall under Windows API and so do not belong in `libc` on Windows.

**Comment by xanathar** [comment]
Thank you for the reply, makes sense.

Closing this issue accordingly.
