### ISSUE TITLE
Allow easy conversion between libc::timeval, libc::timespec and std::time::Duration

### ISSUE THREAD

**Issue by maxbla** [rust-lang/libc#1937]
One way to do this is `impl From<Duration> for timespec`, `impl From<Duration> for timeval` and the reverse - `impl From<timeval> for Duration` and `impl From<timespec> for Duration`. Also on the table is `impl From<timeval> for timespec` and `impl From<timespec> for timeval`. This solution has the issue that `Duration` and `timespec` have nanosecond resolution, while timeval has microsecond resolution. In this system, conversions to timeval would be lossy in nanoseconds, and I think that's okay.

A more heavy-handed approach might look similar to Nix's [TimeValLike](https://docs.rs/nix/0.19.0/nix/sys/time/trait.TimeValLike.html) - a trait for constructing values and getting time units.

**Comment by JohnTitor** [comment]
As explained in #469, I don't think this is an acceptable request.
Thanks for opening the issue anyway :)
