### ISSUE TITLE
Scope of functions in libc crate: can we add things that require linking another "common" lib?

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang/libc#195]
How far outside of actual libc does the libc crate's scope go? Eg, I'm considering adding [`openpty(3)`](http://man7.org/linux/man-pages/man3/openpty.3.html) which requires linking with `libutil` on some platforms but not others[0]. Would this fit in libc?
<br>
---
[0] https://www.gnu.org/software/gnulib/manual/html_node/openpty.html

**Comment by alexcrichton** [comment]
Thanks for the issue! The scope of libc is [currently defined in its RFC](https://github.com/rust-lang/rfcs/blob/master/text/1291-promote-libc.md#scope-of-libc), which means that if it's available on some platform through the standard set of libraries that should be fine, but on other platforms we won't be able to have the API.

**Comment by kamalmarhubi** [comment]
:+1: thanks, I'll make a PR :-)
