### ISSUE TITLE
build.rs cargo:rerun-if-changed

### ISSUE THREAD

**Issue by gilescope** [rust-lang/libc#1978]
I see build.rs doesn't emit any hints to Cargo as to what to look for in terms of changes. 

Cargo has better change detection if build.rs emits things like: 
cargo:rerun-if-changed

If we don't depend on anything else then cargo:rerun-if-changed=build.rs would make for the fastest checks. It's a small detail, but it's a popular crate.

Is this fair or have I missed something?

**Comment by JohnTitor** [comment]
I think this should be fine, @rust-lang/libc does someone have any concerns?

**Comment by Amanieu** [comment]
LGTM

**Comment by gilescope** [comment]
Thanks @JohnTitor - excellent news.
