### ISSUE TITLE
Add getauxval for Android

### ISSUE THREAD

**Issue by jack-signal** [rust-lang/libc#1987]
`getauxval` is useful for detecting CPU specific features such as availability of the ARMv8 AES instructions.

Currently in this crate, `getauxval` is available on Linux but not on Android. This function was added to Android in API Level 18 (https://developer.android.com/ndk/guides/cpu-features). So it might be a problem for someone building to an older API level. However on `aarch64` and `x86_64` the earliest API Level is 21 and thus for these architectures `getauxval` is always available.

Happy to contribute a patch, just wanted to check if enabling `getauxval` only for `aarch64-linux-android` and `x86_64-linux-android` was ok or if you had suggestions on how to handle the possibility of it not being included when built for an old Android.

**Comment by JohnTitor** [comment]
Hey, thanks for the issue!

> Happy to contribute a patch, just wanted to check if enabling `getauxval` only for `aarch64-linux-android` and `x86_64-linux-android` was ok or if you had suggestions on how to handle the possibility of it not being included when built for an old Android.

It's totally okay to add it for these two targets.
