### ISSUE TITLE
Add `memset_s` and/or `explicit_bzero` for platforms that support it

### ISSUE THREAD

**Issue by niluxv** [rust-lang/libc#2009]
target platforms: linux, BSD

I would be interested in adding `memset_s` and `explicit_bzero` from `string.h`. These functions allow securely erasing memory. If a PR would be accepted, I can make one.
One question I would have for linux is: What is the minimum version of libc (glibc/musl etc.) that should be supported? Is this documented somewhere?

@rustbot modify labels: +C-API-request and +O-linux and +O-bsd

**Comment by joshtriplett** [comment]
These functions typically have extra annotations to ensure that compiler optimizations will never remove them. Rust doesn't currently have a means of providing those annotations. Thus, I think we shouldn't add these (and give a false impression of their functionality) until the compiler has a means of doing explicit non-removable zeroing.

**Comment by niluxv** [comment]
I do not see how a compiler could optimize out such call. It can't optimize away an entire FFI call, right? The FFI call could have side effects, as far as the compiler knows... FFI is a very strong optimisation barrier without cross-language/linker-plugin LTO.

As long as the `volatile_set_memory` intrinsic does not have a stable counterpart this is actually the only secure and reasonably fast way to zeroize memory on stable.

**Comment by niacat** [comment]
NetBSD has [explicit_memset(3)](http://man.netbsd.org/explicit_memset.3)
