### ISSUE TITLE
Redox on stable

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/libc#2012]
Currently libc for Redox requires the `static_nobundle` feature, which means it doesn't build on rust stable. Is there any way to work around this?

```log
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/thomas/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.81/src/lib.rs:32:5
   |
32 |     feature(static_nobundle)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `libc`
```

**Comment by JohnTitor** [comment]
I'm not familiar with redox, maybe @jackpot51 has some thoughts?

**Comment by jackpot51** [comment]
This just isn't possible. Redox only supports static linking, and needs the static_nobundle feature. IT would be nice if it was stabilized at some point. Is there a reason you would want to use a stable compiler to target Redox?

**Comment by Thomasdezeeuw** [comment]
@jackpot51 I'm trying to add Redox to the CI of socket2: https://github.com/rust-lang/socket2/issues/78, https://github.com/rust-lang/socket2/issues/181. But I can change it be nighty only.

**Comment by jackpot51** [comment]
@Thomasdezeeuw thank you. We will need that feature stabilized at some point. For now, redox always compiles on nightly. Redoxer will handle this for you automatically

**Comment by JohnTitor** [comment]
Thanks @jackpot51! So, there's no actionable item here and I'm going to close this.
