### ISSUE TITLE
Drop support for CloudABI

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/libc#2025]
Since https://github.com/rust-lang/rust/pull/78439, Rust doesn't support the CloudABI targets anymore. We dropped CI for them (https://github.com/rust-lang/libc/pull/1981) but we still have the CloudABI module (https://github.com/rust-lang/libc/tree/02fe5de20b9d24db107932985aa3b4dc11fe408c/src/cloudabi). We will deprecate it and remove in the future release.

**Comment by joshtriplett** [comment]
If the cloudabi targets no longer exist in Rust, then it's no longer possible to do a build that could access these modules, so I don't think it's a breaking change to remove them.

In theory, someone could use a custom target, or an older version of Rust, but we already don't guarantee that arbitrarily old versions of Rust can build arbitrarily new crates.

**Comment by Amanieu** [comment]
I am also inclined to drop CloudABI support. I don't think this is a breaking change since the target has already been removed from rustc. And honestly nobody is using CloudABI any more, they've all moved to WASI.
