### ISSUE TITLE
Typedef wchar_t to i32 for wasm32-wasi

### ISSUE THREAD

**Issue by abbec** [rust-lang/libc#2045]
Wasi libc has a [`<wchar.h>`](https://github.com/WebAssembly/wasi-libc/blob/main/libc-top-half/musl/include/wchar.h) and `sizeof(wchar_t)` reports 4 which means it should be possible to `type wchar_t = i32;` for wasm32-wasi, right?

**Comment by JohnTitor** [comment]
Seems it's just undeclared, yes. Feel free to send a PR.
