### ISSUE TITLE
Add gettid() for Linux

### ISSUE THREAD

**Issue by jminer** [rust-lang/libc#2076]
I'm using x86_64-unknown-linux-gnu. I need to use `gettid()` in Rust, and it's not in this crate yet. It's got a simple signature:

https://man7.org/linux/man-pages/man2/gettid.2.html

It is Linux-specific. I could probably add it if it would help, but I'm not positive where to add it. From searching, it seems gnu, musl, uclibc, and Android include it, but I don't think Emscripten does (not sure).

I suppose it needs added in either

https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/mod.rs

or in both

https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/android/mod.rs
https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/linux/mod.rs

And it seems like the tests are automatic so they wouldn't need changed?

**Comment by JohnTitor** [comment]
You can go ahead with `linux_like/mod.rs` and check if CI complains about it.

> And it seems like the tests are automatic so they wouldn't need changed?

Yep, you're right.
