### ISSUE TITLE
Move `s390x-unknown-linux-musl` to the build check

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/libc#2085]
It's a tier 3 target and it should be in build.sh.

**Comment by kaniini** [comment]
There isn't a toolchain generated in rustup, which is why we decided to skip it for now.

**Comment by JohnTitor** [comment]
We have a test structure for no core targets with the build-std feature:

https://github.com/rust-lang/libc/blob/5fd6540db9b14fae02ff8a11a6102ee99965ae30/ci/build.sh#L260-L266

**Comment by kaniini** [comment]
It's strange that the linter is hating the constants.  There shouldn't be anything different about the s390x module over other ones.

**Comment by JohnTitor** [comment]
We `pub use` all the items, e.g.:
https://github.com/rust-lang/libc/blob/5fd6540db9b14fae02ff8a11a6102ee99965ae30/src/unix/linux_like/linux/musl/b64/mod.rs#L164-L166

So if the parent module already defines an item, you don't have to define it on the `s390x` module. Most items I removed are re-defined with the same value. Some other items are re-defined with different values so I move them to `cfg_if`.
