### ISSUE TITLE
memmem not available on macos

### ISSUE THREAD

**Issue by hkratz** [rust-lang/libc#2181]
It is available in macos like most FreeBSD functions however it does not seem to be avAilable on ios, see https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/

**Comment by chadbrewbaker** [comment]
You might as well also spam in all the missing neon intrinsics you want :)

**Comment by chadbrewbaker** [comment]
#[cfg(all(unix, not(target_os = "ios")))]  enough? How many places does it need spammed?

https://github.com/rust-lang/libc/search?q=memmove

**Comment by hkratz** [comment]
@chadbrewbaker I don't understand what you mean. Architecture-specific intrinsics are accessible in `stdarch` and `memmove` is available on ios.

**Comment by hkratz** [comment]
@JohnTitor Thanks!
