### ISSUE TITLE
Why not support pthread_spin_lock

### ISSUE THREAD

**Issue by CXWorks** [rust-lang/libc#2229]
Hi all,

I'm wondering why rust-libc crate doesn't support pthread_spin_lock_t in the pthread library. The document is: [https://man7.org/linux/man-pages/man3/pthread_spin_lock.3.html](https://man7.org/linux/man-pages/man3/pthread_spin_lock.3.html )

I guess there are other reasons, could you please tell me more about this choice?

Thx!

**Comment by JohnTitor** [comment]
We usually add the items by request, feel free to open a PR if you want.
