### ISSUE TITLE
support for POSIX_SPAWN_USEVFORK

### ISSUE THREAD

**Issue by godmar** [rust-lang/libc#2269]
On Linux, certain GNU extensions are available if the `_GNU_SOURCE` feature test macro is set.
For instance, in order to use `POSIX_SPAWN_USEVFORK` in `posix_spawn` this feature test macro must be set, see [posix_spawn(3)](https://man7.org/linux/man-pages/man3/posix_spawn.3.html). However, there does not appear to be a `libc::POSIX_SPAWN_USEVFORK`

Is it correct that `libc`'s binding were created without `_GNU_SOURCE` and if so, would it be meaningful to create an option in libc to enable these GNU extensions on platforms that support them?

**Comment by joshtriplett** [comment]
@godmar libc is happy to expose any and all target-specific features on the targets that have them. And we already define `_GNU_SOURCE`. In this case, I think it's just that nobody has added `POSIX_SPAWN_USEVFORK`. I'd be happy to review a PR adding it.
