### ISSUE TITLE
Run ibc-test on the Local Computer

### ISSUE THREAD

**Issue by silence-coding** [rust-lang/libc#2297]
How Do I Run ibc-test on the Local Computer?

![image](https://user-images.githubusercontent.com/32766901/126784246-c0ac7e4b-a5f1-474b-b20c-2c5c4ec2109d.png)

rust:
1.52.1-x86_64-unknown-linux-gnu

Operating System：
Linux DESKTOP-2FS2IK6 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by silence-coding** [comment]
Through run-docker.sh, I found that I did not have permission to pull the image of the community.

**Comment by JohnTitor** [comment]
The message explains what the error is, make sure that you have the certain header files on your local.

> Through run-docker.sh, I found that I did not have permission to pull the image of the community.

You can just run Docker with the Dockerfile to check what happens. The images there should be available publicly.

Anyway, we generally track the issues related to libc itself, but any PRs to improve CI config is welcome, thanks for reporting!

**Comment by silence-coding** [comment]
@JohnTitor  Can the glibc and other dependent versions required by the test be provided?

**Comment by JohnTitor** [comment]
You can check it on [Dockerfile](https://github.com/rust-lang/libc/blob/master/ci/docker/x86_64-unknown-linux-gnu/Dockerfile) or the CI log.
