### ISSUE TITLE
aarch64 fails with newer glibc (ipc_perm.mode)

### ISSUE THREAD

**Issue by posborne** [rust-lang/libc#231]
I'm playing around with some changes that make it easier to run the tests for multiple architectures locally based on recent work merged into Nix.  Running the build/tests in [posborne/rust-cross:arm](https://hub.docker.com/r/posborne/rust-cross/) which is based on Ubuntu 15.10, this following error is received:

```
/data/aarch64-unknown-linux-gnu/debug/build/libc-test-2ff1f50e28187d2d/out/all.c: In function '__test_field_type_ipc_perm_mode':
/data/aarch64-unknown-linux-gnu/debug/build/libc-test-2ff1f50e28187d2d/out/all.c:9148:21: error: return from incompatible pointer type [-Werror]
                     return &b->mode;
                     ^
cc1: all warnings being treated as errors
thread '<main>' panicked at 'explicit panic', /root/.multirust/toolchains/1.7.0/cargo/registry/src/github.com-88ac128001ac3a9a/gcc-0.3.25/src/lib.rs:818
```

It appears that the type of `struct ipc_perm.mode` has a differnt type (`mode_t` I think).  Not sure how best to handle.  Simply changing the type to `mode_t` causes other failures.

**Comment by alexcrichton** [comment]
How did glibc change in this regard? If it wasn't just switching to `mode_t`, did other pieces change as well?

**Comment by kamalmarhubi** [comment]
Aside: @posborne I'm *really* excited for your testing changes here!
