### ISSUE TITLE
'prctl' function missing in 'libc' crate

### ISSUE THREAD

**Issue by fmalinowrhebo** [rust-lang/libc#2336]
This happens when I'm trying to build [caps-rs](https://github.com/lucab/caps-rs).

My environment:
* MacBook Air with M1
* macOS 11.5.2

Is it possible to request this function for builds on macOS?

**Comment by devnexen** [comment]
I m afraid prctl is linux/android syscall specific.

**Comment by fmalinowrhebo** [comment]
I thought so as well. Anyway I hoped for someone to maybe say that there is some equivalent of it in MacOS. Anyway then in this case wouldn't it be possible to disable capabilities that are dependent on `prctl.h` to make it compilable on Mac?

**Comment by devnexen** [comment]
Solaris systems and FreeBSD have something ressemblant to linux capabilities but not macOs.

**Comment by JohnTitor** [comment]
Thanks for reporting, and thanks for answering, David! This sounds like a more general issue than a libc's so I'm going to close.
