### ISSUE TITLE
Handle API evolution and additions

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang/libc#234]
In both #228 and #233, we're having CI failures for constants that aren't present in the headers that the test infrastructure uses.

Possible directions of improvement:
- verifying constants against the most recent kernel headers instead of whatever headers are installed in CI ([suggested by @posborne](https://github.com/rust-lang/libc/pull/233#issuecomment-198060219))
- switch to _generation_ of constant values instead of verification

With generation, there's still a need to pick the correct type for a constant, so it can't be done purely mechanically. Yay C preprocessor!

**Comment by kamalmarhubi** [comment]
This also relates to #121.

**Comment by kamalmarhubi** [comment]
Relevant: [the wiki for predef: Pre-defined Compiler Macros](https://sourceforge.net/p/predef/wiki/Home/), in particular the [Operating Systems](https://sourceforge.net/p/predef/wiki/OperatingSystems/) and [Architectures](https://sourceforge.net/p/predef/wiki/Architectures/) pages. They list commonly predefined macros for OSes and architectures.

The wiki is also available as [an export on GitHub](https://github.com/natefoo/predef/wiki) if you prefer.

**Comment by alexcrichton** [comment]
I would personally not like to go down the route of generation just yet, but we're free to update whatever headers are on the system at any time in my opinion. They will likely inevitably break existing definitions as binary compatibility is now always upheld, but we can deal with it when it comes.

**Comment by kamalmarhubi** [comment]
> They will likely inevitably break existing definitions as binary compatibility is now always upheld, but we can deal with it when it comes.

Could you clarify a little what you mean here?

**Comment by alexcrichton** [comment]
Ah just that whenever we upgrade the OS image to include a newer glibc in the past something's always broken because some constant changes somewhere.

**Comment by gnzlbg** [comment]
For each `target_os`, currently, `libc` only supports a very particular OS version. Some OSes preserve backward compatibility, and this works fine there (linux, windows). Others make very minor breaking changes (macos), others make larger breaking changes, but try to preserve ABI compatibility (FreeBSD), and others do not care at all, and each minor OS release is essentially a completely different target (OpenBSD).  

How to fix this is being discussed in #570 , so I'm closing this issue. Please feel encouraged to chime up there if you care about this.
