### ISSUE TITLE
Why is there no `STD*_FILENO` macros and `ftello` function for Windows?

### ISSUE THREAD

**Issue by bczhc** [rust-lang/libc#2348]
Hello. I want to ask a question...

I used `libc::STDOUT_FILENO` in my program, but GitHub CI failed in Windows compilation, and I found there's no `STDOUT_FILENO` on Windows platforms. Also, `ftello` and `ftello64` doesn't exist for Windows, but there's a `ftell`. 

So are the APIs above not in POSIX standard, or there's no such an relevant API in Windows C library to bind?

**Comment by devnexen** [comment]
you do not have direct equivalence, but you can get similar effect with `_fileno(stdout)`.
for other calls, for 64 bits you have `_ftelli64` for example.

**Comment by bczhc** [comment]
Thanks for your replay! I just have a look to Windows `stdio.h`, and I found there're definitely not such `STD*_FILENO` macro and the `ftello` definitions. So obviously, the libc rust binding cannot bind them. The Windows libc API is so confusing... Issue closed.
