### ISSUE TITLE
Change posix_spawn* prototypes analogously to exec* prototypes

### ISSUE THREAD

**Issue by safinaskar** [rust-lang/libc#2519]
Prototypes of exec* functions (for example, execve) differ from prototypes in POSIX. POSIX specifies `char *const argv[]`, but libc crate specifies `*const *const c_char`, i. e. in libc crate API characters themselves are immutable as opposed to POSIX API. And this difference is a good thing, because, in fact, characters are immutable, and POSIX prototype is simply erroneous (and it cannot be changed because of compatibility). So, thanks a lot for "fixing" prototype for exec* functions. Please, provide similar fix for two posix_spawn* functions. Change type of `argv` and `envp` from `*const *mut c_char` to `*const *const c_char`.

My target triple is x86_64-unknown-linux-gnu

**Comment by JohnTitor** [comment]
Duplicate of #1272, please continue the discussion on the mentioned issue.
