### ISSUE TITLE
`user_fpsimd_struct` on aarch64

### ISSUE THREAD

**Issue by irgstg** [rust-lang/libc#2524]
On aarch64, `user_fpsimd_struct` includes a `__uint128_t` type:
https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/aarch64/sys/user.h;h=9927b3ac3c43096d85f65421c89c8bef5e0bbce9;hb=a85c93c42433aa52d4c5bc18e1dff038a82415bf#l32

There is a known issue regarding `__uint128_t` / `__int128_t` alignment to be different from `u128` / `i128` in rust.
I know that some of you guys faced this issue in some occasions (e.g. #2008).
In #2417 he tried few different ways to commit this struct, which fails tests.

Should we consider any other workaround, if there is any to consider?

**Comment by Gankra** [comment]
PSA: rustc actually correctly aligns u128/i128 on aarch64 linux (android) and macos and it's totally sound to use it for FFI on those platforms! So we can actually properly add these types and unblock everything that wants to use them.

https://github.com/rust-lang/rust/issues/54341#issuecomment-1062498329
