### ISSUE TITLE
Describe how to convert a c_char to a native Rust string, and back

### ISSUE THREAD

**Issue by kevinburke** [rust-lang/libc#2538]
I'm trying to work with a FFI library that accepts (and in some cases returns) C strings (represented as `*const c_char`). I need to convert from Rust strings to C strings, and from C strings to Rust strings. I'm finding it fairly difficult to find up to date information on how to accomplish this in a straightforward way. 

The documentation for `c_char` is pretty sparse: https://docs.rs/libc/0.2.107/libc/type.c_char.html

It's literally just this line:

```
pub type c_char = i8;
```

It would be nice if there was an example here of how to generate this and translate it into a Rust string, or even just a link explaining where to find more information about how to use the type.

**Comment by JohnTitor** [comment]
Note that the main aim of this crate is just to expose the items, and given how many items we maintain, preparing such a doc for each item is quite hard. IMHO the docs like this should go to the [nomicon](https://github.com/rust-lang/nomicon) or a community article. Closing as wontfix here, thanks for reporting anyway!
