### ISSUE TITLE
Is it acceptable to wade in with small comments after a PR is already merged?

### ISSUE THREAD

**Issue by Minoru** [rust-lang/libc#2564]
Hi! Every time a new libc release comes out, I review the diff from the previous version. I sometimes find typos [which I immediately fix](https://github.com/rust-lang/libc/pull/2330), but other times [I'm not that sure](https://github.com/rust-lang/libc/pull/2545/files#r754246039). My question is: what should I do with these findings?

Right now, I just make comments on already-merged PRs, but I understand this doesn't look very nice. OTOH if I don't know how something should be fixed, I can't send a PR to fix it.

My findings so far were all trivial, so I understand if you don't want to bother with this at all. If so, then I'll just send PRs when I'm sure I know how something should be fixed.

**Comment by devnexen** [comment]
I do not think there is anything wrong doing a PR ;-)

**Comment by JohnTitor** [comment]
Yeah, feel free to submit PRs! Thanks for checking those :)
