### ISSUE TITLE
There is no way to construct a sigevent

### ISSUE THREAD

**Issue by gmilleramilar** [rust-lang/libc#2576]
There appears to be no way to construct a [sigevent](https://docs.rs/libc/0.2.108/libc/struct.sigevent.html) outside of the libc crate.  As far as I can tell, you cannot use a struct literal format--because of inaccessible fields-- and there is no constructor, and it does not derive Default.

To illustrate the problem, I have this simple contrived example:

```
fn main() {
    let s = libc::sigevent {
        sigev_value: libc::sigval {
            sival_ptr: std::ptr::null_mut(),
        },
        sigev_signo: 0,
        sigev_notify: 0,
        sigev_notify_thread_id: 0,
    };
    std::process::exit(s.sigev_signo);
}
```

Which fails with 

```
error: cannot construct `sigevent` with struct literal syntax due to inaccessible fields
 --> src/main.rs:2:13
  |
2 |     let s = libc::sigevent {
  |             ^^^^^^^^^^^^^^

```

**Comment by JohnTitor** [comment]
You can use `mem::zeroed` for unused fields. See https://github.com/rust-lang/libc/pull/2346#issuecomment-899226540 for a similar discussion.
