### ISSUE TITLE
`target_vendor = "rumprun"` makes `cargo build --no-default-features` fail for stable and beta

### ISSUE THREAD

**Issue by nodakai** [rust-lang/libc#258]
- https://travis-ci.org/rust-lang/libc/jobs/121326837

Combining shell commands with `;` rather than `&&` doesn't look correct to me. But if that was intentional, please just close this issue.

**Comment by alexcrichton** [comment]
gah I'm not a fan of shell... this is indeed a bug, thanks for the report!
