### ISSUE TITLE
Yank libc 0.1.0 to 0.1.4

### ISSUE THREAD

**Issue by xfix** [rust-lang/libc#2641]
libc versions 0.1.0, 0.1.1, 0.1.2, 0.1.3 and 0.1.4 don't compile anymore. This makes it more annoying to use `cargo update -Z minimal-versions`. Could those versions be yanked? This won't affect ancient versions of Rust, as I doubt those versions are capable of using crates.io-index nowadays.

**Comment by JohnTitor** [comment]
I'm fairly sure that these old versions aren't used now but also doubt if it's worthwhile to yank them just for one nightly feature.

**Comment by JohnTitor** [comment]
Closing in favor of the above reasons, thanks for reporting.
