### ISSUE TITLE
nightly builds on CI broken

### ISSUE THREAD

**Issue by fiveop** [rust-lang/libc#266]
The nightly builds for PRs fail with the error message:

> the crate `X` has been compiled with rustc 1.10.0-nightly (576229fea 2016-04-15), which is incompatible with this version of rustc [E0514]

where `X` in `{std, core, and a few others}`. The failures are not caused by changes due to the PRs, since the first failure (https://travis-ci.org/rust-lang/libc/builds/123657547) happens for a patch that just changes the README.md

**Comment by alexcrichton** [comment]
Thanks for the report! Attempting to fix in https://github.com/rust-lang/libc/pull/267, we'll see how that turns out.

**Comment by alexcrichton** [comment]
Ok, fixed in https://github.com/rust-lang/libc/pull/267
