### ISSUE TITLE
Copyright year and holder name missing from the Apache license

### ISSUE THREAD

**Issue by michaelgrigoryan25** [rust-lang/libc#2660]
Hello, I have noticed that the copyright year and holder name are missing from [`LICENSE-APACHE`](https://github.com/rust-lang/libc/blob/master/LICENSE-APACHE#L189).  Is that intentional? If not, I can open a PR and replace it with `2014-2020 The Rust Project Developers` (the same as in the MIT license).

**Comment by JohnTitor** [comment]
Note that it's on the "APPENDIX" section and [the _license itself_ doesn't include that](https://opensource.stackexchange.com/questions/4149/include-appendix-of-apache-2-0-in-license-file). See the [similar conversation](https://github.com/rust-lang/rust/pull/67734) on rust-lang/rust. I'm going to close this as wontfix but feel free to remove that text if you want.

**Comment by michaelgrigoryan25** [comment]
Sure, will open a PR tomorrow 👍
