### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jirutka** [rust-lang/libc#2672]
Can you please release a new version? The latest stable release is already two months old. I’m waiting for #2639 to be released, so I can open a pull request in nix with a related fix.

**Comment by rtzoeller** [comment]
@jirutka I think you're being misled by the outdated Releases tab on GitHub. There have been multiple releases which have included #2639, starting with 0.2.114.

https://lib.rs/crates/libc/versions

**Comment by Amanieu** [comment]
I never noticed that we had github releases. I'll start making github releases in addition to the tags for future releases.
