### ISSUE TITLE
Add CI to ensure definitions are not removed

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang/libc#270]
In #269 I moved some definitions around in the hierarchy, and ended up losing some functions for a while. Ideally we'd have something in CI that compares API coverage against `TRAVIS_BRANCH` / `APPVEYOR_REPO_BRANCH` to ensure we're only ever adding APIs.

**Comment by alexcrichton** [comment]
Yeah I'd love to have a check like this!
