### ISSUE TITLE
The sched_param structure and pthread functions arent't available for OpenBSD

### ISSUE THREAD

**Issue by vityafx** [rust-lang/libc#2721]
MCVE
```rust
fn main() {
    let param = libc::sched_param;
    println!("{}", param.sched_priority);
}
```
Gives
```
error[E0412]: cannot find type `sched_param` in crate `libc`
```
Target OS: OpenBSD.

The struct, as well as functions necessary for thread schedule management, [should be available in OpenBSD](https://man.openbsd.org/pthread_schedparam.3) as well as they are for NetBSD and FreeBSD. This also goes for `pthread_getschedparam` and `pthread_setschedparam`, and, probably, `__errno_location`.

[The documentation of libc crate for OpenBSD](https://rust-lang.github.io/libc/x86_64-unknown-openbsd/doc/libc/index.html) doesn't even have a mention of those.

Linking the issue in `thread-priority`: https://github.com/vityafx/thread-priority/issues/19

If there is an agreement, I can provide a PR myself, just want a confirmation here.

**Comment by devnexen** [comment]
feel free to make a PR I would say, note that sched_param and related functions exist already for netbsd and ought to be shared between those two as much as possible.

**Comment by vityafx** [comment]
I will close this after some small manual testing via the `thread-priority` crate.
