### ISSUE TITLE
Linux prctl has 5 arguments, all should be specified.

### ISSUE THREAD

**Issue by AdityaAtulTewari** [rust-lang/libc#2722]
Please provide the below information:

# Minimum Working Example without any dependencies (except libc) that shows
  the issue and ideally reproduces in the Rust playground:
```
use libc;
fn main() {
    let mut res : libc::c_int;
    let val : libc::c_ulong = 1;
    let nval: libc::c_ulong = 0;
    unsafe
    {
      res = libc::prctl(libc::PR_SET_THP_DISABLE, val);
    } if res != 0 {
      println!("res was {}", res);
      println!("prctl called with: {}", libc::PR_SET_THP_DISABLE);
    }
    else {println!("Successfully Disabled THP");}
    unsafe
    {
      res = libc::prctl(libc::PR_SET_THP_DISABLE, val,nval,nval,nval);
    } if res != 0 {
      println!("res was {}", res);
      println!("prctl called with: {}", libc::PR_SET_THP_DISABLE);
    }
    else {println!("Successfully Disabled THP");}
}
```
# the target triple - libc supports many targets and many APIs
x86_64-unknown-linux-gnu
# instructions to reproduce, logs (e.g. build logs, links to Travis-CI logs,
  uploads to github gists, etc.).
1. Place the above code in a `src` folder with the following Cargo.toml:
```
[package]
name = "libc-prnctl-error"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.119"
```
2. Run `cargo build --release`. 
3. The output I get is: 
```
res was -1
prctl called with: 41
Successfully Disabled THP
```
4. Thus the first pass failed and the second pass succeeded, because the proper number of arguments were specified.

# Additional Comments:
I think a change to this [line](https://github.com/rust-lang/libc/blob/55cc85ff7f61e4f11b260ecb68b366818dc4bbe0/src/unix/linux_like/linux/mod.rs#L3780) in order to make it match linux documentation as shown [here](https://man7.org/linux/man-pages/man2/prctl.2.html), makes sense. A convenience macro might also allow it use a smaller number of arguments.

**Comment by AdityaAtulTewari** [comment]
Upon additional investigation it seems that the internal definition in Linux uses a variadic argument set, perhaps this change should just be left to a crate about prctl?

**Comment by devnexen** [comment]
does the same test in pure C gives a different outcome ?

**Comment by devnexen** [comment]
what might be more interesting for you is this kind fo wrapper https://github.com/nix-rust/nix/pull/1550 where you do not need to worry about further arguments.

**Comment by AdityaAtulTewari** [comment]
Yeah the same test in pure C seems to give the same result. Thanks for the pointer!
