### ISSUE TITLE
Consider adding socketopt const "IPV6_BOUND_IF" as we need to set/get bound interface on macOS

### ISSUE THREAD

**Issue by KyleRicardo** [rust-lang/libc#2793]
Consider add this to `bsd/apple/mod.rs`:
```rust
pub const IPV6_BOUND_IF: ::c_int = 125;
```
We really need this constant to perform modification on socket options(to bind socket to an interface, more specifically). Though we can temporarily define this on our own, but since `IP_BOUND_IF` is already defined in libc crate, we'd like to keep consistency.
I can make a simple PR if you agree to add this.
Thanks for your hard work.

**Comment by KyleRicardo** [comment]
5 days passed. Any feedback?

**Comment by thomcc** [comment]
If it's in the headers I don't see a reason why a PR wouldn't be accepted.

**Comment by devnexen** [comment]
@KyleRicardo for next time, you do not need "permission" if you think you can do a PR.

**Comment by KyleRicardo** [comment]
@devnexen Ok, next time I'll do a PR directly. BTW thanks for your PR. Hopefully it will be merged soon.
