### ISSUE TITLE
Aarch64 macOS: ucontext_t is not FFI-Safe

### ISSUE THREAD

**Issue by domenukk** [rust-lang/libc#2812]
When using `ucontext_t` in `getcontext` (manually added, the API seems not to be exported on aarch64 mac in libc), like so:
```rust
extern "C" {
    fn getcontext(ucp: *mut ucontext_t) -> c_int;
}
```
the compiler complains that ucontext_t is not ffi-safe, as 128 bit integers are not supported in FFI.
I did not find any use of 128 bit ints, hence, I assume the compiler is overly smart for the neon state(?) which is:
```rust
    #[repr(align(16))]
    pub struct __darwin_arm_neon_state64 {
        pub __v: [[u64; 2]; 32],
        pub __fpsr: u32,
        pub __fpcr: u32,
    }
````

When I hand-roll the ucontext_t struct, including a neon-state like this, the compiler no longer complains.
```rust
#[repr(C, align(16))]
pub struct arm_neon_state64 {
    pub opaque: [u8; (32 * 16) + (2 * mem::size_of::<u32>())],
}
```
Coincidentally, my testcase would segfault after the original getcontext, which may be related.

This is on macos, aarch64, with libc 0.2.121 and rust 1.59.0

**Comment by devnexen** [comment]
Thanks for the report. isn't it because ucontext_t type has a missing field in libc ? mcontext_data

**Comment by devnexen** [comment]
What I can propose eventually :
- adding the "missing" field here (and tests still pass with) but you keep the getcontext prototype in your side. Indeed the *context api on macos is deprecated and the aforementioned field exists solely when used with the *context api (means setting _XOPEN_SOURCE but that create a lot of build warning in all other parts.
- keeping all the definition in your side as you are already doing.

Let me know what you think.

**Comment by domenukk** [comment]
As far as I can tell, there is not really any good alternative to these APIs, and of course it would be great to have them somehow officially supported by the libc create (?)
I guess there is no concept of feature flags to enable deprecated APIs by any chance?

**Comment by devnexen** [comment]
I ve prepared a change, is it possible for you to temporarily tried out this repo/branch ?

> I guess there is no concept of feature flags to enable deprecated APIs by any chance

I added it there but beware it says "no longer supported" whatever that means :-)

**Comment by sug0** [comment]
I think this change broke the sigaction API on Apple silicon. Related to https://github.com/wasmerio/wasmer/issues/4072
