### ISSUE TITLE
MSRV policy for libc crate is work in progress on the libs-team repo

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/libc#2850]
It's difficult to observe potentially important maintenance policy decisions if they happen in another repo. That said, I don't think it's inherently more or less proper to have the discussion in
- https://github.com/rust-lang/libs-team/issues/72

to be clear. As has already been mentioned by one participant in that discussion, while this is clearly an important discussion for the libc crate, it may have ecosystem-wide impacts. Thus, treating it as a discussion for the libs team in general seems appropriate in other ways. Nonetheless, I raise it as an issue here anyways, if only to accomplish the feat of providing a redirect. It's a potential bug in the human interface of this crate, rather than the machine interface.

**Comment by JohnTitor** [comment]
I've pinned this issue and retitled it for awareness, hope repo visitors find this.

**Comment by JohnTitor** [comment]
Let's track this issue on #3248!
