### ISSUE TITLE
libc::TIOCGWINSZ is not defined for FreeBSD targets

### ISSUE THREAD

**Issue by SShrike** [rust-lang/libc#292]
Despite the `ioctl` call TIOCGWINSZ being available on FreeBSD under the `sys/ioctl.h` header, it's not exposed in libc when built for FreeBSD targets.

If this isn't intentional, I was wondering if maybe it could be add for FreeBSD targets, as this is a blocking issue for a project I'm working on.

Compiling and running the following on FreeBSD should prove that TIOCGWINSZ is available on FreeBSD:

```c
#include <stdio.h>
#include <sys/ioctl.h>

int main(int argc, char **argv) {
    struct winsize sz;

    ioctl(0, TIOCGWINSZ, &sz);
    printf("Screen width: %i  Screen height: %i\n", sz.ws_col, sz.ws_row);
    return 0;
}
```

**Comment by alexcrichton** [comment]
Ah constants are just added piecemeal to libc rather than all at once to all platforms typically. There's no particular reason this was left out, and we'd be more than willing to have it! Want to send a PR?

**Comment by SShrike** [comment]
I'd love to submit a PR, but I'm completely new to syscalls/ioctl, etc. *as* well as developing for FreeBSD.

My current understanding is that the ioctl calls are manually defined by figuring out their request code. Unfortunately I have no idea how exactly I'm supposed to find the code for FreeBSD. On Linux it's dead easy, as there's a convenient list [here](http://man7.org/linux/man-pages/man2/ioctl_list.2.html).

Perhaps you could give me some pointers? I'm usually in IRC around 6-12 PM NZST during the week.

**Comment by alexcrichton** [comment]
Ah no worries! I've typically just dug around in the FreeBSD headers to look for these values (I don't have a machine on hand). Our [linux-cross](https://github.com/rust-lang/rust-buildbot/tree/master/slaves/linux-cross) docker image should have a bunch of headers for cross compilation, and you may be able to poke around the sources [downloaded here](https://github.com/rust-lang/rust-buildbot/blob/master/slaves/linux-cross/build_freebsd_toolchain.sh) perhaps?

**Comment by SShrike** [comment]
Okay, after some thinking I realised I could just do this:

```c
#include <sys/ioctl.h>
#include <stdio.h>
#include <unistd.h>

int main (int argc, char **argv) {
    printf ("Code: 0x%04lx\n", TIOCGWINSZ);
    return 0;
}
```

Since I've now got the right request code, I'll get to adding it to libc.
