### ISSUE TITLE
Publish a new version of libc to unquote std crate

### ISSUE THREAD

**Issue by SSheldon** [rust-lang/libc#3]
Now that rust-lang/rust#23786 is merged, publishing a new version of libc should fix the `note: use an identifier not in quotes instead` warning.

**Comment by sfackler** [comment]
@alexcrichton Ping, liblibc's broken on the new nightly

**Comment by alexcrichton** [comment]
The repo as-is won't work due to https://github.com/rust-lang/rust/pull/23811 but I have pushed a new version which works.
