### ISSUE TITLE
Adding directory file descriptor APIs (openat, mkdirat, *at...)

### ISSUE THREAD

**Issue by darnuria** [rust-lang/libc#306]
The following list of function were added by `POSIX.1-2008`.

It include  `openat(2)` and other syscalls who are relative to a directory file descriptor. (i.e., `execveat(2)`, `faccessat(2)`, `fanotify_mark(2)`, `fchmodat(2)`,  `fchownat(2)`,  `fstatat(2)`,  `futimesat(2)`,  `linkat(2)`,  `mkdirat(2)`, `mknodat(2)`,  `name_to_handle_at(2)`,  `read‐linkat(2)`,  `renameat(2)`,  `symlinkat(2)`,  `unlinkat(2)`, `utimensat(2)`, `mkfifoat(3)`, and `scandirat(3)`).

If it's justified to add this API to rust libc binding, I can take it and make a commit.

As a reference a citation of the rationale form man 2 openat on my Linux:
> First, openat() allows an application to avoid race conditions that could occur when using open()
> to open files in directories other than the current working directory. These race conditions
> result from the fact that some component of the directory prefix given to open() could
> be changed in parallel with the call to open(). Suppose, for example, that we wish to create
> the file path/to/xxx.dep if the file
> path/to/xxx exists. The problem is that between the existence check and the file creation step,
> path or to (which might be symbolic links)
> could be modified to point to a different location. Such races can be avoided by opening a file
> descriptor for the target directory,  and then specifying that file descriptor as the dirfd
> argument of (say) fstatat(2) and openat().

> Second, openat() allows the implementation of a per-thread "current working directory", via
> file descriptor(s) maintained by the application. (This functionality can also be obtained by
> tricks based on the use of /proc/self/fd/dirfd but less efficiently.)

**Comment by alexcrichton** [comment]
I'd love to have these added! We basically include anything and everything we can find in libc and friends :)

Feel free to take a stab at a commit yourself!

**Comment by darnuria** [comment]
I opened a pull-request: https://github.com/rust-lang/libc/pull/307

**Comment by alexcrichton** [comment]
Thanks!

**Comment by alexcrichton** [comment]
Done in https://github.com/rust-lang/libc/pull/307, so closing.
