### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang/libc#311]
Last release was over a month ago.

```
$ git log --oneline 0.2.11.. | wc -l
67
```

:-)

**Comment by kamalmarhubi** [comment]
Probably worth waiting on a couple PRs if they seem close, eg #307.

**Comment by posborne** [comment]
On the other hand pushing another release a few days later does not cause significant harm.

**Comment by alexcrichton** [comment]
Done!
