### ISSUE TITLE
dccp exports are tied to glibc on linux

### ISSUE THREAD

**Issue by nekopsykose** [rust-lang/libc#3132]
the various DCCP_ exports such as `DCCP_SOCKOPT_SERVICE` are tied to `linux/gnu` (or android). that means they are not present on linux/musl.

however, these defines don't come from the libc. for instance:

```c
#include <sys/socket.h>
#include <stdio.h>

int main(void) {
  printf("%d\n", DCCP_SOCKOPT_SERVICE);
}
```

fails to compile on either glibc or musl. this is because they actually come from `<linux/dccp.h>`.

since they come from the kernel headers, they should also be present in linux/musl/mod.rs (or wherever they are meant to be defined here.)

(mostly an upstream version of a downstream bug report: https://github.com/rust-lang/socket2/issues/405)

**Comment by nekopsykose** [comment]
(apologies i didn't provide a rust example, but this is reasonably obvious given the linked downstream issue)

**Comment by Thomasdezeeuw** [comment]
Maybe it's as simple as move the constant from the GNU (and Android) locations:
* https://github.com/rust-lang/libc/blob/5e98ea33195cc867faad2355f16c9bef1dad6a47/src/unix/linux_like/linux/gnu/mod.rs#L733-L749
* https://github.com/rust-lang/libc/blob/106b57a796145c42f9a385a2a8cf764abbc66624/src/unix/linux_like/android/mod.rs#L1394-L1410

To `linux_like/mod.rs`? https://github.com/rust-lang/libc/blob/106b57a796145c42f9a385a2a8cf764abbc66624/src/unix/linux_like/mod.rs

**Comment by nekopsykose** [comment]
> To linux_like/mod.rs?  

that sounds like it would be correct in terms of API surface to me

**Comment by nyurik** [comment]
I think I am hitting this issue when building a docker image with musl. When do you think you can release it? Thx!
