### ISSUE TITLE
Do not link statically against libc by default for musl targets

### ISSUE THREAD

**Issue by joerg-krause** [rust-lang/libc#314]
By default libc is linked statically for musl targets except for the MIPS architecture: https://github.com/rust-lang/libc/blob/master/src/unix/mod.rs#L197-L200.

This is a problem for custom musl targets like ARM: https://github.com/joerg-krause/rust-cross-libs/blob/master/cfg/armv5te-unknown-linux-musl.json

By design, it's wrong to depend on the architecture if linking is done dynamically or statically. It should depend on the value of `dynamic_linking`: https://github.com/rust-lang/rust/blob/master/src/librustc_back/target/mod.rs#L450.

**Comment by alexcrichton** [comment]
This is somewhat related to https://github.com/rust-lang/libc/issues/290 as well which is basically saying that there's not a great way to control how libc is linked today, unfortunately.

**Comment by joerg-krause** [comment]
Is it possible to use the existing `dynamic_linking` to check how libc should be linked?

**Comment by alexcrichton** [comment]
Maybe? I'm not sure how invasive of a compiler change that'd end up being... (and it'd definitely be kinda randomly in the back of the compiler)

**Comment by alexcrichton** [comment]
Solved by https://github.com/rust-lang/rfcs/blob/master/text/1721-crt-static.md and https://github.com/rust-lang/libc/pull/446, implemented in https://github.com/rust-lang/rust/pull/37545
