### ISSUE TITLE
Include WUNTRACED in `sys/wait.h` constants

### ISSUE THREAD

**Issue by nikklassen** [rust-lang/libc#315]
For the `wait` family the only constant flag that is defined is WNOHANG.  The POSIX standard defines WUNTRACED as well. I would be happy to create a PR for this except I don't know how to find the value of the constant on Solaris. Linux also defines some more flags like WCONTINUED that could be added as well.

**Comment by alexcrichton** [comment]
Sure! It's ok to leave out the value one some platforms and only include it on the ones you can find the value for, so no worries there. Also feel free to add any other flags, they'd definitely be welcome!
