### ISSUE TITLE
windows: stat::st_mode and S_IFMT are of different type

### ISSUE THREAD

**Issue by cgzones** [rust-lang/libc#3161]
On windows `stat::st_mode` https://github.com/rust-lang/libc/blob/bac14427831aaff9b79dcdd125c03109414215c5/src/windows/mod.rs#L60 and `S_IFMT` (and other mode flags) https://github.com/rust-lang/libc/blob/bac14427831aaff9b79dcdd125c03109414215c5/src/windows/mod.rs#L146 are of different type, resulting in code like
```
fn is_regular(stat: &libc::stat) -> bool {
    stat.st_mode & libc::S_IFMT == libc::S_IFREG
}
```
to not be portable.

**Comment by ChrisDenton** [comment]
Here's the [ucrt header](https://github.com/microsoft/win32metadata/blob/9bde55b65e3ed63b0473c47c1ef1c5d359c48945/generation/WinSDK/RecompiledIdlHeaders/ucrt/sys/stat.h).
