### ISSUE TITLE
`test_cmsg_nxthdr` fails due to alignment checks for pointer dereferences

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/libc#3181]
Example run: https://cirrus-ci.com/task/5904059698249728?logs=test#L85:
```
running 5 tests
test t::test_cmsg_data ... ok
test t::test_cmsg_firsthdr ... ok
test t::test_cmsg_len ... ok
test t::test_cmsg_space ... ok
test t::test_cmsg_nxthdr ... FAILED
failures:
---- t::test_cmsg_nxthdr stdout ----
thread 't::test_cmsg_nxthdr' panicked at 'misaligned pointer dereference: address must be a multiple of 0x4 but is 0x1b6966ed4d1', libc-test/test/cmsg.rs:74:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It's caused by https://github.com/rust-lang/rust/pull/98112

**Comment by ChrisDenton** [comment]
Hm, this tests looks like it's deliberately doing unaligned pointer reads/writes? Which seems a bit weird but maybe I'm missing something. The easy fix would be to make the unaligned access explicit (e.g. using `ptr::read_aligned` et al).

But it'd be good to know if this is deliberate or an oversight.
