### ISSUE TITLE
Clarify platforms that are tested / guaranteed to build

### ISSUE THREAD

**Issue by jbg** [rust-lang/libc#3186]
The README says "See [ci/build.sh](https://github.com/rust-lang/libc/blob/master/ci/build.sh) for the platforms on which libc is guaranteed to build for each Rust toolchain."

`ci/build.sh` lists [a lot of platforms](https://github.com/rust-lang/libc/blob/master/ci/build.sh#L92) — in particular, musl Linux targets on which libc currently fails to build — but it's unclear how that guarantee is provided since it appears that GitHub CI is currently testing only i386/x86_64 Linux glibc, macOS 12 and Windows 2022, and Cirrus CI is testing only FreeBSD 12/13/14. Is there another CI system running somewhere that isn't linked, or is the claim in the README out of date?

**Comment by jbg** [comment]
Sorry, just to clarify: do you plan to correct the statement in this repo's top-level README that the platforms listed in `ci/build.sh` are guaranteed to build? It would seem pretty clear that they are not, since 0.2.140 was released with all of the *-musl-* platforms failing to build.

**Comment by JohnTitor** [comment]
AFAIK musl build isn't broken, read https://github.com/rust-lang/libc/pull/3177#issuecomment-1495466789. Or, do you have any other issues? If so, it means our CI doesn't catch it and we have to investigate.

**Comment by jbg** [comment]
Thanks for the clarification on the other issue. I'm still really curious about CI though — where are the platforms other than glibc Linux / macos / Windows / FreeBSD being tested? GH Actions has the first three and Cirrus has FreeBSD, where are musl Linux and the rest tested?

**Comment by JohnTitor** [comment]
We run _full_ CI on Docker on GitHub Actions (which is triggered by bors, a cute bot taking care of merge operations): https://github.com/rust-lang/libc/blob/master/.github/workflows/bors.yml

You can trace how things are invoked from `run-docker.sh` :)

**Comment by jbg** [comment]
Thanks, I can start to see how it's working now! Thanks for taking the time to point me in the right direction 😄
