### ISSUE TITLE
utmp function family missing on musl

### ISSUE THREAD

**Issue by Ecordonnier** [rust-lang/libc#3190]
Hello,
functions like getutxent, setutxent, endutxent, struct utmpx, etc. are missing from the musl implementation ( src/unix/linux_like/linux/musl/mod.rs ), even though those functions are implemented in musl (see https://git.musl-libc.org/cgit/musl/tree/include/utmpx.h ).

As reference, see this [commit](https://github.com/rust-lang/libc/commit/98fd3188e7d46db84d321475344f2f82d958b0c7) which added the function for solaris, as well as the man page: https://linux.die.net/man/3/endutxent

**Comment by joshtriplett** [comment]
Why is this trying to change O_LARGEFILE?

**Comment by Ecordonnier** [comment]
@joshtriplett  did you mean to ask this in the pull-request?

**Comment by andrewliebenow** [comment]
These changes have been merged in, but have not been included in any subsequent releases:

```
diff --git a/src/unix/linux_like/linux/musl/mod.rs b/src/unix/linux_like/linux/musl/mod.rs
index a4c1f708afd50..d8b2767669309 100644
--- a/src/unix/linux_like/linux/musl/mod.rs
+++ b/src/unix/linux_like/linux/musl/mod.rs
@@ -900,6 +900,13 @@ extern "C" {
 
     pub fn dirname(path: *mut ::c_char) -> *mut ::c_char;
     pub fn basename(path: *mut ::c_char) -> *mut ::c_char;
+
+    pub fn getutxent() -> *mut utmpx;
+    pub fn getutxid(ut: *const utmpx) -> *mut utmpx;
+    pub fn getutxline(ut: *const utmpx) -> *mut utmpx;
+    pub fn pututxline(ut: *const utmpx) -> *mut utmpx;
+    pub fn setutxent();
+    pub fn endutxent();
 }
 
 // Alias <foo> to <foo>64 to mimic glibc's LFS64 support
```

https://github.com/rust-lang/libc/pull/3213/commits/e3caaf6b0ea08ae294e25a861022c256a7535ec4#r1431346483

Is this waiting on version 0.3 (https://github.com/rust-lang/libc/pull/3213#issuecomment-1851732478)?

**Comment by Ecordonnier** [comment]
Yes or is waiting on 0.3 (which was renamed to 1.0).
