### ISSUE TITLE
Usage of `rustc-std-workspace-core` is wrong

### ISSUE THREAD

**Issue by HKalbasi** [rust-lang/libc#3225]
In the `Cargo.toml` of this repository, `rustc-std-workspace-core` is used in this way:
```
rustc-std-workspace-core = { version = "1.0.0", optional = true }
```
But in anywhere else, [for example hashbrown](https://github.com/rust-lang/hashbrown/blob/4ba7f3336fa86c8210979c6b4d17867e41ac8dbe/Cargo.toml#L24), it is different:
```
core = { version = "1.0.0", optional = true, package = "rustc-std-workspace-core" }
```
And per the [`rustc-std-workspace-core` readme](https://github.com/rust-lang/rust/blob/master/library/rustc-std-workspace-core/README.md) using the `core` name for dependency is the correct way. It is causing problem for rust-analyzer to resolve names from `std > libc > core` as it can't see that the libc in the sysroot is dependent on core.

If my understanding is correct, I can file a PR to fix it.

**Comment by JohnTitor** [comment]
Feel free to submit a PR if it doesn't break our MSRV!

**Comment by HKalbasi** [comment]
I was wrong, `libc` uses `extern crate rustc_std_workspace_core as core` which is equivalent to renaming the crate, and the r-a problem wasn't this (I don't know yet what the problem is). I still slightly prefer to make it consistent with others, but `package` is added in cargo `1.31`. If cargo was smart enough to ignore `package` field for optional unused dependencies, it would be good, but I guess it isn't and will break the MSRV, so closing.
