### ISSUE TITLE
struct *linger* is missing

### ISSUE THREAD

**Issue by sateffen** [rust-lang/libc#327]
Hey,

the `linger {int l_onoff, int l_linger}` struct is missing in this binding. I checked it's implementation in [glibc](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/bits/socket.h;h=2eb95f7e20b8b68685ac2363b4b2db72cab8d98a;hb=HEAD#l402) and [musl](https://git.musl-libc.org/cgit/musl/tree/include/sys/socket.h#n40), but it's missing in this binding.

I guess the struct should look like in the crate [winapi](https://github.com/retep998/winapi-rs/blob/e13b8561738d33f52cbde4fd49ce8dd73025a610/src/winsock2.rs#L113).

**Comment by alexcrichton** [comment]
Ah yeah should be good to add at any time!

**Comment by sateffen** [comment]
Ok, it's a bad idea to take the struct from winapi, because on windows you need to set u_short's, on *nix systems you need to set int's, so we need to set it so c_int, not u16.

**Comment by alexcrichton** [comment]
Now fixed!
