### ISSUE TITLE
emscripten time_t has wrong size

### ISSUE THREAD

**Issue by benjamin-sieffert** [rust-lang/libc#3306]
`time_t` is 64bit on emscripten since https://github.com/emscripten-core/emscripten/pull/17401
Currently the undersized struct definition here truncates the last 4 bytes of the `timespec`, I believe, so that `Instant::now()` etc. end up having no sub-second resolution on `wasm32-unknown-emscripten`.

Filed these issues with more details before I landed here:
https://github.com/emscripten-core/emscripten/issues/19872
https://github.com/rust-lang/rust/issues/113852

It is curious to note that `time_t` was only 32-bit for a short while, starting with https://github.com/emscripten-core/emscripten/pull/16966 (edit: according the comment in that PR, the size on wasm32 stayed the same at that point, so I presume it was indeed 64-bit for the first time from 17401)
~~although it has been 32-bit in this repo for 6 years. I am not seeing the same issue before 16966 that I am seeing after 17401, however. So there is probably another glitch or two that either masked the issue before 16966 or (in between 16966 and 17401) enabled the issue to surface as soon as the size became wrong again.~~

Cheers!

**Comment by kleisauke** [comment]
I think PR https://github.com/rust-lang/libc/pull/3569 would fix this.
