### ISSUE TITLE
`SYS_close` exposed for macOS (arm)

### ISSUE THREAD

**Issue by tony-go** [rust-lang/libc#3311]
Hey 👋🏼 

I'm trying to play with `libc::syscall` but I get this error:

```text
error[E0425]: cannot find value `SYS_open` in crate `libc`
  --> src/main.rs:10:38
   |
10 |         let fd = libc::syscall(libc::SYS_open, path.as_ptr(), libc::O_RDONLY, 0);
   |                                      ^^^^^^^^ not found in `libc`
```

I guess that some stuff are not exposed for macOS?

Let me know if I can help :)

With love ❤️

**Comment by devnexen** [comment]
Note that the syscall interface is deprecated since Sierra.

**Comment by tony-go** [comment]
Hey @devnexen thanks for this answer :) I learned something today 🙌🏼 

So maybe the `asm` macro is probably the only remaining way to play with syscall?

**Comment by devnexen** [comment]
this is from the C's header.

<img width="643" alt="image" src="https://github.com/rust-lang/libc/assets/4922778/952dc279-f398-4efb-be8e-e7b02e5f0660">

**Comment by tony-go** [comment]
Thanks a lot @devnexen, yeah I should have looked there before opening this issue :)
