### ISSUE TITLE
Provide zerocopy trait implementations behind feature flag

### ISSUE THREAD

**Issue by joshlf** [rust-lang/libc#3317]
A common use of `unsafe` code is to access or modify the bytes of libc types (e.g. by transmuting them; [here's an example](https://github.com/bytecodealliance/rustix/blob/main/src/backend/libc/net/ext.rs)). Many libc types could implement the zerocopy traits ([FromBytes](https://docs.rs/zerocopy/latest/zerocopy/trait.FromBytes.html), [AsBytes](https://docs.rs/zerocopy/latest/zerocopy/trait.AsBytes.html), and [Unaligned](https://docs.rs/zerocopy/latest/zerocopy/trait.AsBytes.html)) by using a custom derive, so this would just be a matter of adding `#[cfg_attr(feature = "zerocopy", derive(FromBytes, AsBytes, Unaligned))]` to the types which support it. This would allow all of those uses to be safe.

If this is something that the maintainers would be open to, I'd be happy to put up a PR.

**Comment by tgross35** [comment]
This needs some level of team discussion since it would involve an ecosystem crate. I don't really have any objection for an addition in 1.0 (or later) as long as it is pretty unintrusive.

**Comment by joshlf** [comment]
> This needs some level of team discussion since it would involve an ecosystem crate, I suggested a Zulip discussion on [#3924 (comment)](https://github.com/rust-lang/libc/pull/3924#issuecomment-2356572073). I don't really have any objection for an addition in 1.0 (or later) as long as it is pretty unintrusive.

I've started a [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/351149-t-libs.2Fcrates/topic/libc.20optional.20dependency.20on.20zerocopy).

**Comment by joshlf** [comment]
@tgross35 Is there an official process to put this proposal forward somewhere? Not sure whether to take the radio silence on the Zulip thread as disinterest or lack of opposition.

**Comment by tgross35** [comment]
I think the t-libs/crates channel just doesn't get very much traffic. I'll poke things here tomorrow.

**Comment by joshlf** [comment]
Sounds good, thanks!

**Comment by joshlf** [comment]
Per the [Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/libc.20optional.20dependency.20on.20zerocopy/near/474417305), I'm going to close this for now.
