### ISSUE TITLE
src/unix/hermit/ is dead code as hermit is no longer cfg(unix)

### ISSUE THREAD

**Issue by egrimley-arm** [rust-lang/libc#3318]
As verified with
```
rustc -Z unstable-options --target=aarch64-unknown-hermit --print target-spec-json | grep unix
```
`hermit` had `"target-family": "unix"` removed between versions 1.39.0 and 1.40.0 of `rustc`, or between `nightly-2019-10-26` and `nightly-2019-10-27`.

This may well not be a bug in `libc` but I would like to know how to access the types defined in `src/unix/hermit/` when using a recent version of `rustc`.

(@stlankes made relevant changes to `libc` and `rustc` and might be able to help.)

**Comment by stlankes** [comment]
@mkroening Please correct me, if I am wrong.

During the years it changed and it doesn't belong to the family `unix`. Consequently it is dead code. Should I remove it?

**Comment by egrimley-arm** [comment]
Are some of the types defined in `src/unix/hermit/` needed for `vsock` (https://github.com/hermitcore/libhermit-rs/pull/826)?

**Comment by mkroening** [comment]
Stefan changed this in [rust-lang/rust@`c1e440a`#R22](https://github.com/rust-lang/rust/commit/c1e440a90f472468c8069ba6254b23c6feedc32e#diff-7fefa017c327eb864c54dae469c7f12dba3de44d945650a8f39943c97d575021R22).

This was when we migrated away from newlib for Rust userspace and directly called into the kernel instead. So I'd say, anything `#[cfg(all(target_os = "hermit", unix))]` is safe to remove.
