### ISSUE TITLE
[API Request] Support `reboot()` on macOS

### ISSUE THREAD

**Issue by sisungo** [rust-lang/libc#3327]
## Target
macOS targets, like `aarch64-apple-darwin`.

## API Link
[Mac OS X Manual Page For reboot(2)](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/reboot.2.html).

Its signature in C is `int reboot(int howto)`, which is represented `fn reboot(howto: c_int) -> c_int` in Rust.

It comes with the following macros:
 - `RB_AUTOBOOT`
 - `RB_ASKNAME`
 - `RB_DFLTROOT`
 - `RB_DUMP`
 - `RB_HALT`
 - `RB_INITNAME`
 - `RB_KDB`
 - `RB_NOSYNC`
 - `RB_RDONLY`
 - `RB_SINGLE`

## Example
`reboot()` is used to reboot the device. A minimal self-contained example looks like:
```rust
#[link(name = "System")]
extern {
    fn reboot(howto: i32) -> i32;
}

fn main() {
    unsafe {
        reboot(0);
    }
}
``` 

## Other Information
This is an Apple Private API. In C, it requires `#define __APPLE_API_PRIVATE` to work.

**Comment by devnexen** [comment]
I m not entirely sure it s a good idea to add private apis in this crate, usually it is private for a reason (as not meant to be used from the userland's standpoint, apis could change over time, etc). But that's not for me to decide about this, just personal opinion :).

**Comment by JohnTitor** [comment]
Yeah, closing in favor of the reason described above. Thanks for requesting anyway!
