### ISSUE TITLE
F_PUNCHHOLE

### ISSUE THREAD

**Issue by anacrolix** [rust-lang/libc#3336]
Apple has F_PUNCHHOLE for punching file system holes.

aarch64-apple-darwin

fcntl.h:
```
#define F_PUNCHHOLE     99              /* Deallocate a range of the file */
/* fpunchhole_t used by F_PUNCHHOLE */
typedef struct fpunchhole {
	unsigned int fp_flags; /* unused */
	unsigned int reserved; /* (to maintain 8-byte alignment) */
	off_t fp_offset; /* IN: start of the region */
	off_t fp_length; /* IN: size of the region */
} fpunchhole_t;
```

Happy to add this myself with some pointers. Cheers!

**Comment by devnexen** [comment]
please do :-)  here is the [contributing guide](https://github.com/rust-lang/libc/blob/HEAD/CONTRIBUTING.md).

**Comment by anacrolix** [comment]
Woops, already did, here's the PR https://github.com/rust-lang/libc/pull/3337
