### ISSUE TITLE
chmod & fchmodat cannot set permissions to 2750

### ISSUE THREAD

**Issue by fbatogo** [rust-lang/libc#3417]
Attempting to set permissions to 2750 with chmod & fchmodat (and maybe others) results in permissions only being set to 0750.  This appears to have something to do with the group execute bit being set as setting permissions to something like 2740 appears to work correctly.

This code will trigger the problem:

        let mycstr = CString::new("/path/to/test/file").expect("CString::new failed");

        let res = unsafe { libc::chmod(mycstr.as_ptr(), 0o2750) };
        println!("res: {}", res);

The roughly equivalent C code below allows the permissions to be set correctly:

#include <sys/stat.h>
#include <stdio.h>

int main()
{
  printf("Result: %d\n", chmod("/path/to/test/file", 02750));
}

I can confirm this issue happens on :

armv7-unknown-linux-gnuabihf
i686-unknown-linux-gnu
x86_64-unknown-linux-gnu
i686-unknown-linux-musl

**Comment by JohnTitor** [comment]
We just provide the wrapper, i.e. don't have any implementation here:
https://github.com/rust-lang/libc/blob/2dcc239ee85bb8d639620c227676c1269207319f/src/unix/mod.rs#L718

And the provided code succeeds on my target (`x86_64-unknown-linux-gnu`), so there should be misconfiguration on your Rust toolchain, I think.

**Comment by fbatogo** [comment]
In case someone comes across this issue in the future, you are probably setting the ownership of a file around the same time you are setting permissions.

If you set the permissions, and include the SUID or SGID flag in those permissions, Linux will clear those flags when you set the ownership.   Setting ownership first, and then permissions allows it to work properly.
