### ISSUE TITLE
Migrate from bors to the merge queue feature

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/libc#3419]
docs: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

It should be achieved by running bors CI on `merge_group` event.
IIRC bors doesn't support a multi-release branches strategy, so we have to migrate to the merge queue before going ahead to v0.3.

**Comment by JohnTitor** [comment]
Requested to t-infra: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/merge.20queue.20for.20libc

**Comment by tgross35** [comment]
Merge queue is active so I think this is all set :)
