### ISSUE TITLE
Add support for getpgid/setpgid calls

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/libc#345]
# getpgid

http://linux.die.net/man/2/getpgid

https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man2/getpgid.2.html

http://www.freebsd.org/cgi/man.cgi?query=getpgid&sektion=2

# setpgid

http://linux.die.net/man/2/setpgid

https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man2/setpgid.2.html

http://www.freebsd.org/cgi/man.cgi?query=setpgid&sektion=2

**Comment by alexcrichton** [comment]
Sounds good to me, PRs always welcome!

**Comment by frewsxcv** [comment]
Looks like `setpgid` already exists, though I added `setpgrp` for symmetry since we already have `getpgrp`.
