### ISSUE TITLE
"Portuguese" is misspelled in generated psp file

### ISSUE THREAD

**Issue by Takashiidobe** [rust-lang/libc#3497]
In https://github.com/rust-lang/libc/blob/0292b4eff4dc8f83c2098fa97ae2623b557c299f/src/psp.rs#L1018, Portuguese is misspelled.

 I don't think this can be fixed without causing breakage due to it being an enum variant, so maybe it should remain?

**Comment by JohnTitor** [comment]
cc @sajattack as you've worked on the PSP declarations

**Comment by sajattack** [comment]
It looks like the C library we sourced our defs from misspelled it too. https://github.com/pspdev/pspsdk/blob/master/src/utility/psputility_osk.h
I wonder if the official sony one did. There hasn't been much usage of the OSK so it shouldn't be a big deal if you want to fix it.

**Comment by Takashiidobe** [comment]
Can we look at the official sony osk header file?

**Comment by sajattack** [comment]
It was leaked so it's probably not legally a good idea to take things from the official sdk if we want to stay above board.

**Comment by Takashiidobe** [comment]
Well, looking at https://github.com/search?q=PORTUGESE&type=code, where there are 77k instances of portugese, I guess its not that bad. 

I guess it can be fixed someday when libc 0.3 happens?

**Comment by JohnTitor** [comment]
Yeah, let's not correct it then. Thank you for clarifying!
