### ISSUE TITLE
How to use libc in Windows

### ISSUE THREAD

**Issue by akitaSummer** [rust-lang/libc#3545]
Hello, I've been working on a user-space file system project, and I've been using libc on Linux and macOS, which has been quite useful. However, I'm not sure if libc is still applicable on Windows. For instance, I have the following code:

```rust
write(
    file.as_raw_fd(),
    slice.as_ptr() as *const c_void,
    slice.len(),
)
```
This code works fine on Linux, but it's not compatible with Windows because Windows doesn't have file descriptors (fd), only handles. I'd like to ask whether it's possible to use libc on Windows, and if so, how should I modify my code?

Thanks

**Comment by JohnTitor** [comment]
You can check docs.rs, for example x86_64-pc-windows-msvc is here: https://docs.rs/libc/latest/x86_64-pc-windows-msvc/libc/index.html

But I'd recommend checking the windows-rs, which exposes many more APIs: https://github.com/microsoft/windows-rs

**Comment by akitaSummer** [comment]
@JohnTitor 
My friend, I understand your point, and I have also checked the documentation for libc. Taking `write` as an example, its definition is:

```rust
pub unsafe extern "C" fn write(
    fd: c_int,
    buf: *const c_void,
    count: c_uint
) -> c_int
```
However, the type of `file.as_raw_handle()` is `*mut c_void`. Can I directly use `handle as c_int` for this?

Thanks

**Comment by ChrisDenton** [comment]
libc uses fds (file descriptors), not handles. If you want to use libc instead of the raw Windows API then you'll either need to open the file using libc or else create a new fd using the raw handle via [open_osfhandle](https://docs.rs/libc/latest/x86_64-pc-windows-msvc/libc/fn.open_osfhandle.html).

**Comment by akitaSummer** [comment]
@ChrisDenton Thank you, your solution has resolved my issue.
