### ISSUE TITLE
Add missing definitions from linux/include/uapi/linux/netfilter/nf_tables.h

### ISSUE THREAD

**Issue by brizental** [rust-lang/libc#3566]
There are missing definitons from `linux/include/uapi/linux/netfilter/nf_tables.h`. I am opening this ticket due to a missing definitions for `NFT_CT_ZONE`, but upon checking that I realized there are a bunch of definitions from that file missing as well.

This is the header I am referring to: https://github.com/torvalds/linux/blob/master/include/uapi/linux/netfilter/nf_tables.h

This is where the definitions are: https://github.com/rust-lang/libc/blob/ad75ba1f261a33d118d61c066818b60efc1fa6fe/src/unix/linux_like/linux/mod.rs#L4034

If this is just a matter of adding the missing definitions, I'd be happy to do it. Let me know.

**Comment by devnexen** [comment]
Feel free I would say !
