### ISSUE TITLE
Assorted libc-test failures

### ISSUE THREAD

**Issue by japaric** [rust-lang/libc#357]
### UPDATE (2016-11-16)

I'm now using (or rather will soon be using) the "one Dockerfile per target" that this repo uses in my smoke repo. See japaric/smoke#32.

I'm now seeing the following errors:

Disclaimer: These builds are **8 days old**

- powerpc64le-unknown-linux-gnu. [gcc error](https://travis-ci.org/japaric/smoke/jobs/174115144#L922). I think libc is not testing this target.

- x86_64-unknown-linux-musl. [gcc error](https://travis-ci.org/japaric/smoke/jobs/174115150#L819). Not sure about this one, are we using a different musl version?

All the issues below seem to have been solved.

---

I've been testing, with the help of QEMU, Rust cross compilation targets in [this repository](https://github.com/japaric/smoke) (look [ma test matrix!](https://travis-ci.org/japaric/smoke)). One of tests I'm running is libc-test. I've seen some failures so I figured I should report them here:
- [mips-unknown-linux-musl](https://travis-ci.org/japaric/smoke/jobs/152709759#L464) and [mipsel-unknown-linux-musl](https://travis-ci.org/japaric/smoke/jobs/152709762#L464). These targets have legit failures due   to wrong bindings and bad constants.
- [aarch64-unknown-linux-gnu](https://travis-ci.org/japaric/smoke/jobs/152709764#L477) and [powerpc64-unknown-linux-gnu](https://travis-ci.org/japaric/smoke/jobs/152709775#L480). "error: return from incompatible   pointer type [-Werror=incompatible-pointer-types]". The aarch target passes its test in this   repository CI, which uses Ubuntu 14.04 (my repository CI uses 16.04). Perhaps is just an innocuous warning that's enabled in gcc-5 but not in gcc-4. UPDATE: This is the same as #231
- [i586-unknown-linux-gnu](https://travis-ci.org/japaric/smoke/jobs/152709770#L423). Seems like ctest doesn't handle the i586 component. But I suppose its definitions must match i686's so there isn't much to test here anyway.
- [powerpc-unknown-linux-gnu](https://travis-ci.org/japaric/smoke/jobs/152583323#L503). Looks like a legit C compilation error.

cc @alexcrichton

**Comment by alexcrichton** [comment]
Holy cow that is quite the matrix! We've currently got a dockerfile-per-target, so it should be quite easy to add new targets to being tested here. I'd love to get CI up and running for everything here! (nothing is omitted intentionally)

**Comment by japaric** [comment]
I'm using a single docker image (Dockerfile [here](https://github.com/japaric/docker/tree/master/rustc-builtins)) to run all these. Perhaps we can use that image or create one based on it under the rust-lang organization name. (I'm not sure what's the policy on depending on Docker images not owned by the rust-lang organization) When I get the time, I'll see how to integrate my CI scripts with the ones here.

**Comment by alexcrichton** [comment]
Sounds good to me! I've just preferred lately to have a single target per docker image because it's easy enough to see how to compose them together and otherwise it cuts down the cycle time when debugging one particular target.

**Comment by japaric** [comment]
I see you forked my docker repository. I want to document one trick I'm using, in case you are
playing with the docker image or thinking about creating a similar one:

- Do not install QEMU on the docker *image*.
- Instead install `qemu-user-static` and `binfmt-support` in a **privileged** docker *container*
  (`docker run --privileged ..`).
- This will let you transparently run "foreign" binaries on the container. IOW, you will be able to directly
  run   `./arm-binary` or `cargo test --target arm-unknown-linux-gnueabi`; Instead of having to call
  `cargo test --target arm-unknown-linux-gnueabi --no-run && qemu-arm
  target/debug/arm-unknown-linux-gnueabi/some_test-$HASH`. Note that you still have to set QEMU_LD_PREFIX in both cases.

**Comment by alexcrichton** [comment]
I think we're now testing all these targets, @japaric are there still remaining issues though?

**Comment by japaric** [comment]
@alexcrichton Everything in my original report seems to be fixed now. I've updated the top comment with two errors I saw in a *8 days old* smoke run.

**Comment by alexcrichton** [comment]
Ah yeah for musl we're [installing 1.15](https://github.com/rust-lang/libc/blob/a3baaf6a9562ac9a37d03807cdbc15cba5fc34fb/ci/docker/x86_64-unknown-linux-musl/Dockerfile#L6) where [you're using 1.9](https://travis-ci.org/japaric/smoke/jobs/174115150#L458) I believe. Those errors are likely benign.

Also holy cow I swear if powerpc64 and powerpc64le are different in terms of APIs I'm going to flip a table. I'll make a PR adding it to this repo though.

**Comment by alexcrichton** [comment]
Turns out powerpc64le was a [bug in ctest](https://github.com/alexcrichton/ctest/commit/d5aac516d895556d652c15134ba1ad6cec5e38be). In light of that sounds like we can close!

**Comment by japaric** [comment]
> Turns out powerpc64le was a bug in ctest.

:+1: The tables are safe!
