### ISSUE TITLE
Require support for inet_* API

### ISSUE THREAD

**Issue by devendranaga** [rust-lang/libc#3595]
Hi,

I am using libc for writing systems programming interface for a project i am working on.

I find the lack of following very useful functions for network programming.

1. `inet_ntoa`.
2. `inet_aton`.
3. `inet_addr`.

Are there any plans to add these?

my current Test system is Linux Fedora.

Thanks,
Dev

**Comment by devnexen** [comment]
well, those are outdated, coming with their shortcomings (e.g. ipv4 only).

**Comment by devendranaga** [comment]
Ok. I am mostly interested in ipv4 ones specifically. IPv4 is not going anywhere too. 

Is it possible to provide support for those ? if not, can you please suggest alternatives?

thanks.

**Comment by devnexen** [comment]
If you really want to avoid newer api inet_ntop and the rest, you can always add this in an appropriate place in your project

```rust
extern "C" {
        pub fn inet_aton(cp: *const libc::c_char, inp: *mut libc::in_addr) -> libc::c_int;
        pub fn inet_addr(cp: *const libc::c_char) -> libc::in_addr_t;
        pub fn inet_ntoa(inp: libc::in_addr) -> *mut libc::c_char;
    }
```

**Comment by devendranaga** [comment]
> ```rust
> extern "C" {
>         pub fn inet_aton(cp: *const libc::c_char, inp: *mut libc::in_addr) -> libc::c_int;
>         pub fn inet_addr(cp: *const libc::c_char) -> libc::in_addr_t;
>         pub fn inet_ntoa(inp: libc::in_addr) -> *mut libc::c_char;
>     }
> ```

This works !

Thank you very much for your help. I appreciate it very much.
