### ISSUE TITLE
Inconsistency in definition of c_char

### ISSUE THREAD

**Issue by GuillaumeLestringant** [rust-lang/libc#362]
I just noticed that `c_char` is defined as `u8` on:

- Android
- Linux musl ARM
- Linux other ARM
- Linux other AArch64

… but as `i8` on Linux musl AArch64.

There might be a good reason for it, but that looks like an inconsistency to me.

**Comment by alexcrichton** [comment]
Thanks for the report! On ARM, though [`char` is unsinged](http://blog.cdleary.com/2012/11/arm-chars-are-unsigned-by-default/), so this is just reflecting the state of the world in C. It's a bit unfortunate, but this crate is intended to represent the corresponding C compiler for a platform exactly, so we don't have much of a choice here :(

**Comment by GuillaumeLestringant** [comment]
Either you have read my message too quickly or I have not been clear enough…

The problem here is that Linux musl AArch64 is using *signed* chars, although, as you pointed it yourself, they are supposed to be *unsigned*. :wink:

**Comment by alexcrichton** [comment]
Oh oops, sorry! I did indeed misread...

Yes currently the aarch64 musl target is not tested, so it likely has a few more bugs beyond this as well.
