### ISSUE TITLE
Libc-test fails on linux due to Undeclared symbols Elf32_Relr and Elf64_Relr

### ISSUE THREAD

**Issue by biabbas** [rust-lang/libc#3641]
`cargo test -p libc-test` fails on linux. 

I've attached `cargo test -p libc-test`
The libc-test work on windows. For linux and mac, they fail.
On linux rust version = 1.79 nightly. 
[libc-test-p_linux_rust_179.txt](https://github.com/rust-lang/libc/files/14820415/libc-test-p_linux_rust_179.txt)
On windows rust version = 1.75 stable.
It ran 753  tests in tests/makedev.rs and all of them passed.
[libc-test-pwindowspass.txt](https://github.com/rust-lang/libc/files/14820416/libc-test-pwindowspass.txt)

**Comment by biabbas** [comment]
How to link cargo test executable to external libraries used in tests?

**Comment by safinaskar** [comment]
`libc-test` works in recent debian sid. I suggest running in recent Linux, for example, inside Docker

**Comment by biabbas** [comment]
@safinaskar Please share the info on C library that you are using, the Debian OS version info, along with the libc test log.

**Comment by Amanieu** [comment]
Generally speaking, the libc tests will only pass on the specific linux release that we use in our docker containers. If you run the test with `run-docker.sh` then they should all pass.

**Comment by biabbas** [comment]
@Amanieu David @devnexen created a PR removing Elf32relr and Elf64relr tests for all systems including linux. Libc -tests work on linux after that.
