### ISSUE TITLE
Add IPV6_DONTFRAG socket option on OpenBSD

### ISSUE THREAD

**Issue by flub** [rust-lang/libc#3704]
* target triple: x86_64-unknown-openbsd
* Header file: https://github.com/openbsd/src/blob/35659bf2453d7eeb12fd24089cf668ca13361c18/sys/netinet6/in6.h#L330C9-L330C24

According to the git history this symbol has been there for a very long time, so there is probably no need to check the openbsd version.

**Comment by devnexen** [comment]
You re in the luck, seems [it is already there](https://github.com/rust-lang/libc/blob/libc-0.2/src/unix/bsd/netbsdlike/mod.rs#L504).

**Comment by flub** [comment]
Huh, totally true.  I'm afraid I mixed up the symbol, I am looking for IPV6_DONTFRAG:

https://github.com/openbsd/src/blob/35659bf2453d7eeb12fd24089cf668ca13361c18/sys/netinet6/in6.h#L336

Also has been there since forever in OpenBSD, but I don't think is defined by the libc crate.

**Comment by tgross35** [comment]
This should have been closed by https://github.com/rust-lang/libc/pull/3716.
