### ISSUE TITLE
`ifa_flags` is `uint_64` on Solaris/illumos

### ISSUE THREAD

**Issue by mtelka** [rust-lang/libc#3726]
The `ifa_flags` is declared as `c_ulong` [here for solarish](https://github.com/rust-lang/libc/blob/acc7bb1a38e2b9d6a18f28279d80d464c4c25089/src/unix/solarish/mod.rs#L138), but actually in both Solaris and illumos it is `uint_64`:

- https://illumos.org/man/3SOCKET/getifaddrs
- https://docs.oracle.com/cd/E88353_01/html/E37843/getifaddrs-3c.html

I think the type of `ifa_flags` should be changed to `u64` here.

This issue was found during the [illumos support fix work for GStreamer](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3553).

**Comment by devnexen** [comment]
If you feel like it, you can create a PR targeting libc-0.2 for starter.

**Comment by mtelka** [comment]
Why not `main` first?
