### ISSUE TITLE
Hostname on xtensa esp-idf esp32s3

### ISSUE THREAD

**Issue by lorenzo-pirchio** [rust-lang/libc#3748]
Hi, 
I need to use hostname_max and the function gethostname for xtensa-esp32s3-espidf but they're not supported for this target.
Can anyone give me any suggestion or help?
Thanks

**Comment by tgross35** [comment]
PRs are welcome here! Take a look at https://github.com/rust-lang/libc/blob/1ffe0bde929a43ce3d25a8f08b9f95bde8d3e5d8/CONTRIBUTING.md, it should be pretty easy to add the API on those platforms.

**Comment by Vollbrecht** [comment]
There is no written guide for this target specifically that i am aware off. Though the target ( and all other `-espidf` targets ) are using a version of `newlib` that is directly integrated in the underlying esp-idf system. Depending on the version of the `esp chip` there are parts of this newlib library directly inside the ROM.

[Here](https://github.com/espressif/esp-idf/tree/v5.2.2/components/newlib) you can find the in tree version of newlib that is used in ESP_IDF version 5.2.2. 

What actually lives inside the ROM's is tracked inside this [repository](https://github.com/espressif/newlib-esp32) 

We have one [outstanding](https://github.com/rust-lang/libc/pull/3920) PR that does a bit of cleanup inside libc with respect to correct constants. There you see for example how the rust libc site and the esp_idf site can be checked against each other. 

If you have any target specific questions all the maintainers are also available in our `esp-rs` matrix channel  found [here](https://matrix.to/#/#esp-rs:matrix.org)
