### ISSUE TITLE
pub extern fn functions without #[no_mangle]

### ISSUE THREAD

**Issue by pornel** [rust-lang/libc#376]
[src/unix/bsd/apple/mod.rs](https://github.com/rust-lang/libc/blob/955aa6d7ab71f732109bf58c87891e95ae39a090/src/unix/bsd/apple/mod.rs#L1301) defines functions that look like replacements for POSIX macros:

```
    pub fn WSTOPSIG(status: ::c_int) -> ::c_int {
        status >> 8
    }
```

`macro_rules! f` makes these functions `pub unsafe extern fn`, but does *not* add `#[no_mangle]`, which makes them not callable from C under these names.

Is lack of C-compatible names intentional?

**Comment by alexcrichton** [comment]
This is indeed intentional! This crate doesn't have a C ABI, it's just intends the Rust interface to look like a C header file basically.

**Comment by comex** [comment]
Does this actually need to be extern?

**Comment by alexcrichton** [comment]
As far as I know, no
