### ISSUE TITLE
preadv2 is not supported on musl libc

### ISSUE THREAD

**Issue by NobodyXu** [rust-lang/libc#3760]
The preadv2 function is present on -gnu target, however when compiling on -musl target, which is surprising.

The jobserver-rs would like to use it to optimize it's performance rust-lang/jobserver-rs#90 (the try_acquire optimization has shipped once but reverted, so I opened another PR to use raw syscall directly).

FYI, my motivation is to that this API is used in cc-rs to improve performance.

**Comment by faptc** [comment]
closed by #3762

**Comment by NobodyXu** [comment]
Thank you!
