### ISSUE TITLE
Missing kill function in libc on Windows

### ISSUE THREAD

**Issue by chuacw** [rust-lang/libc#3763]
The kill function is missing in libc on Windows

**Comment by devnexen** [comment]
I did not find it in MSDN.

**Comment by chuacw** [comment]
The implementation is missing in libc's implementation on Windows.

**Comment by faptc** [comment]
There is no corresponding kill functions on Windows MSVC libc. Windows OS doesn't exposing every libc C99 functions like Unix's.

**Comment by chuacw** [comment]
The initial PR used a different signature than expected because of styling issues that causes a ci failure when I used the same signature. It has now been fixed.

The added kill function is to provide parity with the existing kill function and usage on other platforms.

Thanks.

**Comment by ChrisDenton** [comment]
[Scope of libc](https://github.com/rust-lang/rfcs/blob/HEAD/text/1291-promote-libc.md#scope-of-libc) states that this crate wraps "VS CRT libraries" and is "distinct from the winapi crate as well as bindings to common system DLLs found on Windows".

Therefore we should not be depending on winapi nor duplicating their bindings.

**Comment by chuacw** [comment]
See also point 3 [Unresolved questions](https://github.com/rust-lang/rfcs/blob/HEAD/text/1291-promote-libc.md#unresolved-questions)

**Comment by faptc** [comment]
Even if it is a yes, then only bare Win32 APIs will be exposed, not compositions/emulations of them.

**Comment by tgross35** [comment]
Thank you for the enthusiasm here. However, as pointed out, this crate only provides bindings to system libraries (and some very minimal functions that reimplement C macros). It is even a bit lower level than `windows`, which makes use of Rust features to provide a much more user-friendly API.

A crate that provides a POSIX API for Windows is a very interesting idea; this just isn't the place for it (something like a fork of [`nix`](https://docs.rs/nix/latest/nix/) that supports Windows would be cool).
