### ISSUE TITLE
The getppid function is missing on Windows

### ISSUE THREAD

**Issue by chuacw** [rust-lang/libc#3765]
The getppid  function is missing on Windows

**Comment by devnexen** [comment]
I am afraid it s a bigger no than your previous feature request. To get a proper implementation, it will require more work than your kill wrapper, regardless does not have its place here.

**Comment by tgross35** [comment]
I don't think this is a bug since it is just missing API. PRs are welcome if you are able to add it :)

**Comment by ChrisDenton** [comment]
This issue is this simply doesn't exist on Windows. It would need to be implemented from scratch, which is not something this crate does.

**Comment by tgross35** [comment]
Thanks Chris, I guess there isn't much we can do here then.
