### ISSUE TITLE
update the openbsd image for testing

### ISSUE THREAD

**Issue by semarie** [rust-lang/libc#380]
The OpenBSD image is 5.8 release. This release isn't supported anymore by OpenBSD.

The image should be updated to 6.0.

OpenBSD 6.0 has the following ports (installed using pkg_add):
  - rustc 1.9.0
  - cargo 0.10.0

**Comment by alexcrichton** [comment]
The [instructions here](https://github.com/rust-lang/libc/tree/master/ci#qemu-setup---openbsd) should be good for generating a new image. @semarie would you be interested in trying to give this a go?

**Comment by semarie** [comment]
@alexcrichton I will take a shot at it. Thanks.

**Comment by semarie** [comment]
I have build two qcow2 images:
  - one just like the current one (without any packages installed): 241M
  - one with cargo+rust+gcc pre-installed: 405M

The images are qcow2 with compression (using `qemu-img convert -c`). So don't expect any size reduction with additionnal gzip layer.

Even if the second is larger, I think it is better to not relying to external source for installing rust and cargo at testing time. What do you think ?

**Comment by alexcrichton** [comment]
Awesome, thanks! I think yeah I'd prefer to stick to installing Rust at travis-test time as that's what all the other targets do, but if it becomes a hassle perhaps we can update the image? I can go ahead and upload both images to where I'm hosting the other, want to send me the links?

**Comment by posborne** [comment]
@semarie Where are these images located?  I've been looking at adding BSD as a test target for nix.  Our test system is based on libc from a little while back and modified a bit, but I'm considering making them more similar again.

**Comment by semarie** [comment]
Images are (temporary) located at:
  - http://semarie.free.fr/stuff/openbsd-6.0-with-pkgs.qcow2 (405M)
  - http://semarie.free.fr/stuff/openbsd-6.0-without-pkgs.qcow2 (241M)

(note the second is still uploading)

**Comment by alexcrichton** [comment]
Ok I've hosted them here now: http://people.mozilla.org/~acrichton/libc-test/qemu/2016-09-07/

@semarie do you want to send a PR to update to using those imagse?

**Comment by semarie** [comment]
closed by #384
