### ISSUE TITLE
Uncommenting SO_PREFER_BUSY_POLL and SO_BUSY_POLL_BUDGET

### ISSUE THREAD

**Issue by tammela** [rust-lang/libc#3896]
I'm interested in these socket options which are commented out:
https://docs.rs/libc/latest/src/libc/unix/linux_like/linux/arch/generic/mod.rs.html#109

Digging through the git history and issues I did not see any specific issue with these constants when they were added:
https://github.com/rust-lang/libc/pull/2135

Is there any blocker for adding them?

**Comment by devnexen** [comment]
It might be because of CI not passing at the time ? if that s still the case now, it s better to put an exception libc-test/build.rs instead.

**Comment by tammela** [comment]
Opened https://github.com/rust-lang/libc/pull/3917
Let's see if CI complains
