### ISSUE TITLE
Move away from 2015 edition?

### ISSUE THREAD

**Issue by eduardosm** [rust-lang/libc#3898]
Right now, the libc crate is at Rust edition 2015. Is there a desire to bump to a newer edition?

That would require a significant amount of changes, such as adding `crate` to paths that being with `::` (e.g., `crate::c_int` instead of `::c_int`). It would also require types inside an `union` to be `Copy` or wrapped in a `ManuallyDrop`.

**Comment by tgross35** [comment]
Yeah, we should probably target 2021 as part of 1.0. Thanks for writing this up, I have been meaning to for a while but never got to it.

**Comment by ChrisDenton** [comment]
Note that doing this may make some backports more involved.

**Comment by eduardosm** [comment]
It looks like https://github.com/JohnTitor/ctest2/issues/48 blocks this.

**Comment by tgross35** [comment]
@ChrisDenton are you just referring to maintaining both 1.0 and 0.2 at the same time like we do currently? We have a handful of planned changes like this that would make backports worse, it would probably be good to get everything else lined up then do them right before we plan to release 1.0.

**Comment by ChrisDenton** [comment]
> are you just referring to maintaining both 1.0 and 0.2 at the same time like we do currently?

Yes, that's what I was referring to.

> We have a handful of planned changes like this that would make backports worse, it would probably be good to get everything else lined up then do them right before we plan to release 1.0.

Makes sense.

**Comment by ismailarilik** [comment]
I have tried to migrate it to 2021 using `cargo fix --edition`, and `cargo build` is now working with the edition set to 2021 in Cargo.toml. Isn't this that simple?

**Comment by tgross35** [comment]
We cherry pick commits from `main` to `libc-0.2` for the stable release. Doing a lot of tiny changes from the autofix means that these many cherry picks won't apply as cleanly, which would be a huge annoyance - since doing this change is so easy/automated, we can defer it until we get closer to 1.0.

**Comment by tgross35** [comment]
We upgraded the MSRV of 0.2 to 1.63, meaning that both `main` and `libc-0.2` can use edition 2021. If anyone would like to put up a PR making this change, that would be welcome!

**Comment by eduardosm** [comment]
Completed in https://github.com/rust-lang/libc/pull/4132 and https://github.com/rust-lang/libc/pull/4155.
