### ISSUE TITLE
`CLONE_CLEAR_SIGHAND` and `CLONE_INTO_CGROUP` overflow `c_int`

### ISSUE THREAD

**Issue by ruihe774** [rust-lang/libc#3955]
```rust
pub const CLONE_CLEAR_SIGHAND: ::c_int = 0x100000000;
pub const CLONE_INTO_CGROUP: ::c_int = 0x200000000;
```

Their values are beyond the range of `c_int`.

**Comment by ChrisDenton** [comment]
This is fixed on the main branch but can't be fixed in the 2.* branch because it's a breaking change. See https://github.com/rust-lang/libc/pull/3585
