### ISSUE TITLE
`libc` crate tests do not run (or even compile) on linux targets in CI

### ISSUE THREAD

**Issue by tamird** [rust-lang/libc#4149]
https://github.com/rust-lang/libc/pull/1536 added the ability to mark functions as const, along with a test in https://github.com/rust-lang/libc/blob/42e5708d3c0cfcf68f6ffea45eed7e1732dbd7ec/tests/const_fn.rs. Unfortunately this file is completely dead due to the combination of `#[cfg(target_os = "linux")]` in it and the behavior introduced in 3eb4a48b1b63909a8898aa37b5f610a63d776f4d which skips building the libc crate when `docker: true`, which [is the case for all linuxes](https://github.com/rust-lang/libc/blob/42e5708d3c0cfcf68f6ffea45eed7e1732dbd7ec/.github/workflows/ci.yaml#L52-L57).

This all culminated in the fact that https://github.com/rust-lang/libc/pull/4105 broke const functions and https://github.com/rust-lang/libc/pull/4134 failed to fix it in the `--no-default-features` case. This remains broken.

@tgross35 

EDIT: all releases after 0.2.163 which do not contain a fix for this should be yanked.

**Comment by tgross35** [comment]
Your `--no-default-features` configuration is not covered, but isn't this test being run by https://github.com/rust-lang/libc/blob/42e5708d3c0cfcf68f6ffea45eed7e1732dbd7ec/ci/run.sh#L83-L92?

**Comment by tamird** [comment]
No, it is not, because of `exec`: https://github.com/rust-lang/libc/blob/42e5708d3c0cfcf68f6ffea45eed7e1732dbd7ec/ci/run.sh#L80

**Comment by tgross35** [comment]
The branch with `exec` would only be executed when `QEMU` is set, which shouldn't be the case for anything x86 (though a command followed by `exit` is better style than relying on `exec`). I also don't think `QEMU` is set for any of the qemu-system tests, since those were failing when I added the test branch.

**Comment by tamird** [comment]
> The branch with `exec` would only be executed when `QEMU` is set, which shouldn't be the case for anything x86 (though a command followed by `exit` is better style than relying on `exec`, and that grep seems fragile). I also don't think `QEMU` is set for any of the qemu-system tests, since those were failing when I added the test branch.

Yes, I think you're right.

> `$cmd` is not the same at lines 91 and 123, it gains `--manifest-path libc-test/Cargo.toml` in between. This should probably just be `--all` on platforms where unit tests can run successfully.

Right, I paged this out. Either that or we shouldn't have tests in the libc crate. The situation today is quite inconsistent. Note that `--all` is a deprecated alias for `--workspace`.

**Comment by tgross35** [comment]
Released in 0.2.166 https://github.com/rust-lang/libc/releases/tag/0.2.166
