### ISSUE TITLE
openpty last paremeter mutability inconsistency

### ISSUE THREAD

**Issue by meh** [rust-lang/libc#447]
On Linux the last parameter is `*const ::winsize`, on BSDs it's `*mut ::winsize`.

Is this difference intended? It makes it a little awkward to support both.

**Comment by alexcrichton** [comment]
Unfortunately these are just mirroring the APIs actually present on the system, so there's not much libc can do about inevitable differences between platforms. Luckily in Rust a `*mut T` will coerce to a `*const T` I believe.

**Comment by meh** [comment]
Yeah, it does, I just thought it was weird when I went to build on macOS and had that compilation error, thanks.
