### ISSUE TITLE
struct sigstack changed from FreeBSD 10 to 11

### ISSUE THREAD

**Issue by asomers** [rust-lang/libc#450]
In FreeBSD 10, `sigstack.ss_sp` was a `char*`.  In 11, it's a `void*`.  The libc-test program requires all fields to have the correct type.  That means that libc can't pass its tests on both FreeBSD 10 and FreeBSD 11.  The only way to pass would be to remove that structure, and the `sigaltstack` function along with it.  What is libc's plan for supporting multiple versions of an OS?  IMHO an autoconf-like system that dynamically builds the bindings would be nice; it would also reduce the effort required to support additional OSes.

> running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-fPIC" "-Wall" "-Wextra" "-Werror" "-Wno-unused-parameter" "-Wno-type-limits" "-Wno-deprecated-declarations" "-o" "/usr/home/somers/src/rust/libc/libc-test/target/debug/build/libc-test-b3343f7e85468f61/out/all.o" "-c" "/usr/home/somers/src/rust/libc/libc-test/target/debug/build/libc-test-b3343f7e85468f61/out/all.c"
> cargo:warning=/usr/home/somers/src/rust/libc/libc-test/target/debug/build/libc-test-b3343f7e85468f61/out/all.c:5508:28: error: incompatible pointer types returning 'void **' from a function with result type 'char **' [-Werror,-Wincompatible-pointer-types]
> cargo:warning=                    return &b->ss_sp;
> cargo:warning=                           ^~~~~~~~~
> cargo:warning=1 error generated.

https://svnweb.freebsd.org/base?view=revision&revision=294930

**Comment by asomers** [comment]
I just learned how to mask such errors with libc-test/build.rs.  I guess that's the best solution for now.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/libc/pull/451
