### ISSUE TITLE
Remove obsolete constants in version 1.0.0

### ISSUE THREAD

**Issue by asomers** [rust-lang/libc#454]
This issue tracks constants that should be removed from libc for release 1.0.0.  

The following are absent in FreeBSD 11, never had stable values across versions, and should never have been used by third party software.  They should be removed from FreeBSD.
```
CTL_MAXID
KERN_MAXID
HW_MAXID
USER_MAXID
```
The following is still present in FreeBSD 11, but like the previous four it should never have been used by third party software, and its value isn't guaranteed to be stable across versions.  It should be removed from FreeBSD
`CTL_P1003_1B_MAXID`

**Comment by asomers** [comment]
Add to the list `AIO_LISTIO_MAX`.  That symbol should never be used because the quantity it represents can potentially vary at runtime.  Programs should use sysconf(3) instead.

**Comment by gnzlbg** [comment]
I've deprecated these on master, and they are also `doc(hidden)`. I'd say that we'd remove them in one of the next releases.

**Comment by asomers** [comment]
I agree.

**Comment by gnzlbg** [comment]
Feel free to open a PR removing these.
