### ISSUE TITLE
Some conversion implementations

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/libc#469]
I know you want to keep this crate thin, but why not implement things like `impl From<Ipv4Addr> for in_addr`?

**Comment by alexcrichton** [comment]
Right now the API of this crate is defined by [RFC 1291](https://github.com/rust-lang/rfcs/blob/master/text/1291-promote-libc.md), and the intention is to just be a very small wrapper around the underlying system APIs, avoiding conversions and interactions with the standard library where possible.

Thanks for the report though!
