### ISSUE TITLE
type c_void = std::os::raw::c_void

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/libc#470]
Currently, the types in `std::os::raw` are duplicated in `libc`, so the compiler thinks they are different. If `libc` pointed to `std::os::raw`, they could be used interchangeably.

**Comment by alexcrichton** [comment]
The public types in `std::os::raw` are likely slated for deprecation/deletion at some point (is at least my personal desire), so I'd prefer to hold off on this.

**Comment by Yamakaky** [comment]
Ok
