### ISSUE TITLE
Can't create in6_addr

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/libc#471]
There is a private `__align` field, so we can't create it.
https://doc.rust-lang.org/libc/x86_64-unknown-linux-gnu/libc/struct.in6_addr.html

**Comment by alexcrichton** [comment]
Thanks for the report! This has also been reported [here](https://github.com/rust-lang-nursery/libc/issues/55) and [here](https://github.com/rust-lang-nursery/libc/issues/41), and unfortunately this is just a place where Rust hasn't historically handled FFI unions very well right now. The underlying type is a union which gains it higher alignment but the exposed fields right now don't give us that alignment. When we have custom alignment we may be able to get around this via other means, but for now you can construct this like you would in C:

``` rust
let mut foo: libc::in6_addr = mem::uninitialized();
// initialize foo.s6_addr
return foo
```

Which is to say it's not necessarily "impossible", just not very idiomatic!

**Comment by Yamakaky** [comment]
Oh, OK. Maybe add it in the doc? You could also add a method for that.

**Comment by alexcrichton** [comment]
Perhaps some general documentation, yes, but I don't think it's particularly necessary to document each and every structure in libc
