### ISSUE TITLE
Error message could be better if home directory isn't found (because it doesn't exist)

### ISSUE THREAD

**Issue by daym** [rust-lang/libc#486]
```
$ cd libc-test && cargo run
error: An unknown error occurred

To learn more, run the command again with --verbose.
```

What does it mean? :)

```
$ cd libc-test && cargo run --verbose
error: Permission denied (os error 13)
```

Errr... yes? Where?

strace reveals that it's because it can't find the user's home directory (because there's none in the chroot). Setting the environment variable "CARGO_HOME" or creating a ".cargo" directory makes the error go away.

But it would be nice if it also printed the filename.

**Comment by alexcrichton** [comment]
This seems like a Cargo issue? Can you use strace to figure it out?

**Comment by daym** [comment]
It? What do you mean?

It's working now. This was just a heads-up about it so that the error message doesn't stay that mysterious forever.

**Comment by alexcrichton** [comment]
@daym it seems that a phantom comment may have come in? Is it working now? I was thinking of using `strace` to figure out the filename.

**Comment by alexcrichton** [comment]
I'm going to close this as I think this isn't an issue for libc
