### ISSUE TITLE
posix: fchdir() seems to be missing

### ISSUE THREAD

**Issue by lucab** [rust-lang/libc#495]
I have some linux-related code which needs to escape a chroot, and the most ergonomic way of doing that is via POSIX [fchdir()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fchdir.html). 

I was expecting to see it defined here, however I see no reference to that. Has it been omitted for some reasons? Otherwise, can it just be exposed by libc please?

**Comment by alexcrichton** [comment]
Ah yes nothing is ever explicitly omitted from libc, it's all just awaiting a PR!

**Comment by lucab** [comment]
I see. Followed-up at https://github.com/rust-lang/libc/pull/496.
