### ISSUE TITLE
support pipe2 on BSD

### ISSUE THREAD

**Issue by oconnor663** [rust-lang/libc#500]
Right now it's only available in the `notbsd` subtree, but it looks like the BSD's support it?

https://www.freebsd.org/cgi/man.cgi?query=pipe&sektion=2
http://netbsd.gw.com/cgi-bin/man-cgi?pipe2+2+NetBSD-current
http://man.openbsd.org/pipe.2

I might try moving it up to `src/unix/mod.rs` in a PR just to see what happens. Maybe Apple doesn't support it? Let me know if there's an easy way to figure this out without just seeing what breaks :)

**Comment by oconnor663** [comment]
Yep, it breaks on OSX. Would the right thing to do be to individually add it to the other BSD flavors?

**Comment by oconnor663** [comment]
Related question: `nix` currently hardcodes the platforms that support this call, https://github.com/nix-rust/nix/blob/master/src/unistd.rs#L617-L619. If we add more platforms, `nix` will want to update those lines. Is there a way for `nix` to avoid this kind of hardcoding?

**Comment by alexcrichton** [comment]
AFAIK there's no way to avoid hardcoding down the road, but yeah you can just add it to the BSD modules

**Comment by oconnor663** [comment]
Closing since #502 has landed.
