### ISSUE TITLE
Missing WIFCONTINUED on FreeBSD

### ISSUE THREAD

**Issue by radupopescu** [rust-lang/libc#505]
Hello,

I think the `WIFCONTINUED` function is missing from `libc` on FreeBSD.
I am running:
* FreeBSD 11.0-RELEASE-p1
* rustc 1.14.0 (e8a012324 2016-12-16) with target `x86_64-unknown-freebsd`
* cargo 0.15.0-nightly (298a012 2016-12-20)
* libc 0.2.20

**Comment by alexcrichton** [comment]
Constants like this are never explicitly omitted or anything like that, so a PR to add them is always welcome!

**Comment by radupopescu** [comment]
Right. I just wanted to make sure that there's no specific reason this isn't implemented on FreeBSD.

**Comment by radupopescu** [comment]
Closing as this was fixed in #507 .
