### ISSUE TITLE
upload libc-test to crates.io

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang/libc#509]
Apparently it breaks `cargo metadata` when using archive from crates.io...

See https://github.com/rust-lang/cargo/issues/3642

**Comment by alexcrichton** [comment]
I commented over on Cargo (https://github.com/rust-lang/cargo/issues/3642#issuecomment-277312348) but the tl;dr; is that this is intentional and shouldn't be necessary because crate files from crates.io cannot be consumed directly but only indirectly through Cargo
