### ISSUE TITLE
Linking liblibc with musl target fails with the new nightlies

### ISSUE THREAD

**Issue by golddranks** [rust-lang/libc#529]
Not sure if this belongs in the Rust repo issues or here, but anyway.
When building with `nightly-2017-02-19` (on a Linux host) and with target `x86_64-unknown-linux-musl`, the error message is as following:
```
  = note: /usr/bin/ld: /root/.rustup/toolchains/nightly-2017-02-19-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/liblibc-95af4192ed69a1c8.rlib(exit.lo): unrecognized relocation (0x2a) in section `.text.libc_exit_fini'
          /usr/bin/ld: final link failed: Bad value
          collect2: error: ld returned 1 exit status
```

With `nightly-2017-02-13` it builds without problems.

**Comment by BurntSushi** [comment]
I've also recently been seeing weird things, although it's not the same error message, so I'm not sure if it's related:

```
  = note: /usr/bin/ld: BFD (GNU Binutils for Ubuntu) 2.22 internal error, aborting at ../../bfd/reloc.c line 443 in bfd_get_reloc_size
          
          /usr/bin/ld: Please report this bug.
          
          collect2: ld returned 1 exit status
```

See: https://travis-ci.org/BurntSushi/ripgrep/jobs/203183624

**Comment by golddranks** [comment]
Trying to pinpoint which nightly breaks it. `2016-02-17` has this error too. Trying `2016-02-16` ATM.

**Comment by golddranks** [comment]
So, `nightly-2017-02-16 installed - rustc 1.17.0-nightly (62eb6056d 2017-02-15)` breaks too. `2017-02-15` and `2017-02-14` don't have releases, so that makes `nightly-2017-02-13 installed - rustc 1.17.0-nightly (956e2bcba 2017-02-12)` the last working release.

**Comment by golddranks** [comment]
Here's a minified, dockerized regression test that doesn't compile. https://github.com/golddranks/libc_regression_test/ The README claims that `libc` is tested against `x86_64-unknown-linux-musl` but maybe that's not the nightlies? Because I'm unable to find such a test, checked the Travis suite.

**Comment by alexcrichton** [comment]
I believe this is not the fault of libc itself, but rather the way we distribute binaries, so closing in favor of https://github.com/rust-lang/rust/issues/39979

(I'll investigate soon)

**Comment by BurntSushi** [comment]
Thanks @alexcrichton :-)
