### ISSUE TITLE
Make a release :-)

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang/libc#539]
It's been about a month and about 20 pull requests:

https://github.com/rust-lang/libc/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged%20merged%3A%3E2017-01-17%20

**Comment by alexcrichton** [comment]
Sounds good to me! Want to send a PR w/ a version bump? Once it merges I'll tag/publish

**Comment by malbarbo** [comment]
It would be great if https://github.com/rust-lang/libc/pull/538 could be included.

**Comment by kamalmarhubi** [comment]
@malbarbo sure, will wait for it to get merged

**Comment by malbarbo** [comment]
@alexcrichton How about a new release? The last release was more than 50 day ago and there is [23](https://github.com/rust-lang/libc/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged%20merged%3A%3E2017-03-01) new commits since then.

**Comment by alexcrichton** [comment]
Certainly! Bumped in https://github.com/rust-lang/libc/pull/583

**Comment by alexcrichton** [comment]
Ok published!

**Comment by malbarbo** [comment]
Thanks!
