### ISSUE TITLE
Policy on new system calls?

### ISSUE THREAD

**Issue by alexander255** [rust-lang/libc#540]
I see that the `accept4` system call is currently exposed on Linux, but not on FreeBSD, OpenBSD or other system that support it. Here's the Unix compatibility story for that, IMHO quite useful, system call:

 - Linux 2.6.28+ (24.12.2008)
 - FreeBSD 10.0+ (01.02.2014)
 - OpenBSD 5.7+ (01.05.2015)
 - DragonFlyBSD 4.4+ (07.12.2015)
 - BitRig ??? (More that 3 years ago according to `git blame` on https://github.com/bitrig/bitrig/blame/master/sys/kern/syscalls.c, OTOH the BitRig 1.0 release page says it incorporates changes up to OpenBSD 5.6?, very unclear status in general IMHO…)
 - NetBSD 8.0+ (Hopefully released soonish…)
 - macOS/Darwin Nope, expected anything else?

Should these simply be submitted for any platform that supports them? Will that cause any issues for applications that target older platform?

Possibly related issues: #234

**Comment by alexcrichton** [comment]
New functions are definitely welcome! Adding them to this crate doesn't imply that they *must* be used, so it's up to downstream crates to use them or not. So in that sense PRs are definitely welcome!

**Comment by Susurrus** [comment]
Can this be closed since #546 was merged?

**Comment by alexander255** [comment]
I guess so… The policy is basically "**add whatever you want, as long as it exists in some released version of that platform**". So the opening question of this issue has indeed been answered in the process of getting the PR merged, yes.
