### ISSUE TITLE
Derive more for structs

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/libc#544]
I'd like to propose adding `#[derive(Copy, Debug, Eq, PartialEq)]` for some of the structs here in libc so they can be used downstream. This may be controversial for various reasons, but I have a specific use case for `Eq` and `Debug` on the `termios` struct. Additionally `Clone` may be worth adding also, though I don't know if that could blanket apply to all structs.

**Comment by alexcrichton** [comment]
Debug is covered by https://github.com/rust-lang/libc/issues/302 and otherwise Eq/PartialEq are left out for compile time implications. The Clone/Copy traits are already implemented for all structs.

I think we'd require an RFC for Eq/PartialEq, so I'm going to close this in favor of #302

**Comment by Susurrus** [comment]
@alexcrichton Is that an RFC as in the repo rust-lang/rfcs? I'll post on internals as a pre-RFC to get some thoughts together before I try to go down that road. I wanted to ask though, why do you think deriving `Eq` and `PartialEq` will require an RFC, is it that big of a change?

**Comment by alexcrichton** [comment]
Yeah in rust-lang/rfcs.

I personally would be against such behavior as it doesn't make sense for most types and it also has serious compile-time implications. The very few niches which require it would end up imposing a cost on all other users by increasing the compile time of this crate (b/c of so many more impls)

**Comment by Susurrus** [comment]
What about including it with #302, which I wasn't sure if you meant to suggest that earlier.

**Comment by alexcrichton** [comment]
Yes having it optional off-by-default is plausible, but I'd still want to measure the impact.
