### ISSUE TITLE
Missing implementation `libc::EPOLLONESHOT` on the android 

### ISSUE THREAD

**Issue by gdf8gdn8** [rust-lang/libc#548]
epoll EPOLLONESHOT is implemented since linux kernel 2.6.2, but on android platform EPOLLONESHOT is missing in rust libc.

Should be an bug in rust libc implementation.
Because EPOLLONESHOT is available on android platform.
see [https://doc.rust-lang.org/libc/arm-linux-androideabi/libc/index.html?search=EPOLLONESHOT](https://doc.rust-lang.org/libc/arm-linux-androideabi/libc/index.html?search=EPOLLONESHOT)

**Comment by alexcrichton** [comment]
Ah yeah if bindings aren't present that just means that they haven't been added yet, feel free to submit a PR!

**Comment by gdf8gdn8** [comment]
Which android versions are supported by rust libc?
Currently since android ndk 21 (android 5) EPOLLONESHOT is available.

**Comment by alexcrichton** [comment]
We typically use the latest when it's written down, and this can be [updated at any time](https://github.com/rust-lang/libc/blob/439a4d7d4bc86526e3765d75438edb54ae247246/ci/android-install-ndk.sh#L14-L15)
