### ISSUE TITLE
i686-linux-android libc and libstd disagree on c_char

### ISSUE THREAD

**Issue by dten** [rust-lang/libc#561]
So std lib seems to be wrong about this. but what to do? a lot of things just don't compile (looking at openssl) because of CString and CStr

libstd says that `c_char` is `u8`
https://github.com/rust-lang/rust/blob/b1363a73ede57ae595f3a1be2bb75d308ba4f7f6/src/libstd/os/raw.rs#L15

libc says that `c_char` is `i8`
https://github.com/rust-lang/libc/blob/master/src/unix/notbsd/android/b32/x86.rs#L1

**Comment by malbarbo** [comment]
This was [fixed](https://github.com/rust-lang/rust/pull/40317) when rust libc was update to 0.2.21. See https://github.com/rust-lang/rust/issues/40903.

Using rustc nightly (2017-03-29) should make your code compile.

**Comment by dten** [comment]
Such timing! I'll give it a try

**Comment by dten** [comment]
it works 👍
