### ISSUE TITLE
Reformat code with rustfmt

### ISSUE THREAD

**Issue by anatol** [rust-lang/libc#563]
Keeping consistent code formatting across Rust projects is a great thing that simplifies learning new projects and getting familiar with its codebase. `rustfmt` is a standard tool that tries to achieve it. It would be really great if Rust developers use `rustfmt` for the core projects like `libc`.

**Comment by kristate** [comment]
@anatol Thanks for your suggestion! `libc` currently has a [CI script for style validation (ci/style.rs)](https://github.com/rust-lang/libc/blob/master/ci/style.rs), but perhaps you would like to improve upon it?

**Comment by gnzlbg** [comment]
This is blocked on: https://github.com/rust-lang/rustfmt/issues/3253

**Comment by kellda** [comment]
Now rust-lang/rustfmt#3253 is closed and (when available) rustfmt is run on CI in `ci/style.sh`.

Is this issue solved ? Or should we ensure that rustfmt is always run (by using stable or a nightly with rustfmt) ?

**Comment by JohnTitor** [comment]
Closing as resolved.
