### ISSUE TITLE
Missing O_EXEC and O_SEARCH for some platforms

### ISSUE THREAD

**Issue by amosonn** [rust-lang/libc#566]
As written in the title. On some platforms, `O_ACCMODE` isn't limited just to `O_RDONLY | O_WRONLY | O_RDWR`, but has also other options, such as `O_EXEC` and `O_SEARCH`. The constants for these are currently missing from all platforms (except `O_SEARCH` on netbsd).
Looking through `O_ACCMODE`-s which are not `3`, it seems these are musl and solaris. Surprisingly, netbsd does have `O_ACCMODE = 3`.
Solaris [definitely](https://docs.oracle.com/cd/E26502_01/html/E29032/open-2.html) has both `O_EXEC` and `O_SEARCH`, musl [seems](http://www.openwall.com/lists/musl/2014/07/01/10) to have only `O_SEARCH`.

**Comment by alexcrichton** [comment]
Note that no constants are ever left out on purpose, so PRs are always welcome to fill out more!

**Comment by amosonn** [comment]
This solves Solaris.
As for musl, there's this: http://git.musl-libc.org/cgit/musl/commit/?id=fd427c4eaeed4d1099acc7b6188e41c6cfa5bca5 , so I'm not sure what's the best approach; add the constants for now, with some warning this might break someday?
For netbsd I've checked, and it's true, `O_SEARCH` really isn't part of `O_ACCMODE`.

**Comment by alexcrichton** [comment]
Yes libc changes from time to time, but in general there's typically a migration path forward for us, so it's fine to add if it's there today.

**Comment by amosonn** [comment]
Yeah, at their code this constant is platform dependant, currently the same for all platforms but the threat is that it might become really platform dependant. Anyway, added, so this should close it.

**Comment by Susurrus** [comment]
Was this resolved by #567?

**Comment by alexcrichton** [comment]
I believe so!
