### ISSUE TITLE
Why does mmap take a mutable ptr?

### ISSUE THREAD

**Issue by diekmann** [rust-lang/libc#586]
The first parameter for `mmap` is `addr: *mut c_void`. Why is this a *mutable* pointer? Are there any systems where the system-call/libc-wrapper changes the value?

**Comment by alexcrichton** [comment]
All function definitions are currently verified against the headers in libc itself, so it's mutable b/c libc has it as mutable. As to why that's mutable I'm not sure! The man pages may help though?

**Comment by diekmann** [comment]
Thanks for the reply :+1: I agree that this issue is closed now. I would have two final clarifying questions:

> libc has it as mutable

Do you mean libc did not explicitly mark it as `const`? So to get it immutable here, it would need to be declared as `const` in the C headers of libc?

> The man pages may help though?

By the way, neither the [man](https://linux.die.net/man/2/mmap) page for my Linux system nor the [posix standard](http://pubs.opengroup.org/onlinepubs/9699919799/functions/mmap.html) could give me a hint why any system may change the passed address.

**Comment by alexcrichton** [comment]
Yeah in the header it's mutable, not const. I don't know why though :(
