### ISSUE TITLE
macosx     libc::sysconf(84) as usize   // result 18446744073709551615

### ISSUE THREAD

**Issue by whispermemory** [rust-lang/libc#6]
|- 1-|
|- 2-| extern crate libc;
|- 3-| fn get_num_cpus() -> usize {
|- 4-|     unsafe {
|- 5-|         libc::sysconf(84) as usize
|- 6-|     }
|- 7-| }
|- 8-|
|- 9-| fn main() {
|-10-|    println!("{}", get_num_cpus());//18446744073709551615
|-11-| }

Darwin matoMacBook-Pro.local 13.3.0 Darwin Kernel Version 13.3.0: Tue Jun  3 21:27:35 PDT 2014; root:xnu-2422.110.17~1/RELEASE_X86_64 x86_64

**Comment by whispermemory** [comment]
https://github.com/seanmonstar/num_cpus/issues/2

**Comment by lambdaburrito** [comment]
`84` is only valid for `linux` and not `macos`; i've submitted a pull request to fix this so you can reference it as a constant as `libc::_SC_NPROCESSORS_ONLN` and it will ensure it's the correct value for `macos` 

https://github.com/rust-lang/rust/pull/24376

**Comment by alexcrichton** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/24374, but thanks for the report!

**Comment by whispermemory** [comment]
THANKS
