### ISSUE TITLE
gmtime missing

### ISSUE THREAD

**Issue by Uplifting** [rust-lang/libc#600]
It is in the POSIX spec (not deprecated) and gmtime_r is included (and the pair localtime vs. localtime_r is included, so I'm assuming this is just an oversight).  Hesitant to pull request because I don't want to guess the exception on netbsd.

The relevant lines are 708-719 in `src/unix/mod.rs`

**Comment by alexcrichton** [comment]
Ah yeah if bindings aren't present that just means that they haven't been added yet, feel free to submit a PR!

**Comment by Uplifting** [comment]
[https://github.com/rust-lang/libc/pull/603](https://github.com/rust-lang/libc/pull/603) now a pull request
