### ISSUE TITLE
Missing sync() function

### ISSUE THREAD

**Issue by Razican** [rust-lang/libc#601]
Hello, I'm trying to implement a service that requires the `sync()` function from `unistd.h` in Linux, but I cannot find it. More information [here](https://linux.die.net/man/2/sync).

**Comment by alexcrichton** [comment]
Ah yeah if bindings aren't present that just means that they haven't been added yet, feel free to submit a PR!

**Comment by Razican** [comment]
If I understand it properly, since that's a UNIX API, it should be added to `src/unix/mod.rs`, right? Should I simply add a `pub fn sync();` in the `extern` block? The function does not accept arguments and the return is always success, void.

**Comment by alexcrichton** [comment]
That'd work! There's some [instructions in the README](https://github.com/rust-lang/libc#adding-an-api) about adding an api to this crate.
