### ISSUE TITLE
Why is there no `pthread_setschedparam`

### ISSUE THREAD

**Issue by vityafx** [rust-lang/libc#609]
I want to set a priority for my thread. `std::thread` does not offer this. So I wanted to make my own crate for this. I have found that `libc` crate provides some `pthread` bindings but does not have `setschedparam` function. Why it is so?

**Comment by alexcrichton** [comment]
Nothing is left out intentionally, you're more than welcome to [add an API](https://github.com/rust-lang/libc#adding-an-api)!
