### ISSUE TITLE
uClibc support

### ISSUE THREAD

**Issue by glebpom** [rust-lang/libc#637]
For some reason, uClibc is processed separately (https://github.com/rust-lang/libc/blob/master/src/unix/mod.rs#L888), and for now, only x86_64 and MIPS are implemented. I was trying to compile the app with uClibc on ARM, and it failed on requiring 'unsupported' (https://github.com/rust-lang/libc/blob/master/src/unix/uclibc/mod.rs#L1779). Simple removing of uClibc check in unix/mod.rs made my app compile and working smoothly on ARM. It looks like, at least, on ARM uClibc doesn't require any special binding, and there is no reason to fail compilation in this case.

**Comment by alexcrichton** [comment]
Other Unix bindings are typically for glibc and unlikely to match uclibc, but adding new modules to uclibc sounds fine to me!

**Comment by glebpom** [comment]
This patch https://github.com/glebpom/libc/commit/7da806cca530cf9c9c08eae1eb2b8c59e9390148 works just well for uClibc on ARMv5te. In this particular case, uClibc doesn't require any special code and works well with the ordinary glibc bindings.

**Comment by alexcrichton** [comment]
Oh yeah something like that is unlikely to fail for any one particular program, but you may want to run the `libc-test` crate in this repo as it'll likely report that a lot of constants/signatures are subtly wrong.

**Comment by alexcrichton** [comment]
I believe an initial version of this at least has been added.
