### ISSUE TITLE
getrandom(2) is missing from the bindings

### ISSUE THREAD

**Issue by marmistrz** [rust-lang/libc#659]
We have `getentropy`, but not `getrandom`

**Comment by marmistrz** [comment]
This can't be implemented until glibc in CI becomes 2.25, adding this binding will break the crate for < 2.25.

**Comment by kristate** [comment]
Hi @marmistrz  ! I am trying to clean-up issues: is this still an issue for you?
(btw, I would recommend [lib `rand`](https://crates.io/crates/rand) or other cryptographic libraries instead of relying on `getrandom(2)`)

**Comment by marmistrz** [comment]
@kristate I'm not currently working on the project which needed that, but I still consider this an issue. I should be able use `getrandom` if my libc is new enough. Otherwise, it defies the purpose of this crate.

IIRC the project did something pretty low-level and thus I wanted to use the syscall directly, but I don't remember the details.

maybe you should do a feature build, just like `gtk-rs` does - e.g. I can explicitly demand `glibc >= 2.25` in my `cargo.toml` - or just say that I demand that the libc supports `getrandom`, and then the bindings are generated.

**Comment by gnzlbg** [comment]
The version of glibc being targeted on CI (and therefore, the minimum version of glibc supported), has been updated. Please feel free to submit a PR implementing these.

**Comment by briansmith** [comment]
> The version of glibc being targeted on CI (and therefore, the minimum version of glibc supported), has been updated. Please feel free to submit a PR implementing these.

My understanding from https://lwn.net/Articles/711013/ is that glibc does NOT implement a fallback in the case that the `getrandom()` syscall is unavailable. Is that correct, or have things changed? If so, I agree it is a really good idea to expose `libc::getrandom()` so that no Rust code needs to use the vararg syscall function. (varargs are a bad idea, in general.)
