### ISSUE TITLE
AF_MAX/PF_MAX incorrect on local system

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/libc#665]
I'm running x86_64 Linux and when running `libc-test` I the following:
```
bad AF_MAX value at byte 0: rust: 42 (0x2a) != c 43 (0x2b)
bad PF_MAX value at byte 0: rust: 42 (0x2a) != c 43 (0x2b)
```

I don't remember getting these in the past, but I just upgraded to Fedora 26, so maybe newer libs changed this constant. Tests are also still passing in CI...

**Comment by marmistrz** [comment]
The same for me, Arch Linux, glibc 2.25

**Comment by marmistrz** [comment]
glibc 2.25 has added Qualcomm IPC Router and had to increment `AF_MAX/PF_MAX`:
https://fossies.org/diffs/glibc/2.24_vs_2.25/sysdeps/unix/sysv/linux/bits/socket.h-diff.html

**Comment by Susurrus** [comment]
I think this ties into how does `libc` deal with API changes between OS versions. There's some work to be done to figure that out, and it should include things like this.

**Comment by alexcrichton** [comment]
We should probably just ignore these constants in libc-test, the values don't seem too critical for keeping correct

**Comment by Susurrus** [comment]
I was going to suggest they might just be worth removing, but that doesn't seem like the right answer either.

**Comment by marmistrz** [comment]
Maybe we should instead generate such files during build based on the libc that is currently installed? It can possibly be a problem when rust-libc exports some constants libc doesn't.

**Comment by Susurrus** [comment]
Digging around the internet more, I'm inclined to say that `AF_MAX` and `PF_MAX` should just be removed. I think this would need to wait to 1.0 to do given the backwards compatibility guarantees provided by `libc`, but I can't find any real code that uses `AF_MAX` and PF_MAX`.

In `nix` we don't expose these constants in our socket API which makes me even more inclined to say that these constants are unused.

I searched through all Rust projects on GitHub and in the first 20 pages couldn't find a use for `AF_MAX` that wasn't just declaring it.

**Comment by mati865** [comment]
Since https://github.com/rust-lang/libc/pull/904 tests now skip these 2 values.
Confirmed to pass tests on openSUSE Tumbleweed (rolling release distro with glibc 2.27 right now).

**Comment by gnzlbg** [comment]
I've submitted a PR that deprecates these #1375 . After a couple of releases, if nobody complains, we can remove these.

**Comment by gnzlbg** [comment]
Feel free to submit a PR removing these.

**Comment by Susurrus** [comment]
`NET_MAXID` is included here as it relies on `AF_MAX` on many targets and had the same deprecation notice. Submitted rust-lang/libc#1423
