### ISSUE TITLE
fd_set.fds_bits is not public

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/libc#730]
Was there a reason for this? I know that there are `FD_CLR` and friends, but it seems odd that this one field is private while almost all struct fields for all `libc` types are public.

**Comment by alexcrichton** [comment]
If it matches libc itself seems fine to export!

**Comment by Susurrus** [comment]
I believe this is actually correct, it's just C can't make fields of structs public, but it's the reason why the `FD_CLR()` macros and friends exist. Since those are now included in libc, we can close this issue.
