### ISSUE TITLE
fexecve doesn't exist on mac/ios

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/libc#732]
For some reason it's ignored in build.rs, but my `/usr/include/unistd.h` on Mac OS X 10.11.6 doesn't have it. It's actually nowhere in `/usr/include/`. Using this results in a linking error, so I'd suggest it be removed on those platforms even if it's technically a breaking change (as nobody can possibly be using it on those platforms).

I can file a PR to remove it, but what to do about `build.rs`, anything? Should I change it to be `if mac` for `fexecve` to make sure it never creeps back in accidentally?

**Comment by alexcrichton** [comment]
Seems fine to me yeah to remove! IIRC these are ignored b/c the exec-family of functions are really hard to verify (the signatures in C are tough for ctest to generate to match)
