### ISSUE TITLE
Add VM_FLAGS_* constants on Darwin

### ISSUE THREAD

**Issue by joshlf** [rust-lang/libc#736]
These flags are needed for using superpages on Darwin with `mmap`, and are defined in `mach/vm_statistics.h`.

**Comment by alexcrichton** [comment]
PRs are of course always welcome!

**Comment by joshlf** [comment]
Yeah, I'm definitely planning on it. I've just been busy recently and figured I'd add this in case somebody else was looking for work to do here. That's the plan though.
