### ISSUE TITLE
Potential incorrect type for ptrace requests with musl

### ISSUE THREAD

**Issue by xd009642** [rust-lang/libc#744]
For some reason normal ptrace requests i.e. PTRACE_TRACEME are c_int whereas the ptrace requests related to program registers (i.e. PTRACE_GETREGS) are unsigned integers [musl mod.rs](https://github.com/rust-lang/libc/blob/68463056e5a787dc0ad6bacbfa4cb671c785a3d7/src/unix/notbsd/linux/musl/mod.rs). Now as all these values are used as the request argument to fn ptrace surely the sign should be consistent?

musl is also the only libc environment which has the difference in signedness which also doesn't seem to be mimicking musl itself [ptrace.h musl](https://github.com/esmil/musl/blob/master/include/sys/ptrace.h)

**Comment by alexcrichton** [comment]
While technically a breaking change to fix this, my guess is that it's fine to fix in a point release as it's unlikely to break anyone.

**Comment by xd009642** [comment]
I'd only expect it to make a cast unnecessary for some users. I'll submit a pull request later today then unless it's already being covered :+1:

**Comment by xd009642** [comment]
Closing this issue as #745 is merged!
