### ISSUE TITLE
clock_gettime for macOS 10.12+

### ISSUE THREAD

**Issue by ekmartin** [rust-lang/libc#776]
macOS 10.12 and Xcode 8 added support for `clock_gettime` and [related functions](https://linux.die.net/man/3/clock_gettime). Would it be possible to add these to the macOS libc bindings?

I'd send a PR, but not sure how to do it conditionally since it doesn't seem like the OS version number is included in `cfg`.

Relevant: https://github.com/zeromq/libzmq/issues/2175

**Comment by alexcrichton** [comment]
Seems good to me to add! (PRs are more than welcome!)

**Comment by ekmartin** [comment]
@alexcrichton: but would it be okay to add it to the general `apple/mod.rs` even if it's only supported in newer versions of macOS?

**Comment by alexcrichton** [comment]
Yeah that's fine, this isn't the first symbol of its kind :)
