### ISSUE TITLE
Use union for epoll_event user data (`epoll_data_t`)?

### ISSUE THREAD

**Issue by vojtechkral** [rust-lang/libc#779]
It would make working with epoll a bit more pleasant, but I'm concerned about backcompat problems.
There's no way to make this change in a non-breaking way.
I'd be glad to implement, but I'm checking here first whether it's worth it...

**Comment by alexcrichton** [comment]
Would be great to do! But yes backwards compatible is required

**Comment by vojtechkral** [comment]
Hm, well, I don't really see a way of doing this without breaking compatibility, so I'm gonna close (at least for now).
