### ISSUE TITLE
glibc 2.26 incompatibilities

### ISSUE THREAD

**Issue by vojtechkral** [rust-lang/libc#788]
glibc 2.26 introduces some changes that make `libc-test` not work anymore.

- It [removes `xlocale.h`](https://sourceware.org/glibc/wiki/Release/2.26#Removal_of_.27xlocale.h.27)
- It [removes `SIGUNUSED`](http://man7.org/linux/man-pages/man7/signal.7.html)

**Comment by alexcrichton** [comment]
Thanks for the report! A PR to update this would be most welcome!

**Comment by vojtechkral** [comment]
Fixed by #798
