### ISSUE TITLE
Document ABI changes in release notes

### ISSUE THREAD

**Issue by asomers** [rust-lang/libc#814]
Commit https://github.com/rust-lang/libc/commit/9029cfb9eb76647cf9122a47252f1129eb18a562 changed libc's ABI.  If this was intended, then it should be documented in the release notes.  However, it looks like libc doesn't currently publish release notes.  I suggest keeping a changelog in the style of nix: https://github.com/nix-rust/nix/blob/master/CHANGELOG.md .

**Comment by alexcrichton** [comment]
All changes are mistakes, I don't think there's anything to document. Just need to fix them.

**Comment by alexcrichton** [comment]
Fixed in #813
