### ISSUE TITLE
`pid_t` is not defined for Windows

### ISSUE THREAD

**Issue by shaleh** [rust-lang/libc#832]
It should be a typedef for `c_int`.

Is there a reason `pid_t` is missing? If not, would a PR be accepted?

**Comment by alexcrichton** [comment]
Nothing is left out on purpose so a PR would be more than welcome!

**Comment by shaleh** [comment]
:+1:

**Comment by shaleh** [comment]
Party started......

I did not see any obvious way to have a test that ensures that a type is defined on all supported systems. Did I miss it @alexcrichton ?

**Comment by gnzlbg** [comment]
@alexcrichton this issue should be closed due to https://github.com/rust-lang/libc/pull/833
