### ISSUE TITLE
Considerer using cross in our CI

### ISSUE THREAD

**Issue by malbarbo** [rust-lang/libc#845]
We should discuss using [cross](https://github.com/japaric/cross) in our CI infrastructure.

Pros

- easier to maintain
- support to new targets when they are added
- faster builds? (download the docker image vs build the docker image)
- ...

Cons

- not all targets are available for testing (like bsd targets, in this case we would continue to use the actual approach)
- lost of control (we are adding a external dependecy)
- ...

What do you think @alexcrichton?

**Comment by alexcrichton** [comment]
I'd personally prefer to stick to custom docker images because we tend to want pretty fine-grained control over things like the libc version and versions of various tools installed, and yeah we'd still have to carry support for things like freebsd/openbsd I believe?

**Comment by gnzlbg** [comment]
> I'd personally prefer to stick to custom docker image

`cross` allows you to specify your own docker images, which don't necessarily need to be based on the `cross` ones (although `cross` provides some images that one can build on top). I've been able to reuse cross one in some cases (e.g. adding `objdump` for usage in `stdsimd`), but I had to specify my own in other cases (`cross` ships an "as old as reasonable" libc, and if you need a newer one, you can't build on top of a too old ubuntu distribution). 

> and yeah we'd still have to carry support for things like freebsd/openbsd I believe?

Yeah in complicated projects `cross` isn't a replacement for everything, but more like a replacement for X% of the boilerplate. For example, in `stdsimd` we have the Intel SDE emulator which `cross` does not "natively" support, so for some "weird" targets one will always need some sort of custom `ci` system. 

All in all for `stdsimd` `cross` did not cut that much boiler plate (e.g. we still need custom docker images for basically all non `x86` targets) but it did cut some boiler plate and these docker images are simpler.

However, `stdsimd` only currently uses `qemu-user` which is relatively simple to set up. The amount of boiler-plate required to use, for example, `qemu-system` is much larger. Iff `cross` is able to remove that it might be worth considering using `cross` at least for the `qemu-system` targets.

**Comment by gnzlbg** [comment]
@malbarbo for targets that we are not currently testing, but that cross does support, I wouldn't mind us to start adding CI build jobs that use cross to test them. I think something is better than nothing here. 

However, as @alexcrichton pointed out, we want some fine grained control about some parts of the environment used, like the glibc version. It would be great if cross could support that.

**Comment by gnzlbg** [comment]
So cross is so unmaintained that I don't think this makes sense anymore. Basically cross goals are only supporting the oldest possible glibc versions that actually can compile, while libc needs also to expose newer APIs and be able to test them.
