### ISSUE TITLE
bsd: {get,set}domainname are missing

### ISSUE THREAD

**Issue by lucab** [rust-lang/libc#868]
Currently {get,set}domainname are exposed on Linux and emscripten only. However they are implemented on BSDs too so they should be exposed there are as well:
 * https://www.freebsd.org/cgi/man.cgi?sektion=3&query=gethostname
 * https://man.openbsd.org/setdomainname.3
 * http://netbsd.gw.com/cgi-bin/man-cgi?getdomainname+3+NetBSD-current
 * https://www.dragonflybsd.org/cgi/web-man?command=getdomainname&section=3

**Comment by gnzlbg** [comment]
@lucab could you check out the PR and see if adding `{get,set}domainname` and `gethostname` is enough to close this issue?
