### ISSUE TITLE
Possible typo in comment about c_void's type

### ISSUE THREAD

**Issue by mjbshaw** [rust-lang/libc#878]
I'm happy to send a patch for this, but I'm not 100% sure whether it's the code or the comment that's incorrect. Commit d5c4e55f6554f909e662ef9d13caeaf62663a445 added a comment to `c_void` explaining it's `#[repr(u8)]` because "LLVM expects `void*` to be the same as `i8*`".

The two types are different: `u8` and `i8`. I assume the comment is in error and meant to say `u8*`.

If both the code and comment are correct (and `c_void` is intentionally given a type that isn't the same as LLVM's expectations for `void*`), then perhaps a small note in the comment justifying the difference would be useful. As-is, though, it seems like the code and comment were intended to use the same type, and a small typo crept in.

**Comment by alexcrichton** [comment]
Oh heh this is actually mostly because LLVM doesn't actually have unsigned types, it *only* has `i8` and then it has operations which act in an unsigned fashion. PRs are more than welcome to tweak this though!

**Comment by mjbshaw** [comment]
Thanks for explaining that! I'll close this then. If I think of a decent way to clarify the comment (without being too verbose) I'll send a PR.
