### ISSUE TITLE
Backport changes from Master to 0.2.19 tag

### ISSUE THREAD

**Issue by cneira** [rust-lang/libc#897]
I have a PR for adding EPOLL(5)  for illumos in master,  but crate like mio and iovec pull libc using 0.2.19 tag.  I have a branch "mio" in  https://github.com/cneira/libc  that address this. is it possible to do a PR against this tag?

**Comment by alexcrichton** [comment]
Ah so currently we don't do backports in libc, but would updating to a newer version work?
