### ISSUE TITLE
IFF_ constants should all be c_int

### ISSUE THREAD

**Issue by Susurrus** [rust-lang/libc#915]
#873 added some Linux-specific `IFF_*` constants as `c_short`s, but I believe they should been `c_int`s as all other `IFF_*` constants are `c_int`.

**Comment by kristate** [comment]
@Susurrus @LuoZijun @alexcrichton 
with the #916 merge, can this now be closed?

**Comment by Susurrus** [comment]
#916 didn't change the types for c_int, so no. That will require a 0.3 libc release to do.

**Comment by gnzlbg** [comment]
How come ctest did not catch this ?

**Comment by alexcrichton** [comment]
@gnzlbg constant in C don't really have a type, so ctest can only test the bit pattern of constants, not the types unfortunately :(

**Comment by gnzlbg** [comment]
Ah, I thought that there was a problem with their value.  Maybe one could do a crater run to see what changing these to `c_int` would break ?

**Comment by alexcrichton** [comment]
Seems plausible!

**Comment by gnzlbg** [comment]
I'd be willing to give this a try if somebody submits a PR fixing this.
