### ISSUE TITLE
Interest in more netlink constants in libc

### ISSUE THREAD

**Issue by jbaublitz** [rust-lang/libc#921]
I realize that netlink is a pretty specific use case but is there any interest in me doing a PR to include some of the standard but less common netlink constants? Currently for my crate, I compile a C extention and link to it from Rust to get these constants in my crate and I'd love to have this incorportated into this crate to keep all of the C dependencies in one place. I'm mainly focusing on the constants that signify netlink attribute types in `<linux/netlink.h>` and `<linux/genetlink.h>` as well as potentially `<linux/rtnetlink.h>` as that is the next part of netlink that I plan to implement in my library. There were a number of netlink constants that were not included in libc when I started that now are so I'd be happy to get the rest of them in there if this is a use case you'd be willing to support.

**Comment by faern** [comment]
I'm working on a PR to include these now. I had to add some netlink structs anyway for another use case so I'll bring in the constants you need. See #922, however, the constants have not been pushed there yet.

**Comment by faern** [comment]
However, since `GENL_ID_GENERATE` was deprecated in 2016 (https://github.com/torvalds/linux/commit/a07ea4d9941af5a0c6f0be2a71b51ac9c083c5e5) I'm going to exclude that one.

**Comment by jbaublitz** [comment]
Thanks for this!

**Comment by alexcrichton** [comment]
@jbaublitz there's certainly interest! Basically if it's in headers and it verifies, it should be fine to add.

**Comment by kristate** [comment]
@jbaublitz @faern What is the current status?

**Comment by faern** [comment]
This is merged and done. I'm pretty sure my PR included all the parts @jbaublitz needed.

**Comment by alexcrichton** [comment]
Great!
