### ISSUE TITLE
Hard error compiling libc 0.2.36: #![feature(link_cfg)] missing ?

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/libc#928]
```shell 
 Compiling libc v0.2.36
error[E0658]: is feature gated (see issue #37406)
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.36/src/unix/mod.rs:279:9
    |
279 |         #[link(name = "c", kind = "static", cfg(target_feature = "crt-static"))]
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(link_cfg)] to the crate attributes to enable
```

**Comment by gnzlbg** [comment]
Seems to only fail when building libc with `--no-default-features` on some targets:

* arm-unknown-linux-musleabi
* armv7-unknown-linux-musleabi
* i686-unknown-linux-musl
* x86_64-unknown-linux-musl

**Comment by gnzlbg** [comment]
Looks like `libc`'s CI does not test building libc with `--no-default-features`... opening an issue about this: PLACEHOLDER.

**Comment by alexcrichton** [comment]
Argh this definitely wasn't intentional. Although I'm not sure that the `no_std` build of the musl version of `libc` would work otherwise...

**Comment by gnzlbg** [comment]
They used to work last month just fine :/

**Comment by alexcrichton** [comment]
I forget which PR caused this at this point but I think it's fine to fix whenever basically

**Comment by gnzlbg** [comment]
yeah I am working on a fix :)

**Comment by gnzlbg** [comment]
I don't know if we just need to enable the nightly feature and require nightly for no-std builds, or if there is something better that we can do (like not using the link attribute somehow).

**Comment by alexcrichton** [comment]
Yeah I don't think we should require nightly for no_std builds, but rather we just need to compile it differently when included in libstd and when included in cargo
