### ISSUE TITLE
IPV6_UNICAST_HOPS not defined on Fuchsia

### ISSUE THREAD

**Issue by raphlinus** [rust-lang/libc#932]
#925 added a bunch of `IPV6_MULTICAST_*` definitions, and _mostly_ applied them consistently between notbsd unix and fuchsia, but seems to have left off `IPV6_UNICAST_HOPS` in particular from the fuchsia module. From a shallow look, it seems like a simple oversight, the fix is probably to add it with the same value as notbsd.

This is causing net2 0.2.32 to fail to compile on Fuchsia, I'm temporarily working around this by pinning to net2 0.2.31.

Happy to provide a PR if it's the simple one-liner it appears to be, but wanted to sanity-check first.

ping @bluejekyll as author of the patch

**Comment by alexcrichton** [comment]
Oh yeah a PR to add any missing constants should be totally fine!

**Comment by bluejekyll** [comment]
Thanks for taking care of this. Do the automated tests not cover Fuchsia today?

**Comment by raphlinus** [comment]
Not covered yet, but we're hoping to at some point. It's not trivial to add because it's a whole operating system; it should be possible to ship images that run in qemu, but we don't have stable releases yet.

**Comment by bluejekyll** [comment]
Thanks. I'm worried that there will be a similar problem with Redox as well...
