### ISSUE TITLE
[Win10] libc::{uid_t, gid_t} not found

### ISSUE THREAD

**Issue by JoeyAcc** [rust-lang/libc#940]
I just tried to compile `exa` and `ripgrep` on Win10, both of which which fail with an error starting with:
````
   ... snipped build output ...

   Compiling libz-sys v1.0.18
   Compiling users v0.5.3
error[E0432]: unresolved import `libc::uid_t`
   --> C:\Users\Joey\.cargo\registry\src\github.com-1ecc6299db9ec823\users-0.5.3\src\lib.rs:113:16
    |
113 | pub use libc::{uid_t, gid_t};
    |                ^^^^^ no `uid_t` in the root

error[E0432]: unresolved import `libc::gid_t`
   --> C:\Users\Joey\.cargo\registry\src\github.com-1ecc6299db9ec823\users-0.5.3\src\lib.rs:113:23
    |
113 | pub use libc::{uid_t, gid_t};
    |                       ^^^^^ no `gid_t` in the root

error[E0432]: unresolved import `libc::uid_t`
  --> C:\Users\Joey\.cargo\registry\src\github.com-1ecc6299db9ec823\users-0.5.3\src\base.rs:37:12
   |
37 | use libc::{uid_t, gid_t};
   |            ^^^^^ no `uid_t` in the root

````

From this I infer that  the libc `uid_t` and `gid_t` types don't exist on Windows.  Is this because Windows has no definitions for such types?  Or is it a matter of adding them?

**Comment by alexcrichton** [comment]
Thanks for the report! If Windows has definitions for these types we can add them, otherwise this is as intended (I forget the situation here)

**Comment by gnzlbg** [comment]
@tavianator 's comment hints that this is not something we should fix. Feel free to reopen this if I've misinterpreted it.

**Comment by scoiatael** [comment]
Hey, sorry if that's not the best place to ask this question: would you be opposed to including these types and related functions under Windows MinGW build? MinGW provides (I think) more or less full `unistd.h`. I'd be happy to open a PR :)

**Comment by gnzlbg** [comment]
@scoiatael if the `mingw` headers provide definitions of these types, you can add them to: https://github.com/rust-lang/libc/blob/master/src/windows/gnu.rs

**Comment by tavianator** [comment]
@scoiatael My copy of the mingw-w64 headers doesn't define `uid_t` or `gid_t` either.

**Comment by scoiatael** [comment]
Ah, my bad. These are available on MSYS2, not just MinGW. Is there any way to distinguish between these from Rust side?
