### ISSUE TITLE
Add "_aligned_malloc" on windows platform

### ISSUE THREAD

**Issue by paddyhoran** [rust-lang/libc#953]
Hi,

I'm trying to add windows support for a another library which uses `posix_memalign`.  I have researched to the point of realizing that I need libc to expose `_aligned_malloc` for windows.

I'm willing to have a go at a PR to add it but I'm a little out of my depth...

Could someone more knowledgeable point my in the direction of a similar function already implemented in libc and I will try to have a go adding this one.

Obviously, any other advise is welcome.

Thanks

**Comment by gnzlbg** [comment]
@paddyhoran I can mentor your with your PR, just take a look at the `windows.rs` module: https://github.com/rust-lang/libc/blob/master/src/windows.rs#L201 You just need to add an extern function for it there. You can find its API here: https://msdn.microsoft.com/en-us/library/8z34s9c6.aspx

**Comment by retep998** [comment]
Keep in mind that `aligned_malloc` is *not* the same as `posix_memalign` as memory allocated using `posix_memalign` can be freed using `free` but `_aligned_malloc` memory has to be deallocated specifically using `_aligned_free`.
