### ISSUE TITLE
IPV6_PKTINFO missing in Darwin

### ISSUE THREAD

**Issue by mcginty** [rust-lang/libc#969]
This seems to be because it's undefined unless one of either `__APPLE_USE_RFC_2292` or `__APPLE_USE_RFC_3542` is also defined ([explained in the XNU source here](https://github.com/apple/darwin-xnu/blob/master/bsd/netinet6/in6.h#L499)).

It appears to be a bit of a hairy compatibility situation, but the RFC 3542 code was added 5 years ago, so it's not exactly brand new any more. Is there any precedent for these kinds of situations in libc? It would be nice to have these constants and the `in6_pktinfo` struct available in some form or another.

**Comment by gnzlbg** [comment]
PRs welcome.

**Comment by gnzlbg** [comment]
Thanks!
