### ISSUE TITLE
incorrect html_root_url

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/libc#976]
Currently, the crate’s `doc(html_root_url)` is set as https:\//doc.rust-lang.org/libc/<i>&lt;target&gt;</i>, for example https://doc.rust-lang.org/libc/x86_64-unknown-linux-gnu, but that will redirect to https:\//docs.rs/libc/<i>&lt;target&gt;</i>, for example https://docs.rs/libc/x86_64-unknown-linux-gnu which simply states that the requested resource/crate does not exist.

**Comment by alexcrichton** [comment]
Ah oops! The domain here is intended to be rust-lang.github.io, which should fix the issue!
