### ISSUE TITLE
TCP_KEEPINTVL and TCP_KEEPCNT for *bsd

### ISSUE THREAD

**Issue by aep** [rust-lang/libc#978]
nix author would prefer these to be available on all bsd variants that have them before i can expose them on linux. 

https://github.com/nix-rust/nix/pull/889

I don't know how bsd works at all unfortunately, otherwise i'd just open a PR.  Syscall values are probably different than on linux.

**Comment by aep** [comment]
couldn't find it in freebsd (probably this?  https://github.com/freebsd/freebsd/tree/master/lib/libc)  or openbsd (this? https://github.com/robertbachmann/openbsd-libc)   no idea how to proceed.

**Comment by semarie** [comment]
a git mirror of openbsd repository is at https://github.com/openbsd/src/

`TCP_KEEPINTVL` and `TCP_KEEPCNT` are unavailable, but some others `TCP_` constants are available, see https://github.com/openbsd/src/blob/master/sys/netinet/tcp.h#L124

**Comment by Susurrus** [comment]
@aep is this issue resolved now that #982 was merged?

**Comment by aep** [comment]
@Susurrus if you're happy with it, i am :)
