### ISSUE TITLE
tests failing on macOS High Sierra

### ISSUE THREAD

**Issue by mcginty** [rust-lang/libc#981]
This is from running the tests on my laptop.
```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.4
BuildVersion:   17E199
```

failure output:
```
bad syslog function pointer: rust: 140734611868871 (0x7fff548c4cc7) != c 140734611869453 (0x7fff548c4f0d)
bad VM_FLAGS_USER_ALLOCATE value at byte 0: rust: 27 (0x1b) != c 31 (0x1f)
bad VM_FLAGS_USER_MAP value at byte 0: rust: 27 (0x1b) != c 31 (0x1f)
```

and here's the relevant snippet of my `/usr/include/mach/vm_statistics.h` of the conflicting VM_* constants. I'm not sure how to help with the syslog function pointer error, but happy to give more info as requested.

```
/* These are the flags that we accept from user-space */
#define VM_FLAGS_USER_ALLOCATE	(VM_FLAGS_FIXED |		\
				 VM_FLAGS_ANYWHERE |		\
				 VM_FLAGS_PURGABLE |		\
				 VM_FLAGS_4GB_CHUNK |		\
				 VM_FLAGS_RANDOM_ADDR |		\
				 VM_FLAGS_NO_CACHE |		\
				 VM_FLAGS_OVERWRITE |		\
				 VM_FLAGS_SUPERPAGE_MASK |	\
				 VM_FLAGS_ALIAS_MASK)
#define VM_FLAGS_USER_MAP	(VM_FLAGS_USER_ALLOCATE |	\
				 VM_FLAGS_RETURN_4K_DATA_ADDR |	\
				 VM_FLAGS_RETURN_DATA_ADDR)
```

**Comment by alexcrichton** [comment]
Thanks for the report! These sorts of things can change over time and it should be fine to tweak the values as they change.

**Comment by dpogretskiy** [comment]
MacOS's libc, which is somewhere in their SDK, is not based on glibc, there are a lot of inconsistencies, such as different struct layouts, same consts with different values and so on. Maybe disable libc build for OS X entirely since it's not reliable in any way, unfortunately. Other then full sanity check and somewhat reimplemenation for OSX and probably BSD targets.

**Comment by gnzlbg** [comment]
>  Thanks for the report! These sorts of things can change over time and it should be fine to tweak the values as they change.

This means that people can't target some SDK versions with libc. These constants changed again in xcode10. I can update them, but then people will stop being able to target xcode9.2 with them. What's worse is that if the std library use them as options to apple APIs, well depending on the system we might be calling APIs with different options =/

**Comment by palfrey** [comment]
I've just hit a similar issue with 10.14 and NET_RT_MAXID (10 in git, 11 in 10.14). Does anyone know of a `cfg!` way or similar to match a OS X version?

**Comment by gnzlbg** [comment]
You might want to check the `mach` crate. It has a `mach-test` crate inside like `libc-test` crate, which contains some code for detecting the `osx` version and using that with ctest: https://github.com/fitzgen/mach/blob/master/mach-test/build.rs#L4
