### ISSUE TITLE
bad NFT_* value errors

### ISSUE THREAD

**Issue by canndrew** [rust-lang/libc#996]
When I try to run libc-test on my machine I get the following:

```
bad NFT_TABLE_MAXNAMELEN value at byte 0: rust: 0 (0x0) != c 32 (0x20)
bad NFT_TABLE_MAXNAMELEN value at byte 1: rust: 1 (0x1) != c 0 (0x0)
bad NFT_CHAIN_MAXNAMELEN value at byte 0: rust: 0 (0x0) != c 32 (0x20)
bad NFT_CHAIN_MAXNAMELEN value at byte 1: rust: 1 (0x1) != c 0 (0x0)
bad NFT_SET_MAXNAMELEN value at byte 0: rust: 0 (0x0) != c 32 (0x20)
bad NFT_SET_MAXNAMELEN value at byte 1: rust: 1 (0x1) != c 0 (0x0)
bad NFT_OBJ_MAXNAMELEN value at byte 0: rust: 0 (0x0) != c 32 (0x20)
bad NFT_OBJ_MAXNAMELEN value at byte 1: rust: 1 (0x1) != c 0 (0x0)
```

This is on an x86_64 Gentoo linux machine.

**Comment by faern** [comment]
My guess is that you are running a somewhat older kernel? For example `NFT_SET_MAXNAMELEN` was bumped from 32 to 256 in 4.13 I believe. This is a problem with libc as it's currently implemented. It can't handle platform constants changing between versions. It does not pull in whatever value your system has, but rather a hardcoded value corresponding with the latest release of that given platform :man_shrugging:

**Comment by gnzlbg** [comment]
Fixed on master.
